import type { VocabCard } from '../../types/domain'

// Flashcard từ vựng theo chủ đề TV-xx — Mục 4.2 URD.
// Giai đoạn 3: TV-07 (Thể thao & sở thích), xác thực mô hình flashcard +
// spaced repetition. Giai đoạn 6: mở rộng thêm 5 chủ đề tần suất cao trong
// đề thi thật (gia đình, trường học, thức ăn, động vật, giao thông).
export const vocabCards: VocabCard[] = [
  { id: 'TV07-01', word: 'football', meaning: 'bóng đá', example: 'He plays football every weekend.', topicId: 'TV-07' },
  { id: 'TV07-02', word: 'basketball', meaning: 'bóng rổ', example: 'She is good at basketball.', topicId: 'TV-07' },
  { id: 'TV07-03', word: 'swim', meaning: 'bơi', example: 'We swim in the lake in summer.', topicId: 'TV-07' },
  { id: 'TV07-04', word: 'team', meaning: 'đội, nhóm', example: 'Our team won the match.', topicId: 'TV-07' },
  { id: 'TV07-05', word: 'match', meaning: 'trận đấu', example: 'The football match starts at 3 pm.', topicId: 'TV-07' },
  { id: 'TV07-06', word: 'goal', meaning: 'bàn thắng', example: 'Minh scored the winning goal.', topicId: 'TV-07' },
  { id: 'TV07-07', word: 'player', meaning: 'cầu thủ, người chơi', example: 'He is the best player on the team.', topicId: 'TV-07' },
  { id: 'TV07-08', word: 'practice', meaning: 'luyện tập', example: 'I practice badminton every Tuesday.', topicId: 'TV-07' },
  { id: 'TV07-09', word: 'hobby', meaning: 'sở thích', example: 'Reading comic books is my hobby.', topicId: 'TV-07' },
  { id: 'TV07-10', word: 'race', meaning: 'cuộc đua', example: 'They ran a race around the park.', topicId: 'TV-07' },
  { id: 'TV07-11', word: 'champion', meaning: 'nhà vô địch', example: 'She became the champion of the chess club.', topicId: 'TV-07' },
  { id: 'TV07-12', word: 'exercise', meaning: 'sự luyện tập, bài tập thể dục', example: 'Exercise is good for your health.', topicId: 'TV-07' },
  { id: 'TV07-13', word: 'score', meaning: 'ghi điểm', example: 'He scored three goals in one match.', topicId: 'TV-07' },
  { id: 'TV07-14', word: 'coach', meaning: 'huấn luyện viên', example: 'Our coach teaches us new skills every day.', topicId: 'TV-07' },

  // TV-01: Gia đình & bản thân
  { id: 'TV01-01', word: 'father', meaning: 'bố', example: 'My father works in a hospital.', topicId: 'TV-01' },
  { id: 'TV01-02', word: 'mother', meaning: 'mẹ', example: 'My mother cooks dinner every evening.', topicId: 'TV-01' },
  { id: 'TV01-03', word: 'brother', meaning: 'anh/em trai', example: 'I have an older brother.', topicId: 'TV-01' },
  { id: 'TV01-04', word: 'sister', meaning: 'chị/em gái', example: 'My sister is younger than me.', topicId: 'TV-01' },
  { id: 'TV01-05', word: 'grandparents', meaning: 'ông bà', example: 'We visit our grandparents every weekend.', topicId: 'TV-01' },
  { id: 'TV01-06', word: 'cousin', meaning: 'anh/chị/em họ', example: 'My cousin lives in Da Nang.', topicId: 'TV-01' },
  { id: 'TV01-07', word: 'parents', meaning: 'cha mẹ', example: 'My parents love me very much.', topicId: 'TV-01' },
  { id: 'TV01-08', word: 'baby', meaning: 'em bé', example: 'The baby is sleeping in the room.', topicId: 'TV-01' },
  { id: 'TV01-09', word: 'family', meaning: 'gia đình', example: 'I love spending time with my family.', topicId: 'TV-01' },
  { id: 'TV01-10', word: 'name', meaning: 'tên', example: 'What is your name?', topicId: 'TV-01' },
  { id: 'TV01-11', word: 'age', meaning: 'tuổi', example: 'What is your age?', topicId: 'TV-01' },
  { id: 'TV01-12', word: 'birthday', meaning: 'sinh nhật', example: 'My birthday is in June.', topicId: 'TV-01' },
  { id: 'TV01-13', word: 'kind', meaning: 'tốt bụng', example: 'My grandmother is very kind.', topicId: 'TV-01' },
  { id: 'TV01-14', word: 'friendly', meaning: 'thân thiện', example: 'My new classmate is friendly.', topicId: 'TV-01' },

  // TV-02: Trường học & môn học
  { id: 'TV02-01', word: 'classroom', meaning: 'lớp học', example: 'Our classroom is on the second floor.', topicId: 'TV-02' },
  { id: 'TV02-02', word: 'teacher', meaning: 'giáo viên', example: 'Our teacher explains lessons clearly.', topicId: 'TV-02' },
  { id: 'TV02-03', word: 'student', meaning: 'học sinh', example: 'There are thirty students in my class.', topicId: 'TV-02' },
  { id: 'TV02-04', word: 'subject', meaning: 'môn học', example: 'Math is my favorite subject.', topicId: 'TV-02' },
  { id: 'TV02-05', word: 'homework', meaning: 'bài tập về nhà', example: 'I do my homework after dinner.', topicId: 'TV-02' },
  { id: 'TV02-06', word: 'timetable', meaning: 'thời khóa biểu', example: "Check the timetable for tomorrow's classes.", topicId: 'TV-02' },
  { id: 'TV02-07', word: 'exam', meaning: 'kỳ thi', example: 'The English exam is next Monday.', topicId: 'TV-02' },
  { id: 'TV02-08', word: 'library', meaning: 'thư viện', example: 'I borrow books from the library.', topicId: 'TV-02' },
  { id: 'TV02-09', word: 'playground', meaning: 'sân chơi', example: 'We play football in the playground.', topicId: 'TV-02' },
  { id: 'TV02-10', word: 'break time', meaning: 'giờ ra chơi', example: 'We eat snacks during break time.', topicId: 'TV-02' },
  { id: 'TV02-11', word: 'uniform', meaning: 'đồng phục', example: 'Students wear a uniform on Mondays.', topicId: 'TV-02' },
  { id: 'TV02-12', word: 'blackboard', meaning: 'bảng đen', example: 'The teacher writes on the blackboard.', topicId: 'TV-02' },
  { id: 'TV02-13', word: 'principal', meaning: 'hiệu trưởng', example: 'The principal gave a speech today.', topicId: 'TV-02' },
  { id: 'TV02-14', word: 'score', meaning: 'điểm số', example: 'She got a high score on the test.', topicId: 'TV-02' },

  // TV-04: Thức ăn & đồ uống
  { id: 'TV04-01', word: 'rice', meaning: 'cơm, gạo', example: 'We eat rice every day.', topicId: 'TV-04' },
  { id: 'TV04-02', word: 'bread', meaning: 'bánh mì', example: 'I have bread and milk for breakfast.', topicId: 'TV-04' },
  { id: 'TV04-03', word: 'vegetable', meaning: 'rau', example: 'Vegetables are good for your health.', topicId: 'TV-04' },
  { id: 'TV04-04', word: 'fruit', meaning: 'trái cây', example: 'I eat fruit after lunch.', topicId: 'TV-04' },
  { id: 'TV04-05', word: 'meat', meaning: 'thịt', example: "He doesn't eat much meat.", topicId: 'TV-04' },
  { id: 'TV04-06', word: 'fish', meaning: 'cá', example: 'My mother cooks fish for dinner.', topicId: 'TV-04' },
  { id: 'TV04-07', word: 'egg', meaning: 'trứng', example: 'I had a boiled egg this morning.', topicId: 'TV-04' },
  { id: 'TV04-08', word: 'milk', meaning: 'sữa', example: 'Children should drink milk every day.', topicId: 'TV-04' },
  { id: 'TV04-09', word: 'juice', meaning: 'nước ép', example: 'I like orange juice very much.', topicId: 'TV-04' },
  { id: 'TV04-10', word: 'noodles', meaning: 'mì', example: 'We had noodles for lunch.', topicId: 'TV-04' },
  { id: 'TV04-11', word: 'snack', meaning: 'đồ ăn vặt', example: 'She bought some snacks for the trip.', topicId: 'TV-04' },
  { id: 'TV04-12', word: 'sweet', meaning: 'ngọt', example: 'This cake is too sweet for me.', topicId: 'TV-04' },
  { id: 'TV04-13', word: 'delicious', meaning: 'ngon', example: 'The soup smells delicious.', topicId: 'TV-04' },
  { id: 'TV04-14', word: 'hungry', meaning: 'đói', example: 'I am hungry after football practice.', topicId: 'TV-04' },

  // TV-05: Động vật & thiên nhiên
  { id: 'TV05-01', word: 'dog', meaning: 'chó', example: 'My dog likes playing in the yard.', topicId: 'TV-05' },
  { id: 'TV05-02', word: 'cat', meaning: 'mèo', example: 'The cat is sleeping on the chair.', topicId: 'TV-05' },
  { id: 'TV05-03', word: 'bird', meaning: 'chim', example: 'Birds sing early in the morning.', topicId: 'TV-05' },
  { id: 'TV05-04', word: 'elephant', meaning: 'voi', example: 'An elephant is a very big animal.', topicId: 'TV-05' },
  { id: 'TV05-05', word: 'tiger', meaning: 'hổ', example: 'The tiger is the king of the forest.', topicId: 'TV-05' },
  { id: 'TV05-06', word: 'monkey', meaning: 'khỉ', example: 'Monkeys can climb trees quickly.', topicId: 'TV-05' },
  { id: 'TV05-07', word: 'forest', meaning: 'rừng', example: 'Many animals live in the forest.', topicId: 'TV-05' },
  { id: 'TV05-08', word: 'mountain', meaning: 'núi', example: 'We climbed a high mountain last summer.', topicId: 'TV-05' },
  { id: 'TV05-09', word: 'river', meaning: 'dòng sông', example: 'The river flows through the village.', topicId: 'TV-05' },
  { id: 'TV05-10', word: 'tree', meaning: 'cây', example: 'We planted a tree in the garden.', topicId: 'TV-05' },
  { id: 'TV05-11', word: 'flower', meaning: 'hoa', example: 'These flowers smell very nice.', topicId: 'TV-05' },
  { id: 'TV05-12', word: 'sky', meaning: 'bầu trời', example: 'The sky is blue and clear today.', topicId: 'TV-05' },
  { id: 'TV05-13', word: 'wild', meaning: 'hoang dã', example: 'Wild animals live in the jungle.', topicId: 'TV-05' },
  { id: 'TV05-14', word: 'protect', meaning: 'bảo vệ', example: 'We should protect wild animals.', topicId: 'TV-05' },

  // TV-09: Thành phố, phương hướng & phương tiện giao thông
  { id: 'TV09-01', word: 'city', meaning: 'thành phố', example: 'Ha Noi is a big city.', topicId: 'TV-09' },
  { id: 'TV09-02', word: 'street', meaning: 'con phố', example: 'There are many shops on this street.', topicId: 'TV-09' },
  { id: 'TV09-03', word: 'bus', meaning: 'xe buýt', example: 'I go to school by bus.', topicId: 'TV-09' },
  { id: 'TV09-04', word: 'bicycle', meaning: 'xe đạp', example: 'She rides her bicycle to school.', topicId: 'TV-09' },
  { id: 'TV09-05', word: 'car', meaning: 'ô tô', example: 'My father drives a car to work.', topicId: 'TV-09' },
  { id: 'TV09-06', word: 'train', meaning: 'tàu hỏa', example: 'We traveled by train to Hue.', topicId: 'TV-09' },
  { id: 'TV09-07', word: 'airport', meaning: 'sân bay', example: 'The airport is far from the city center.', topicId: 'TV-09' },
  { id: 'TV09-08', word: 'traffic light', meaning: 'đèn giao thông', example: 'Stop when the traffic light is red.', topicId: 'TV-09' },
  { id: 'TV09-09', word: 'left', meaning: 'bên trái', example: 'Turn left at the corner.', topicId: 'TV-09' },
  { id: 'TV09-10', word: 'right', meaning: 'bên phải', example: 'The post office is on your right.', topicId: 'TV-09' },
  { id: 'TV09-11', word: 'straight', meaning: 'thẳng', example: 'Go straight and you will see the school.', topicId: 'TV-09' },
  { id: 'TV09-12', word: 'map', meaning: 'bản đồ', example: 'Look at the map to find the way.', topicId: 'TV-09' },
  { id: 'TV09-13', word: 'crowded', meaning: 'đông đúc', example: 'The street is crowded in the morning.', topicId: 'TV-09' },
  { id: 'TV09-14', word: 'direction', meaning: 'phương hướng', example: 'Can you tell me the direction to the park?', topicId: 'TV-09' },
]
