import type { VocabCard } from '../../types/domain'

// Flashcard từ vựng theo chủ đề TV-xx — Mục 4.2 URD.
// Giai đoạn 3: TV-07 (Thể thao & sở thích), xác thực mô hình flashcard +
// spaced repetition. Giai đoạn 6: mở rộng thêm 5 chủ đề tần suất cao trong
// đề thi thật (gia đình, trường học, thức ăn, động vật, giao thông).
// Giai đoạn 9: bổ sung mỗi chủ đề 6 từ chất lượng cao hay gặp trong đề thi
// (14 → 20 từ/chủ đề), và bổ sung loại từ + phiên âm IPA giọng Anh-Mỹ
// (General American) cho toàn bộ 280 thẻ — FlashcardsPage phát âm bằng
// Web Speech API (lang "en-US") dựa trên chính từ (`word`), phiên âm chỉ để
// hiển thị tham khảo.
export const vocabCards: VocabCard[] = [
  { id: 'TV07-01', word: 'football', partOfSpeech: 'n.', phonetic: '/ˈfʊt.bɔːl/', meaning: 'bóng đá', example: 'He plays football every weekend.', topicId: 'TV-07' },
  { id: 'TV07-02', word: 'basketball', partOfSpeech: 'n.', phonetic: '/ˈbæs.kɪt.bɔːl/', meaning: 'bóng rổ', example: 'She is good at basketball.', topicId: 'TV-07' },
  { id: 'TV07-03', word: 'swim', partOfSpeech: 'v.', phonetic: '/swɪm/', meaning: 'bơi', example: 'We swim in the lake in summer.', topicId: 'TV-07' },
  { id: 'TV07-04', word: 'team', partOfSpeech: 'n.', phonetic: '/tiːm/', meaning: 'đội, nhóm', example: 'Our team won the match.', topicId: 'TV-07' },
  { id: 'TV07-05', word: 'match', partOfSpeech: 'n.', phonetic: '/mætʃ/', meaning: 'trận đấu', example: 'The football match starts at 3 pm.', topicId: 'TV-07' },
  { id: 'TV07-06', word: 'goal', partOfSpeech: 'n.', phonetic: '/ɡoʊl/', meaning: 'bàn thắng', example: 'Minh scored the winning goal.', topicId: 'TV-07' },
  { id: 'TV07-07', word: 'player', partOfSpeech: 'n.', phonetic: '/ˈpleɪ.ɚ/', meaning: 'cầu thủ, người chơi', example: 'He is the best player on the team.', topicId: 'TV-07' },
  { id: 'TV07-08', word: 'practice', partOfSpeech: 'v./n.', phonetic: '/ˈpræk.tɪs/', meaning: 'luyện tập', example: 'I practice badminton every Tuesday.', topicId: 'TV-07' },
  { id: 'TV07-09', word: 'hobby', partOfSpeech: 'n.', phonetic: '/ˈhɑː.bi/', meaning: 'sở thích', example: 'Reading comic books is my hobby.', topicId: 'TV-07' },
  { id: 'TV07-10', word: 'race', partOfSpeech: 'n.', phonetic: '/reɪs/', meaning: 'cuộc đua', example: 'They ran a race around the park.', topicId: 'TV-07' },
  { id: 'TV07-11', word: 'champion', partOfSpeech: 'n.', phonetic: '/ˈtʃæm.pi.ən/', meaning: 'nhà vô địch', example: 'She became the champion of the chess club.', topicId: 'TV-07' },
  { id: 'TV07-12', word: 'exercise', partOfSpeech: 'n./v.', phonetic: '/ˈek.sɚ.saɪz/', meaning: 'sự luyện tập, bài tập thể dục', example: 'Exercise is good for your health.', topicId: 'TV-07' },
  { id: 'TV07-13', word: 'score', partOfSpeech: 'v./n.', phonetic: '/skɔːr/', meaning: 'ghi điểm', example: 'He scored three goals in one match.', topicId: 'TV-07' },
  { id: 'TV07-14', word: 'coach', partOfSpeech: 'n.', phonetic: '/koʊtʃ/', meaning: 'huấn luyện viên', example: 'Our coach teaches us new skills every day.', topicId: 'TV-07' },
  { id: 'TV07-15', word: 'compete', partOfSpeech: 'v.', phonetic: '/kəmˈpiːt/', meaning: 'thi đấu, cạnh tranh', example: 'Our school will compete against three others.', topicId: 'TV-07' },
  { id: 'TV07-16', word: 'medal', partOfSpeech: 'n.', phonetic: '/ˈmed.əl/', meaning: 'huy chương', example: 'She won a gold medal at the sports day.', topicId: 'TV-07' },
  { id: 'TV07-17', word: 'skillful', partOfSpeech: 'adj.', phonetic: '/ˈskɪl.fəl/', meaning: 'khéo léo, có kỹ năng tốt', example: 'He is a skillful badminton player.', topicId: 'TV-07' },
  { id: 'TV07-18', word: 'training', partOfSpeech: 'n.', phonetic: '/ˈtreɪ.nɪŋ/', meaning: 'sự huấn luyện, tập luyện', example: 'The team has training every afternoon.', topicId: 'TV-07' },
  { id: 'TV07-19', word: 'opponent', partOfSpeech: 'n.', phonetic: '/əˈpoʊ.nənt/', meaning: 'đối thủ', example: 'Our opponent played very well today.', topicId: 'TV-07' },
  { id: 'TV07-20', word: 'victory', partOfSpeech: 'n.', phonetic: '/ˈvɪk.tər.i/', meaning: 'chiến thắng', example: 'The whole class celebrated the victory.', topicId: 'TV-07' },

  // TV-01: Gia đình & bản thân
  { id: 'TV01-01', word: 'father', partOfSpeech: 'n.', phonetic: '/ˈfɑː.ðɚ/', meaning: 'bố', example: 'My father works in a hospital.', topicId: 'TV-01' },
  { id: 'TV01-02', word: 'mother', partOfSpeech: 'n.', phonetic: '/ˈmʌð.ɚ/', meaning: 'mẹ', example: 'My mother cooks dinner every evening.', topicId: 'TV-01' },
  { id: 'TV01-03', word: 'brother', partOfSpeech: 'n.', phonetic: '/ˈbrʌð.ɚ/', meaning: 'anh/em trai', example: 'I have an older brother.', topicId: 'TV-01' },
  { id: 'TV01-04', word: 'sister', partOfSpeech: 'n.', phonetic: '/ˈsɪs.tɚ/', meaning: 'chị/em gái', example: 'My sister is younger than me.', topicId: 'TV-01' },
  { id: 'TV01-05', word: 'grandparents', partOfSpeech: 'n.', phonetic: '/ˈɡrænd.per.ənts/', meaning: 'ông bà', example: 'We visit our grandparents every weekend.', topicId: 'TV-01' },
  { id: 'TV01-06', word: 'cousin', partOfSpeech: 'n.', phonetic: '/ˈkʌz.ən/', meaning: 'anh/chị/em họ', example: 'My cousin lives in Da Nang.', topicId: 'TV-01' },
  { id: 'TV01-07', word: 'parents', partOfSpeech: 'n.', phonetic: '/ˈper.ənts/', meaning: 'cha mẹ', example: 'My parents love me very much.', topicId: 'TV-01' },
  { id: 'TV01-08', word: 'baby', partOfSpeech: 'n.', phonetic: '/ˈbeɪ.bi/', meaning: 'em bé', example: 'The baby is sleeping in the room.', topicId: 'TV-01' },
  { id: 'TV01-09', word: 'family', partOfSpeech: 'n.', phonetic: '/ˈfæm.ə.li/', meaning: 'gia đình', example: 'I love spending time with my family.', topicId: 'TV-01' },
  { id: 'TV01-10', word: 'name', partOfSpeech: 'n.', phonetic: '/neɪm/', meaning: 'tên', example: 'What is your name?', topicId: 'TV-01' },
  { id: 'TV01-11', word: 'age', partOfSpeech: 'n.', phonetic: '/eɪdʒ/', meaning: 'tuổi', example: 'What is your age?', topicId: 'TV-01' },
  { id: 'TV01-12', word: 'birthday', partOfSpeech: 'n.', phonetic: '/ˈbɝːθ.deɪ/', meaning: 'sinh nhật', example: 'My birthday is in June.', topicId: 'TV-01' },
  { id: 'TV01-13', word: 'kind', partOfSpeech: 'adj.', phonetic: '/kaɪnd/', meaning: 'tốt bụng', example: 'My grandmother is very kind.', topicId: 'TV-01' },
  { id: 'TV01-14', word: 'friendly', partOfSpeech: 'adj.', phonetic: '/ˈfrend.li/', meaning: 'thân thiện', example: 'My new classmate is friendly.', topicId: 'TV-01' },
  { id: 'TV01-15', word: 'relative', partOfSpeech: 'n.', phonetic: '/ˈrel.ə.tɪv/', meaning: 'họ hàng', example: 'Many relatives came to the party.', topicId: 'TV-01' },
  { id: 'TV01-16', word: 'neighbor', partOfSpeech: 'n.', phonetic: '/ˈneɪ.bɚ/', meaning: 'hàng xóm', example: 'Our neighbor is very friendly.', topicId: 'TV-01' },
  { id: 'TV01-17', word: 'resemble', partOfSpeech: 'v.', phonetic: '/rɪˈzem.bəl/', meaning: 'giống (ai)', example: 'I resemble my mother a lot.', topicId: 'TV-01' },
  { id: 'TV01-18', word: 'generous', partOfSpeech: 'adj.', phonetic: '/ˈdʒen.ər.əs/', meaning: 'hào phóng', example: 'My uncle is very generous to us.', topicId: 'TV-01' },
  { id: 'TV01-19', word: 'polite', partOfSpeech: 'adj.', phonetic: '/pəˈlaɪt/', meaning: 'lịch sự', example: 'You should be polite to older people.', topicId: 'TV-01' },
  { id: 'TV01-20', word: 'only child', partOfSpeech: 'n. phr.', phonetic: '/ˈoʊn.li tʃaɪld/', meaning: 'con một', example: 'She is an only child in her family.', topicId: 'TV-01' },

  // TV-02: Trường học & môn học
  { id: 'TV02-01', word: 'classroom', partOfSpeech: 'n.', phonetic: '/ˈklæs.ruːm/', meaning: 'lớp học', example: 'Our classroom is on the second floor.', topicId: 'TV-02' },
  { id: 'TV02-02', word: 'teacher', partOfSpeech: 'n.', phonetic: '/ˈtiː.tʃɚ/', meaning: 'giáo viên', example: 'Our teacher explains lessons clearly.', topicId: 'TV-02' },
  { id: 'TV02-03', word: 'student', partOfSpeech: 'n.', phonetic: '/ˈstuː.dənt/', meaning: 'học sinh', example: 'There are thirty students in my class.', topicId: 'TV-02' },
  { id: 'TV02-04', word: 'subject', partOfSpeech: 'n.', phonetic: '/ˈsʌb.dʒɪkt/', meaning: 'môn học', example: 'Math is my favorite subject.', topicId: 'TV-02' },
  { id: 'TV02-05', word: 'homework', partOfSpeech: 'n.', phonetic: '/ˈhoʊm.wɝːk/', meaning: 'bài tập về nhà', example: 'I do my homework after dinner.', topicId: 'TV-02' },
  { id: 'TV02-06', word: 'timetable', partOfSpeech: 'n.', phonetic: '/ˈtaɪm.teɪ.bəl/', meaning: 'thời khóa biểu', example: "Check the timetable for tomorrow's classes.", topicId: 'TV-02' },
  { id: 'TV02-07', word: 'exam', partOfSpeech: 'n.', phonetic: '/ɪɡˈzæm/', meaning: 'kỳ thi', example: 'The English exam is next Monday.', topicId: 'TV-02' },
  { id: 'TV02-08', word: 'library', partOfSpeech: 'n.', phonetic: '/ˈlaɪ.brer.i/', meaning: 'thư viện', example: 'I borrow books from the library.', topicId: 'TV-02' },
  { id: 'TV02-09', word: 'playground', partOfSpeech: 'n.', phonetic: '/ˈpleɪ.ɡraʊnd/', meaning: 'sân chơi', example: 'We play football in the playground.', topicId: 'TV-02' },
  { id: 'TV02-10', word: 'break time', partOfSpeech: 'n. phr.', phonetic: '/ˈbreɪk taɪm/', meaning: 'giờ ra chơi', example: 'We eat snacks during break time.', topicId: 'TV-02' },
  { id: 'TV02-11', word: 'uniform', partOfSpeech: 'n.', phonetic: '/ˈjuː.nə.fɔːrm/', meaning: 'đồng phục', example: 'Students wear a uniform on Mondays.', topicId: 'TV-02' },
  { id: 'TV02-12', word: 'blackboard', partOfSpeech: 'n.', phonetic: '/ˈblæk.bɔːrd/', meaning: 'bảng đen', example: 'The teacher writes on the blackboard.', topicId: 'TV-02' },
  { id: 'TV02-13', word: 'principal', partOfSpeech: 'n.', phonetic: '/ˈprɪn.sə.pəl/', meaning: 'hiệu trưởng', example: 'The principal gave a speech today.', topicId: 'TV-02' },
  { id: 'TV02-14', word: 'score', partOfSpeech: 'n.', phonetic: '/skɔːr/', meaning: 'điểm số', example: 'She got a high score on the test.', topicId: 'TV-02' },
  { id: 'TV02-15', word: 'lesson', partOfSpeech: 'n.', phonetic: '/ˈles.ən/', meaning: 'bài học', example: "Today's lesson is about past simple.", topicId: 'TV-02' },
  { id: 'TV02-16', word: 'term', partOfSpeech: 'n.', phonetic: '/tɝːm/', meaning: 'học kỳ', example: 'We have two terms in a school year.', topicId: 'TV-02' },
  { id: 'TV02-17', word: 'absent', partOfSpeech: 'adj.', phonetic: '/ˈæb.sənt/', meaning: 'vắng mặt', example: 'He was absent from school yesterday.', topicId: 'TV-02' },
  { id: 'TV02-18', word: 'review', partOfSpeech: 'v.', phonetic: '/rɪˈvjuː/', meaning: 'ôn tập', example: 'We reviewed the whole unit before the test.', topicId: 'TV-02' },
  { id: 'TV02-19', word: 'achieve', partOfSpeech: 'v.', phonetic: '/əˈtʃiːv/', meaning: 'đạt được', example: 'She achieved a high score this term.', topicId: 'TV-02' },
  { id: 'TV02-20', word: 'classmate', partOfSpeech: 'n.', phonetic: '/ˈklæs.meɪt/', meaning: 'bạn cùng lớp', example: 'My classmates are very friendly.', topicId: 'TV-02' },

  // TV-04: Thức ăn & đồ uống
  { id: 'TV04-01', word: 'rice', partOfSpeech: 'n.', phonetic: '/raɪs/', meaning: 'cơm, gạo', example: 'We eat rice every day.', topicId: 'TV-04' },
  { id: 'TV04-02', word: 'bread', partOfSpeech: 'n.', phonetic: '/bred/', meaning: 'bánh mì', example: 'I have bread and milk for breakfast.', topicId: 'TV-04' },
  { id: 'TV04-03', word: 'vegetable', partOfSpeech: 'n.', phonetic: '/ˈvedʒ.tə.bəl/', meaning: 'rau', example: 'Vegetables are good for your health.', topicId: 'TV-04' },
  { id: 'TV04-04', word: 'fruit', partOfSpeech: 'n.', phonetic: '/fruːt/', meaning: 'trái cây', example: 'I eat fruit after lunch.', topicId: 'TV-04' },
  { id: 'TV04-05', word: 'meat', partOfSpeech: 'n.', phonetic: '/miːt/', meaning: 'thịt', example: "He doesn't eat much meat.", topicId: 'TV-04' },
  { id: 'TV04-06', word: 'fish', partOfSpeech: 'n.', phonetic: '/fɪʃ/', meaning: 'cá', example: 'My mother cooks fish for dinner.', topicId: 'TV-04' },
  { id: 'TV04-07', word: 'egg', partOfSpeech: 'n.', phonetic: '/eɡ/', meaning: 'trứng', example: 'I had a boiled egg this morning.', topicId: 'TV-04' },
  { id: 'TV04-08', word: 'milk', partOfSpeech: 'n.', phonetic: '/mɪlk/', meaning: 'sữa', example: 'Children should drink milk every day.', topicId: 'TV-04' },
  { id: 'TV04-09', word: 'juice', partOfSpeech: 'n.', phonetic: '/dʒuːs/', meaning: 'nước ép', example: 'I like orange juice very much.', topicId: 'TV-04' },
  { id: 'TV04-10', word: 'noodles', partOfSpeech: 'n.', phonetic: '/ˈnuː.dəlz/', meaning: 'mì', example: 'We had noodles for lunch.', topicId: 'TV-04' },
  { id: 'TV04-11', word: 'snack', partOfSpeech: 'n.', phonetic: '/snæk/', meaning: 'đồ ăn vặt', example: 'She bought some snacks for the trip.', topicId: 'TV-04' },
  { id: 'TV04-12', word: 'sweet', partOfSpeech: 'adj.', phonetic: '/swiːt/', meaning: 'ngọt', example: 'This cake is too sweet for me.', topicId: 'TV-04' },
  { id: 'TV04-13', word: 'delicious', partOfSpeech: 'adj.', phonetic: '/dɪˈlɪʃ.əs/', meaning: 'ngon', example: 'The soup smells delicious.', topicId: 'TV-04' },
  { id: 'TV04-14', word: 'hungry', partOfSpeech: 'adj.', phonetic: '/ˈhʌŋ.ɡri/', meaning: 'đói', example: 'I am hungry after football practice.', topicId: 'TV-04' },
  { id: 'TV04-15', word: 'recipe', partOfSpeech: 'n.', phonetic: '/ˈres.ə.pi/', meaning: 'công thức nấu ăn', example: 'My mother has a recipe for this cake.', topicId: 'TV-04' },
  { id: 'TV04-16', word: 'flavor', partOfSpeech: 'n.', phonetic: '/ˈfleɪ.vɚ/', meaning: 'hương vị', example: 'I love the flavor of mango ice cream.', topicId: 'TV-04' },
  { id: 'TV04-17', word: 'fresh', partOfSpeech: 'adj.', phonetic: '/freʃ/', meaning: 'tươi', example: 'We only buy fresh vegetables.', topicId: 'TV-04' },
  { id: 'TV04-18', word: 'sour', partOfSpeech: 'adj.', phonetic: '/ˈsaʊ.ɚ/', meaning: 'chua', example: 'This lemon tastes very sour.', topicId: 'TV-04' },
  { id: 'TV04-19', word: 'thirsty', partOfSpeech: 'adj.', phonetic: '/ˈθɝː.sti/', meaning: 'khát', example: 'I feel thirsty after running.', topicId: 'TV-04' },
  { id: 'TV04-20', word: 'diet', partOfSpeech: 'n.', phonetic: '/ˈdaɪ.ət/', meaning: 'chế độ ăn', example: 'A healthy diet includes lots of vegetables.', topicId: 'TV-04' },

  // TV-05: Động vật & thiên nhiên
  { id: 'TV05-01', word: 'dog', partOfSpeech: 'n.', phonetic: '/dɔːɡ/', meaning: 'chó', example: 'My dog likes playing in the yard.', topicId: 'TV-05' },
  { id: 'TV05-02', word: 'cat', partOfSpeech: 'n.', phonetic: '/kæt/', meaning: 'mèo', example: 'The cat is sleeping on the chair.', topicId: 'TV-05' },
  { id: 'TV05-03', word: 'bird', partOfSpeech: 'n.', phonetic: '/bɝːd/', meaning: 'chim', example: 'Birds sing early in the morning.', topicId: 'TV-05' },
  { id: 'TV05-04', word: 'elephant', partOfSpeech: 'n.', phonetic: '/ˈel.ə.fənt/', meaning: 'voi', example: 'An elephant is a very big animal.', topicId: 'TV-05' },
  { id: 'TV05-05', word: 'tiger', partOfSpeech: 'n.', phonetic: '/ˈtaɪ.ɡɚ/', meaning: 'hổ', example: 'The tiger is the king of the forest.', topicId: 'TV-05' },
  { id: 'TV05-06', word: 'monkey', partOfSpeech: 'n.', phonetic: '/ˈmʌŋ.ki/', meaning: 'khỉ', example: 'Monkeys can climb trees quickly.', topicId: 'TV-05' },
  { id: 'TV05-07', word: 'forest', partOfSpeech: 'n.', phonetic: '/ˈfɔːr.ɪst/', meaning: 'rừng', example: 'Many animals live in the forest.', topicId: 'TV-05' },
  { id: 'TV05-08', word: 'mountain', partOfSpeech: 'n.', phonetic: '/ˈmaʊn.tən/', meaning: 'núi', example: 'We climbed a high mountain last summer.', topicId: 'TV-05' },
  { id: 'TV05-09', word: 'river', partOfSpeech: 'n.', phonetic: '/ˈrɪv.ɚ/', meaning: 'dòng sông', example: 'The river flows through the village.', topicId: 'TV-05' },
  { id: 'TV05-10', word: 'tree', partOfSpeech: 'n.', phonetic: '/triː/', meaning: 'cây', example: 'We planted a tree in the garden.', topicId: 'TV-05' },
  { id: 'TV05-11', word: 'flower', partOfSpeech: 'n.', phonetic: '/ˈflaʊ.ɚ/', meaning: 'hoa', example: 'These flowers smell very nice.', topicId: 'TV-05' },
  { id: 'TV05-12', word: 'sky', partOfSpeech: 'n.', phonetic: '/skaɪ/', meaning: 'bầu trời', example: 'The sky is blue and clear today.', topicId: 'TV-05' },
  { id: 'TV05-13', word: 'wild', partOfSpeech: 'adj.', phonetic: '/waɪld/', meaning: 'hoang dã', example: 'Wild animals live in the jungle.', topicId: 'TV-05' },
  { id: 'TV05-14', word: 'protect', partOfSpeech: 'v.', phonetic: '/prəˈtekt/', meaning: 'bảo vệ', example: 'We should protect wild animals.', topicId: 'TV-05' },
  { id: 'TV05-15', word: 'habitat', partOfSpeech: 'n.', phonetic: '/ˈhæb.ə.tæt/', meaning: 'môi trường sống', example: 'The forest is the tiger\'s natural habitat.', topicId: 'TV-05' },
  { id: 'TV05-16', word: 'endangered', partOfSpeech: 'adj.', phonetic: '/ɪnˈdeɪn.dʒɚd/', meaning: 'có nguy cơ tuyệt chủng', example: 'Elephants are an endangered species.', topicId: 'TV-05' },
  { id: 'TV05-17', word: 'species', partOfSpeech: 'n.', phonetic: '/ˈspiː.ʃiːz/', meaning: 'loài', example: 'This forest has many rare species of birds.', topicId: 'TV-05' },
  { id: 'TV05-18', word: 'insect', partOfSpeech: 'n.', phonetic: '/ˈɪn.sekt/', meaning: 'côn trùng', example: 'Bees and ants are small insects.', topicId: 'TV-05' },
  { id: 'TV05-19', word: 'feather', partOfSpeech: 'n.', phonetic: '/ˈfeð.ɚ/', meaning: 'lông vũ', example: 'The peacock has beautiful feathers.', topicId: 'TV-05' },
  { id: 'TV05-20', word: 'paw', partOfSpeech: 'n.', phonetic: '/pɔː/', meaning: 'bàn chân (thú)', example: 'The dog hurt its paw.', topicId: 'TV-05' },

  // TV-09: Thành phố, phương hướng & phương tiện giao thông
  { id: 'TV09-01', word: 'city', partOfSpeech: 'n.', phonetic: '/ˈsɪt.i/', meaning: 'thành phố', example: 'Ha Noi is a big city.', topicId: 'TV-09' },
  { id: 'TV09-02', word: 'street', partOfSpeech: 'n.', phonetic: '/striːt/', meaning: 'con phố', example: 'There are many shops on this street.', topicId: 'TV-09' },
  { id: 'TV09-03', word: 'bus', partOfSpeech: 'n.', phonetic: '/bʌs/', meaning: 'xe buýt', example: 'I go to school by bus.', topicId: 'TV-09' },
  { id: 'TV09-04', word: 'bicycle', partOfSpeech: 'n.', phonetic: '/ˈbaɪ.sɪ.kəl/', meaning: 'xe đạp', example: 'She rides her bicycle to school.', topicId: 'TV-09' },
  { id: 'TV09-05', word: 'car', partOfSpeech: 'n.', phonetic: '/kɑːr/', meaning: 'ô tô', example: 'My father drives a car to work.', topicId: 'TV-09' },
  { id: 'TV09-06', word: 'train', partOfSpeech: 'n.', phonetic: '/treɪn/', meaning: 'tàu hỏa', example: 'We traveled by train to Hue.', topicId: 'TV-09' },
  { id: 'TV09-07', word: 'airport', partOfSpeech: 'n.', phonetic: '/ˈer.pɔːrt/', meaning: 'sân bay', example: 'The airport is far from the city center.', topicId: 'TV-09' },
  { id: 'TV09-08', word: 'traffic light', partOfSpeech: 'n. phr.', phonetic: '/ˈtræf.ɪk laɪt/', meaning: 'đèn giao thông', example: 'Stop when the traffic light is red.', topicId: 'TV-09' },
  { id: 'TV09-09', word: 'left', partOfSpeech: 'n./adv.', phonetic: '/left/', meaning: 'bên trái', example: 'Turn left at the corner.', topicId: 'TV-09' },
  { id: 'TV09-10', word: 'right', partOfSpeech: 'n./adv.', phonetic: '/raɪt/', meaning: 'bên phải', example: 'The post office is on your right.', topicId: 'TV-09' },
  { id: 'TV09-11', word: 'straight', partOfSpeech: 'adv.', phonetic: '/streɪt/', meaning: 'thẳng', example: 'Go straight and you will see the school.', topicId: 'TV-09' },
  { id: 'TV09-12', word: 'map', partOfSpeech: 'n.', phonetic: '/mæp/', meaning: 'bản đồ', example: 'Look at the map to find the way.', topicId: 'TV-09' },
  { id: 'TV09-13', word: 'crowded', partOfSpeech: 'adj.', phonetic: '/ˈkraʊ.dɪd/', meaning: 'đông đúc', example: 'The street is crowded in the morning.', topicId: 'TV-09' },
  { id: 'TV09-14', word: 'direction', partOfSpeech: 'n.', phonetic: '/dəˈrek.ʃən/', meaning: 'phương hướng', example: 'Can you tell me the direction to the park?', topicId: 'TV-09' },
  { id: 'TV09-15', word: 'corner', partOfSpeech: 'n.', phonetic: '/ˈkɔːr.nɚ/', meaning: 'góc phố', example: 'The bookstore is at the corner.', topicId: 'TV-09' },
  { id: 'TV09-16', word: 'crossroads', partOfSpeech: 'n.', phonetic: '/ˈkrɔːs.roʊdz/', meaning: 'ngã tư', example: 'Turn right at the crossroads.', topicId: 'TV-09' },
  { id: 'TV09-17', word: 'distance', partOfSpeech: 'n.', phonetic: '/ˈdɪs.təns/', meaning: 'khoảng cách', example: 'The distance from home to school is 2 km.', topicId: 'TV-09' },
  { id: 'TV09-18', word: 'nearby', partOfSpeech: 'adj./adv.', phonetic: '/ˈnɪr.baɪ/', meaning: 'gần đó', example: 'There is a supermarket nearby.', topicId: 'TV-09' },
  { id: 'TV09-19', word: 'journey', partOfSpeech: 'n.', phonetic: '/ˈdʒɝː.ni/', meaning: 'chuyến đi', example: 'Our journey to Sa Pa took six hours.', topicId: 'TV-09' },
  { id: 'TV09-20', word: 'signpost', partOfSpeech: 'n.', phonetic: '/ˈsaɪn.poʊst/', meaning: 'biển chỉ đường', example: 'Follow the signpost to the museum.', topicId: 'TV-09' },

  // TV-03: Nhà cửa & đồ vật trong nhà
  { id: 'TV03-01', word: 'house', partOfSpeech: 'n.', phonetic: '/haʊs/', meaning: 'ngôi nhà', example: 'We live in a small house.', topicId: 'TV-03' },
  { id: 'TV03-02', word: 'room', partOfSpeech: 'n.', phonetic: '/ruːm/', meaning: 'phòng', example: 'My room is very tidy.', topicId: 'TV-03' },
  { id: 'TV03-03', word: 'kitchen', partOfSpeech: 'n.', phonetic: '/ˈkɪtʃ.ən/', meaning: 'nhà bếp', example: 'My mother is cooking in the kitchen.', topicId: 'TV-03' },
  { id: 'TV03-04', word: 'bedroom', partOfSpeech: 'n.', phonetic: '/ˈbed.ruːm/', meaning: 'phòng ngủ', example: 'I sleep in my bedroom every night.', topicId: 'TV-03' },
  { id: 'TV03-05', word: 'bathroom', partOfSpeech: 'n.', phonetic: '/ˈbæθ.ruːm/', meaning: 'phòng tắm', example: 'The bathroom is next to my bedroom.', topicId: 'TV-03' },
  { id: 'TV03-06', word: 'table', partOfSpeech: 'n.', phonetic: '/ˈteɪ.bəl/', meaning: 'cái bàn', example: 'We eat dinner at the table.', topicId: 'TV-03' },
  { id: 'TV03-07', word: 'chair', partOfSpeech: 'n.', phonetic: '/tʃer/', meaning: 'cái ghế', example: 'Please sit on this chair.', topicId: 'TV-03' },
  { id: 'TV03-08', word: 'bed', partOfSpeech: 'n.', phonetic: '/bed/', meaning: 'cái giường', example: 'My bed is very comfortable.', topicId: 'TV-03' },
  { id: 'TV03-09', word: 'window', partOfSpeech: 'n.', phonetic: '/ˈwɪn.doʊ/', meaning: 'cửa sổ', example: 'Open the window, please.', topicId: 'TV-03' },
  { id: 'TV03-10', word: 'door', partOfSpeech: 'n.', phonetic: '/dɔːr/', meaning: 'cửa ra vào', example: 'Please close the door.', topicId: 'TV-03' },
  { id: 'TV03-11', word: 'lamp', partOfSpeech: 'n.', phonetic: '/læmp/', meaning: 'đèn', example: "Turn on the lamp; it's dark.", topicId: 'TV-03' },
  { id: 'TV03-12', word: 'mirror', partOfSpeech: 'n.', phonetic: '/ˈmɪr.ɚ/', meaning: 'gương', example: 'She looks in the mirror every morning.', topicId: 'TV-03' },
  { id: 'TV03-13', word: 'wardrobe', partOfSpeech: 'n.', phonetic: '/ˈwɔːr.droʊb/', meaning: 'tủ quần áo', example: 'I keep my clothes in the wardrobe.', topicId: 'TV-03' },
  { id: 'TV03-14', word: 'garden', partOfSpeech: 'n.', phonetic: '/ˈɡɑːr.dən/', meaning: 'khu vườn', example: 'My grandmother grows flowers in the garden.', topicId: 'TV-03' },
  { id: 'TV03-15', word: 'living room', partOfSpeech: 'n. phr.', phonetic: '/ˈlɪv.ɪŋ ruːm/', meaning: 'phòng khách', example: 'We watch TV in the living room.', topicId: 'TV-03' },
  { id: 'TV03-16', word: 'shelf', partOfSpeech: 'n.', phonetic: '/ʃelf/', meaning: 'kệ sách', example: 'The books are on the top shelf.', topicId: 'TV-03' },
  { id: 'TV03-17', word: 'furniture', partOfSpeech: 'n.', phonetic: '/ˈfɝː.nɪ.tʃɚ/', meaning: 'đồ nội thất', example: 'This shop sells nice furniture.', topicId: 'TV-03' },
  { id: 'TV03-18', word: 'tidy', partOfSpeech: 'adj.', phonetic: '/ˈtaɪ.di/', meaning: 'gọn gàng', example: 'Please keep your room tidy.', topicId: 'TV-03' },
  { id: 'TV03-19', word: 'balcony', partOfSpeech: 'n.', phonetic: '/ˈbæl.kə.ni/', meaning: 'ban công', example: 'We grow flowers on the balcony.', topicId: 'TV-03' },
  { id: 'TV03-20', word: 'roof', partOfSpeech: 'n.', phonetic: '/ruːf/', meaning: 'mái nhà', example: 'There is a bird on the roof.', topicId: 'TV-03' },

  // TV-06: Thời tiết & các mùa
  { id: 'TV06-01', word: 'sunny', partOfSpeech: 'adj.', phonetic: '/ˈsʌn.i/', meaning: 'nắng', example: 'It is sunny today.', topicId: 'TV-06' },
  { id: 'TV06-02', word: 'rainy', partOfSpeech: 'adj.', phonetic: '/ˈreɪ.ni/', meaning: 'mưa', example: "I don't like rainy days.", topicId: 'TV-06' },
  { id: 'TV06-03', word: 'cloudy', partOfSpeech: 'adj.', phonetic: '/ˈklaʊ.di/', meaning: 'nhiều mây', example: 'The sky is cloudy this afternoon.', topicId: 'TV-06' },
  { id: 'TV06-04', word: 'windy', partOfSpeech: 'adj.', phonetic: '/ˈwɪn.di/', meaning: 'có gió', example: "It's windy near the sea.", topicId: 'TV-06' },
  { id: 'TV06-05', word: 'hot', partOfSpeech: 'adj.', phonetic: '/hɑːt/', meaning: 'nóng', example: 'Summer in Ha Noi is very hot.', topicId: 'TV-06' },
  { id: 'TV06-06', word: 'cold', partOfSpeech: 'adj.', phonetic: '/koʊld/', meaning: 'lạnh', example: "It's cold in winter.", topicId: 'TV-06' },
  { id: 'TV06-07', word: 'warm', partOfSpeech: 'adj.', phonetic: '/wɔːrm/', meaning: 'ấm', example: 'I like warm weather in spring.', topicId: 'TV-06' },
  { id: 'TV06-08', word: 'cool', partOfSpeech: 'adj.', phonetic: '/kuːl/', meaning: 'mát mẻ', example: 'The weather is cool in autumn.', topicId: 'TV-06' },
  { id: 'TV06-09', word: 'storm', partOfSpeech: 'n.', phonetic: '/stɔːrm/', meaning: 'cơn bão', example: 'A storm is coming this weekend.', topicId: 'TV-06' },
  { id: 'TV06-10', word: 'spring', partOfSpeech: 'n.', phonetic: '/sprɪŋ/', meaning: 'mùa xuân', example: 'Flowers bloom in spring.', topicId: 'TV-06' },
  { id: 'TV06-11', word: 'summer', partOfSpeech: 'n.', phonetic: '/ˈsʌm.ɚ/', meaning: 'mùa hè', example: 'We go swimming in summer.', topicId: 'TV-06' },
  { id: 'TV06-12', word: 'autumn', partOfSpeech: 'n.', phonetic: '/ˈɔː.təm/', meaning: 'mùa thu', example: 'The leaves turn yellow in autumn.', topicId: 'TV-06' },
  { id: 'TV06-13', word: 'winter', partOfSpeech: 'n.', phonetic: '/ˈwɪn.tɚ/', meaning: 'mùa đông', example: 'It sometimes snows in winter in the mountains.', topicId: 'TV-06' },
  { id: 'TV06-14', word: 'temperature', partOfSpeech: 'n.', phonetic: '/ˈtem.pɚ.ə.tʃɚ/', meaning: 'nhiệt độ', example: 'The temperature today is thirty degrees.', topicId: 'TV-06' },
  { id: 'TV06-15', word: 'weather forecast', partOfSpeech: 'n. phr.', phonetic: '/ˈweð.ɚ ˌfɔːr.kæst/', meaning: 'dự báo thời tiết', example: 'The weather forecast says it will rain tomorrow.', topicId: 'TV-06' },
  { id: 'TV06-16', word: 'humid', partOfSpeech: 'adj.', phonetic: '/ˈhjuː.mɪd/', meaning: 'ẩm ướt', example: 'It is hot and humid in summer.', topicId: 'TV-06' },
  { id: 'TV06-17', word: 'foggy', partOfSpeech: 'adj.', phonetic: '/ˈfɑː.ɡi/', meaning: 'có sương mù', example: 'It was too foggy to see the mountain.', topicId: 'TV-06' },
  { id: 'TV06-18', word: 'freezing', partOfSpeech: 'adj.', phonetic: '/ˈfriː.zɪŋ/', meaning: 'lạnh cóng', example: 'It is freezing outside; wear a coat.', topicId: 'TV-06' },
  { id: 'TV06-19', word: 'thunder', partOfSpeech: 'n.', phonetic: '/ˈθʌn.dɚ/', meaning: 'sấm', example: 'We heard thunder during the storm.', topicId: 'TV-06' },
  { id: 'TV06-20', word: 'degree', partOfSpeech: 'n.', phonetic: '/dɪˈɡriː/', meaning: 'độ (nhiệt độ)', example: 'It is thirty-five degrees today.', topicId: 'TV-06' },

  // TV-08: Nghề nghiệp
  { id: 'TV08-01', word: 'doctor', partOfSpeech: 'n.', phonetic: '/ˈdɑːk.tɚ/', meaning: 'bác sĩ', example: 'The doctor works at the hospital.', topicId: 'TV-08' },
  { id: 'TV08-02', word: 'teacher', partOfSpeech: 'n.', phonetic: '/ˈtiː.tʃɚ/', meaning: 'giáo viên', example: 'My teacher explains lessons clearly.', topicId: 'TV-08' },
  { id: 'TV08-03', word: 'farmer', partOfSpeech: 'n.', phonetic: '/ˈfɑːr.mɚ/', meaning: 'nông dân', example: 'The farmer grows rice in the field.', topicId: 'TV-08' },
  { id: 'TV08-04', word: 'engineer', partOfSpeech: 'n.', phonetic: '/ˌen.dʒəˈnɪr/', meaning: 'kỹ sư', example: 'My father is an engineer.', topicId: 'TV-08' },
  { id: 'TV08-05', word: 'nurse', partOfSpeech: 'n.', phonetic: '/nɝːs/', meaning: 'y tá', example: 'The nurse takes care of patients.', topicId: 'TV-08' },
  { id: 'TV08-06', word: 'pilot', partOfSpeech: 'n.', phonetic: '/ˈpaɪ.lət/', meaning: 'phi công', example: 'A pilot flies an airplane.', topicId: 'TV-08' },
  { id: 'TV08-07', word: 'driver', partOfSpeech: 'n.', phonetic: '/ˈdraɪ.vɚ/', meaning: 'tài xế', example: 'The bus driver is very careful.', topicId: 'TV-08' },
  { id: 'TV08-08', word: 'singer', partOfSpeech: 'n.', phonetic: '/ˈsɪŋ.ɚ/', meaning: 'ca sĩ', example: 'My sister wants to be a singer.', topicId: 'TV-08' },
  { id: 'TV08-09', word: 'writer', partOfSpeech: 'n.', phonetic: '/ˈraɪ.tɚ/', meaning: 'nhà văn', example: 'The writer wrote an interesting book.', topicId: 'TV-08' },
  { id: 'TV08-10', word: 'police officer', partOfSpeech: 'n. phr.', phonetic: '/pəˈliːs ˌɔː.fə.sɚ/', meaning: 'cảnh sát', example: 'The police officer helps keep the street safe.', topicId: 'TV-08' },
  { id: 'TV08-11', word: 'firefighter', partOfSpeech: 'n.', phonetic: '/ˈfaɪr.faɪ.tɚ/', meaning: 'lính cứu hỏa', example: 'Firefighters put out the fire quickly.', topicId: 'TV-08' },
  { id: 'TV08-12', word: 'chef', partOfSpeech: 'n.', phonetic: '/ʃef/', meaning: 'đầu bếp', example: 'The chef cooks delicious food.', topicId: 'TV-08' },
  { id: 'TV08-13', word: 'dentist', partOfSpeech: 'n.', phonetic: '/ˈden.tɪst/', meaning: 'nha sĩ', example: 'I visited the dentist yesterday.', topicId: 'TV-08' },
  { id: 'TV08-14', word: 'scientist', partOfSpeech: 'n.', phonetic: '/ˈsaɪ.ən.tɪst/', meaning: 'nhà khoa học', example: 'The scientist works in a laboratory.', topicId: 'TV-08' },
  { id: 'TV08-15', word: 'career', partOfSpeech: 'n.', phonetic: '/kəˈrɪr/', meaning: 'sự nghiệp', example: 'She dreams of a career in medicine.', topicId: 'TV-08' },
  { id: 'TV08-16', word: 'salary', partOfSpeech: 'n.', phonetic: '/ˈsæl.ə.ri/', meaning: 'lương', example: 'Doctors usually earn a good salary.', topicId: 'TV-08' },
  { id: 'TV08-17', word: 'hardworking', partOfSpeech: 'adj.', phonetic: '/ˌhɑːrdˈwɝː.kɪŋ/', meaning: 'chăm chỉ', example: 'My father is a hardworking engineer.', topicId: 'TV-08' },
  { id: 'TV08-18', word: 'journalist', partOfSpeech: 'n.', phonetic: '/ˈdʒɝː.nə.lɪst/', meaning: 'nhà báo', example: 'The journalist wrote about the festival.', topicId: 'TV-08' },
  { id: 'TV08-19', word: 'photographer', partOfSpeech: 'n.', phonetic: '/fəˈtɑː.ɡrə.fɚ/', meaning: 'nhiếp ảnh gia', example: 'The photographer took beautiful pictures.', topicId: 'TV-08' },
  { id: 'TV08-20', word: 'workplace', partOfSpeech: 'n.', phonetic: '/ˈwɝːk.pleɪs/', meaning: 'nơi làm việc', example: 'Her workplace is near the city center.', topicId: 'TV-08' },

  // TV-10: Sức khỏe & cơ thể người
  { id: 'TV10-01', word: 'head', partOfSpeech: 'n.', phonetic: '/hed/', meaning: 'đầu', example: 'My head hurts a little.', topicId: 'TV-10' },
  { id: 'TV10-02', word: 'eye', partOfSpeech: 'n.', phonetic: '/aɪ/', meaning: 'mắt', example: 'She has beautiful eyes.', topicId: 'TV-10' },
  { id: 'TV10-03', word: 'ear', partOfSpeech: 'n.', phonetic: '/ɪr/', meaning: 'tai', example: 'My ear hurts when I have a cold.', topicId: 'TV-10' },
  { id: 'TV10-04', word: 'hand', partOfSpeech: 'n.', phonetic: '/hænd/', meaning: 'bàn tay', example: 'Wash your hands before eating.', topicId: 'TV-10' },
  { id: 'TV10-05', word: 'leg', partOfSpeech: 'n.', phonetic: '/leɡ/', meaning: 'chân', example: 'He hurt his leg while playing football.', topicId: 'TV-10' },
  { id: 'TV10-06', word: 'stomach', partOfSpeech: 'n.', phonetic: '/ˈstʌm.ək/', meaning: 'bụng', example: 'I have a stomachache.', topicId: 'TV-10' },
  { id: 'TV10-07', word: 'healthy', partOfSpeech: 'adj.', phonetic: '/ˈhel.θi/', meaning: 'khỏe mạnh', example: 'Eating vegetables makes you healthy.', topicId: 'TV-10' },
  { id: 'TV10-08', word: 'sick', partOfSpeech: 'adj.', phonetic: '/sɪk/', meaning: 'ốm', example: 'She is sick today and stays at home.', topicId: 'TV-10' },
  { id: 'TV10-09', word: 'fever', partOfSpeech: 'n.', phonetic: '/ˈfiː.vɚ/', meaning: 'sốt', example: 'He has a high fever.', topicId: 'TV-10' },
  { id: 'TV10-10', word: 'cough', partOfSpeech: 'n./v.', phonetic: '/kɔːf/', meaning: 'ho', example: 'I have a bad cough.', topicId: 'TV-10' },
  { id: 'TV10-11', word: 'medicine', partOfSpeech: 'n.', phonetic: '/ˈmed.ə.sən/', meaning: 'thuốc', example: 'Take this medicine after meals.', topicId: 'TV-10' },
  { id: 'TV10-12', word: 'exercise', partOfSpeech: 'v./n.', phonetic: '/ˈek.sɚ.saɪz/', meaning: 'tập thể dục', example: 'Exercise every day to stay healthy.', topicId: 'TV-10' },
  { id: 'TV10-13', word: 'rest', partOfSpeech: 'n./v.', phonetic: '/rest/', meaning: 'nghỉ ngơi', example: 'You should rest when you are tired.', topicId: 'TV-10' },
  { id: 'TV10-14', word: 'hospital', partOfSpeech: 'n.', phonetic: '/ˈhɑː.spɪ.təl/', meaning: 'bệnh viện', example: 'My mother works at a hospital.', topicId: 'TV-10' },
  { id: 'TV10-15', word: 'injury', partOfSpeech: 'n.', phonetic: '/ˈɪn.dʒə.ri/', meaning: 'chấn thương', example: 'He got a minor injury during the game.', topicId: 'TV-10' },
  { id: 'TV10-16', word: 'toothache', partOfSpeech: 'n.', phonetic: '/ˈtuːθ.eɪk/', meaning: 'đau răng', example: 'I have a toothache, so I need to see a dentist.', topicId: 'TV-10' },
  { id: 'TV10-17', word: 'dizzy', partOfSpeech: 'adj.', phonetic: '/ˈdɪz.i/', meaning: 'chóng mặt', example: 'I feel dizzy after the long ride.', topicId: 'TV-10' },
  { id: 'TV10-18', word: 'bandage', partOfSpeech: 'n.', phonetic: '/ˈbæn.dɪdʒ/', meaning: 'băng gạc', example: 'The nurse put a bandage on his hand.', topicId: 'TV-10' },
  { id: 'TV10-19', word: 'patient', partOfSpeech: 'n.', phonetic: '/ˈpeɪ.ʃənt/', meaning: 'bệnh nhân', example: 'The doctor is examining a patient.', topicId: 'TV-10' },
  { id: 'TV10-20', word: 'recover', partOfSpeech: 'v.', phonetic: '/rɪˈkʌv.ɚ/', meaning: 'hồi phục', example: 'She recovered quickly after the flu.', topicId: 'TV-10' },

  // TV-11: Ngày lễ, văn hóa Việt Nam & thế giới
  { id: 'TV11-01', word: 'Tet holiday', partOfSpeech: 'n. phr.', phonetic: '/tet ˈhɑː.lə.deɪ/', meaning: 'Tết Nguyên Đán', example: 'Tet holiday is the most important festival in Vietnam.', topicId: 'TV-11' },
  { id: 'TV11-02', word: 'Christmas', partOfSpeech: 'n.', phonetic: '/ˈkrɪs.məs/', meaning: 'Giáng sinh', example: 'Many families decorate a tree at Christmas.', topicId: 'TV-11' },
  { id: 'TV11-03', word: 'festival', partOfSpeech: 'n.', phonetic: '/ˈfes.tə.vəl/', meaning: 'lễ hội', example: 'The Mid-Autumn Festival is popular with children.', topicId: 'TV-11' },
  { id: 'TV11-04', word: 'lantern', partOfSpeech: 'n.', phonetic: '/ˈlæn.tɚn/', meaning: 'đèn lồng', example: 'Children carry colorful lanterns at the Mid-Autumn Festival.', topicId: 'TV-11' },
  { id: 'TV11-05', word: 'fireworks', partOfSpeech: 'n.', phonetic: '/ˈfaɪr.wɝːks/', meaning: 'pháo hoa', example: "We watched fireworks on New Year's Eve.", topicId: 'TV-11' },
  { id: 'TV11-06', word: 'tradition', partOfSpeech: 'n.', phonetic: '/trəˈdɪʃ.ən/', meaning: 'truyền thống', example: 'Giving lucky money is a Tet tradition.', topicId: 'TV-11' },
  { id: 'TV11-07', word: 'celebrate', partOfSpeech: 'v.', phonetic: '/ˈsel.ə.breɪt/', meaning: 'kỷ niệm, ăn mừng', example: "We celebrate Teachers' Day every November.", topicId: 'TV-11' },
  { id: 'TV11-08', word: 'custom', partOfSpeech: 'n.', phonetic: '/ˈkʌs.təm/', meaning: 'phong tục', example: 'Vietnam has many interesting customs.', topicId: 'TV-11' },
  { id: 'TV11-09', word: 'gift', partOfSpeech: 'n.', phonetic: '/ɡɪft/', meaning: 'món quà', example: 'I gave my mother a gift on her birthday.', topicId: 'TV-11' },
  { id: 'TV11-10', word: 'costume', partOfSpeech: 'n.', phonetic: '/ˈkɑː.stuːm/', meaning: 'trang phục', example: 'She wore a traditional costume at the festival.', topicId: 'TV-11' },
  { id: 'TV11-11', word: 'parade', partOfSpeech: 'n.', phonetic: '/pəˈreɪd/', meaning: 'cuộc diễu hành', example: 'There was a parade in the city center.', topicId: 'TV-11' },
  { id: 'TV11-12', word: 'New Year', partOfSpeech: 'n. phr.', phonetic: '/ˌnuː ˈjɪr/', meaning: 'năm mới', example: 'Happy New Year!', topicId: 'TV-11' },
  { id: 'TV11-13', word: 'ancestor', partOfSpeech: 'n.', phonetic: '/ˈæn.ses.tɚ/', meaning: 'tổ tiên', example: "We visit our ancestors' graves before Tet.", topicId: 'TV-11' },
  { id: 'TV11-14', word: 'reunion', partOfSpeech: 'n.', phonetic: '/riˈjuːn.jən/', meaning: 'đoàn tụ', example: 'Tet is a time for family reunion.', topicId: 'TV-11' },
  { id: 'TV11-15', word: 'lucky money', partOfSpeech: 'n. phr.', phonetic: '/ˈlʌk.i ˈmʌn.i/', meaning: 'lì xì', example: 'Children receive lucky money during Tet.', topicId: 'TV-11' },
  { id: 'TV11-16', word: 'decorate', partOfSpeech: 'v.', phonetic: '/ˈdek.ə.reɪt/', meaning: 'trang trí', example: 'We decorate the house before Tet.', topicId: 'TV-11' },
  { id: 'TV11-17', word: 'worship', partOfSpeech: 'v.', phonetic: '/ˈwɝː.ʃɪp/', meaning: 'thờ cúng', example: 'People worship their ancestors on this day.', topicId: 'TV-11' },
  { id: 'TV11-18', word: 'mooncake', partOfSpeech: 'n.', phonetic: '/ˈmuːn.keɪk/', meaning: 'bánh trung thu', example: 'We eat mooncakes during the Mid-Autumn Festival.', topicId: 'TV-11' },
  { id: 'TV11-19', word: 'guest', partOfSpeech: 'n.', phonetic: '/ɡest/', meaning: 'khách', example: 'We invited many guests to the party.', topicId: 'TV-11' },
  { id: 'TV11-20', word: 'peaceful', partOfSpeech: 'adj.', phonetic: '/ˈpiːs.fəl/', meaning: 'yên bình', example: 'The village looks peaceful during Tet.', topicId: 'TV-11' },

  // TV-12: Công nghệ & truyền thông
  { id: 'TV12-01', word: 'computer', partOfSpeech: 'n.', phonetic: '/kəmˈpjuː.tɚ/', meaning: 'máy tính', example: 'I use a computer to do my homework.', topicId: 'TV-12' },
  { id: 'TV12-02', word: 'smartphone', partOfSpeech: 'n.', phonetic: '/ˈsmɑːrt.foʊn/', meaning: 'điện thoại thông minh', example: 'My mother has a new smartphone.', topicId: 'TV-12' },
  { id: 'TV12-03', word: 'internet', partOfSpeech: 'n.', phonetic: '/ˈɪn.tɚ.net/', meaning: 'mạng internet', example: 'We use the internet to find information.', topicId: 'TV-12' },
  { id: 'TV12-04', word: 'website', partOfSpeech: 'n.', phonetic: '/ˈweb.saɪt/', meaning: 'trang web', example: 'This website has many useful lessons.', topicId: 'TV-12' },
  { id: 'TV12-05', word: 'email', partOfSpeech: 'n.', phonetic: '/ˈiː.meɪl/', meaning: 'thư điện tử', example: 'Please send me an email.', topicId: 'TV-12' },
  { id: 'TV12-06', word: 'message', partOfSpeech: 'n.', phonetic: '/ˈmes.ɪdʒ/', meaning: 'tin nhắn', example: 'I sent her a message this morning.', topicId: 'TV-12' },
  { id: 'TV12-07', word: 'video call', partOfSpeech: 'n. phr.', phonetic: '/ˈvɪd.i.oʊ kɔːl/', meaning: 'cuộc gọi video', example: 'We had a video call with my grandparents.', topicId: 'TV-12' },
  { id: 'TV12-08', word: 'robot', partOfSpeech: 'n.', phonetic: '/ˈroʊ.bɑːt/', meaning: 'rô bốt', example: 'The robot can answer simple questions.', topicId: 'TV-12' },
  { id: 'TV12-09', word: 'camera', partOfSpeech: 'n.', phonetic: '/ˈkæm.rə/', meaning: 'máy ảnh', example: 'He took photos with his new camera.', topicId: 'TV-12' },
  { id: 'TV12-10', word: 'television', partOfSpeech: 'n.', phonetic: '/ˈtel.ə.vɪʒ.ən/', meaning: 'tivi', example: 'We watch the news on television.', topicId: 'TV-12' },
  { id: 'TV12-11', word: 'password', partOfSpeech: 'n.', phonetic: '/ˈpæs.wɝːd/', meaning: 'mật khẩu', example: "Don't share your password with strangers.", topicId: 'TV-12' },
  { id: 'TV12-12', word: 'download', partOfSpeech: 'v.', phonetic: '/ˈdaʊn.loʊd/', meaning: 'tải xuống', example: 'I downloaded a new game yesterday.', topicId: 'TV-12' },
  { id: 'TV12-13', word: 'screen', partOfSpeech: 'n.', phonetic: '/skriːn/', meaning: 'màn hình', example: "Don't sit too close to the screen.", topicId: 'TV-12' },
  { id: 'TV12-14', word: 'technology', partOfSpeech: 'n.', phonetic: '/tekˈnɑː.lə.dʒi/', meaning: 'công nghệ', example: 'Technology helps students learn more easily.', topicId: 'TV-12' },
  { id: 'TV12-15', word: 'device', partOfSpeech: 'n.', phonetic: '/dɪˈvaɪs/', meaning: 'thiết bị', example: 'This app works on many devices.', topicId: 'TV-12' },
  { id: 'TV12-16', word: 'upload', partOfSpeech: 'v.', phonetic: '/ˈʌp.loʊd/', meaning: 'tải lên', example: 'She uploaded her photos to the website.', topicId: 'TV-12' },
  { id: 'TV12-17', word: 'keyboard', partOfSpeech: 'n.', phonetic: '/ˈkiː.bɔːrd/', meaning: 'bàn phím', example: 'I type quickly on the keyboard.', topicId: 'TV-12' },
  { id: 'TV12-18', word: 'application', partOfSpeech: 'n.', phonetic: '/ˌæp.ləˈkeɪ.ʃən/', meaning: 'ứng dụng', example: 'This application helps me study English.', topicId: 'TV-12' },
  { id: 'TV12-19', word: 'connect', partOfSpeech: 'v.', phonetic: '/kəˈnekt/', meaning: 'kết nối', example: 'Please connect your laptop to the printer.', topicId: 'TV-12' },
  { id: 'TV12-20', word: 'social media', partOfSpeech: 'n. phr.', phonetic: '/ˈsoʊ.ʃəl ˈmiː.di.ə/', meaning: 'mạng xã hội', example: 'Many teenagers spend time on social media.', topicId: 'TV-12' },

  // TV-13: Môi trường & bảo vệ thiên nhiên
  { id: 'TV13-01', word: 'environment', partOfSpeech: 'n.', phonetic: '/ɪnˈvaɪ.rən.mənt/', meaning: 'môi trường', example: 'We should protect the environment.', topicId: 'TV-13' },
  { id: 'TV13-02', word: 'pollution', partOfSpeech: 'n.', phonetic: '/pəˈluː.ʃən/', meaning: 'ô nhiễm', example: 'Air pollution is a serious problem in big cities.', topicId: 'TV-13' },
  { id: 'TV13-03', word: 'rubbish', partOfSpeech: 'n.', phonetic: '/ˈrʌb.ɪʃ/', meaning: 'rác', example: 'Please put rubbish in the bin.', topicId: 'TV-13' },
  { id: 'TV13-04', word: 'recycle', partOfSpeech: 'v.', phonetic: '/riˈsaɪ.kəl/', meaning: 'tái chế', example: 'We should recycle paper and plastic bottles.', topicId: 'TV-13' },
  { id: 'TV13-05', word: 'plastic bag', partOfSpeech: 'n. phr.', phonetic: '/ˈplæs.tɪk bæɡ/', meaning: 'túi ni lông', example: 'Try not to use too many plastic bags.', topicId: 'TV-13' },
  { id: 'TV13-06', word: 'clean', partOfSpeech: 'adj.', phonetic: '/kliːn/', meaning: 'sạch sẽ', example: 'Keep the beach clean.', topicId: 'TV-13' },
  { id: 'TV13-07', word: 'dirty', partOfSpeech: 'adj.', phonetic: '/ˈdɝː.ti/', meaning: 'bẩn', example: 'The river looks dirty because of rubbish.', topicId: 'TV-13' },
  { id: 'TV13-08', word: 'plant a tree', partOfSpeech: 'v. phr.', phonetic: '/plænt ə triː/', meaning: 'trồng cây', example: 'We planted a tree at school last week.', topicId: 'TV-13' },
  { id: 'TV13-09', word: 'save water', partOfSpeech: 'v. phr.', phonetic: '/seɪv ˈwɔː.tɚ/', meaning: 'tiết kiệm nước', example: 'We should save water every day.', topicId: 'TV-13' },
  { id: 'TV13-10', word: 'save energy', partOfSpeech: 'v. phr.', phonetic: '/seɪv ˈen.ɚ.dʒi/', meaning: 'tiết kiệm năng lượng', example: 'Turn off the lights to save energy.', topicId: 'TV-13' },
  { id: 'TV13-11', word: 'climate', partOfSpeech: 'n.', phonetic: '/ˈklaɪ.mət/', meaning: 'khí hậu', example: 'Climate change affects the whole world.', topicId: 'TV-13' },
  { id: 'TV13-12', word: 'earth', partOfSpeech: 'n.', phonetic: '/ɝːθ/', meaning: 'trái đất', example: 'We only have one Earth.', topicId: 'TV-13' },
  { id: 'TV13-13', word: 'natural resources', partOfSpeech: 'n. phr.', phonetic: '/ˈnætʃ.rəl ˈriː.sɔːr.sɪz/', meaning: 'tài nguyên thiên nhiên', example: 'We must not waste natural resources.', topicId: 'TV-13' },
  { id: 'TV13-14', word: 'wildlife', partOfSpeech: 'n.', phonetic: '/ˈwaɪld.laɪf/', meaning: 'động vật hoang dã', example: 'The forest protects a lot of wildlife.', topicId: 'TV-13' },
  { id: 'TV13-15', word: 'global warming', partOfSpeech: 'n. phr.', phonetic: '/ˈɡloʊ.bəl ˈwɔːr.mɪŋ/', meaning: 'nóng lên toàn cầu', example: 'Global warming is a big problem today.', topicId: 'TV-13' },
  { id: 'TV13-16', word: 'reduce', partOfSpeech: 'v.', phonetic: '/rɪˈduːs/', meaning: 'giảm thiểu', example: 'We should reduce the use of plastic.', topicId: 'TV-13' },
  { id: 'TV13-17', word: 'reuse', partOfSpeech: 'v.', phonetic: '/riˈjuːz/', meaning: 'tái sử dụng', example: 'You can reuse this bottle many times.', topicId: 'TV-13' },
  { id: 'TV13-18', word: 'litter', partOfSpeech: 'n./v.', phonetic: '/ˈlɪt.ɚ/', meaning: 'rác vứt bừa bãi', example: "Don't litter in the park.", topicId: 'TV-13' },
  { id: 'TV13-19', word: 'solar energy', partOfSpeech: 'n. phr.', phonetic: '/ˈsoʊ.lɚ ˈen.ɚ.dʒi/', meaning: 'năng lượng mặt trời', example: 'Solar energy is clean and renewable.', topicId: 'TV-13' },
  { id: 'TV13-20', word: 'deforestation', partOfSpeech: 'n.', phonetic: '/diːˌfɔːr.əˈsteɪ.ʃən/', meaning: 'phá rừng', example: 'Deforestation harms wild animals.', topicId: 'TV-13' },

  // TV-14: Cụm động từ & thành ngữ thông dụng ở tiểu học
  { id: 'TV14-01', word: 'get up', partOfSpeech: 'phr.v.', phonetic: '/ɡet ʌp/', meaning: 'thức dậy', example: 'I get up at six every morning.', topicId: 'TV-14' },
  { id: 'TV14-02', word: 'turn on', partOfSpeech: 'phr.v.', phonetic: '/tɝːn ɑːn/', meaning: 'bật (thiết bị)', example: 'Please turn on the light.', topicId: 'TV-14' },
  { id: 'TV14-03', word: 'turn off', partOfSpeech: 'phr.v.', phonetic: '/tɝːn ɔːf/', meaning: 'tắt (thiết bị)', example: 'Turn off the TV before you sleep.', topicId: 'TV-14' },
  { id: 'TV14-04', word: 'look after', partOfSpeech: 'phr.v.', phonetic: '/lʊk ˈæf.tɚ/', meaning: 'chăm sóc', example: 'She looks after her little brother.', topicId: 'TV-14' },
  { id: 'TV14-05', word: 'look for', partOfSpeech: 'phr.v.', phonetic: '/lʊk fɔːr/', meaning: 'tìm kiếm', example: 'I am looking for my pencil case.', topicId: 'TV-14' },
  { id: 'TV14-06', word: 'put on', partOfSpeech: 'phr.v.', phonetic: '/pʊt ɑːn/', meaning: 'mặc vào', example: "Put on your coat; it's cold outside.", topicId: 'TV-14' },
  { id: 'TV14-07', word: 'take off', partOfSpeech: 'phr.v.', phonetic: '/teɪk ɔːf/', meaning: 'cởi ra', example: 'Take off your shoes before entering the house.', topicId: 'TV-14' },
  { id: 'TV14-08', word: 'come in', partOfSpeech: 'phr.v.', phonetic: '/kʌm ɪn/', meaning: 'đi vào', example: 'Please come in and sit down.', topicId: 'TV-14' },
  { id: 'TV14-09', word: 'go out', partOfSpeech: 'phr.v.', phonetic: '/ɡoʊ aʊt/', meaning: 'đi ra ngoài', example: 'We usually go out on Sundays.', topicId: 'TV-14' },
  { id: 'TV14-10', word: 'write down', partOfSpeech: 'phr.v.', phonetic: '/raɪt daʊn/', meaning: 'viết xuống', example: 'Write down the new words in your notebook.', topicId: 'TV-14' },
  { id: 'TV14-11', word: 'pick up', partOfSpeech: 'phr.v.', phonetic: '/pɪk ʌp/', meaning: 'nhặt lên, đón ai', example: 'My father picks me up from school.', topicId: 'TV-14' },
  { id: 'TV14-12', word: 'hand in', partOfSpeech: 'phr.v.', phonetic: '/hænd ɪn/', meaning: 'nộp (bài)', example: 'Please hand in your homework tomorrow.', topicId: 'TV-14' },
  { id: 'TV14-13', word: 'once in a while', partOfSpeech: 'idiom', phonetic: '/wʌns ɪn ə (h)waɪl/', meaning: 'thỉnh thoảng', example: 'We eat out once in a while.', topicId: 'TV-14' },
  { id: 'TV14-14', word: 'piece of cake', partOfSpeech: 'idiom', phonetic: '/piːs əv keɪk/', meaning: 'việc dễ như ăn kẹo', example: 'This test is a piece of cake for her.', topicId: 'TV-14' },
  { id: 'TV14-15', word: 'find out', partOfSpeech: 'phr.v.', phonetic: '/faɪnd aʊt/', meaning: 'tìm ra, khám phá', example: 'Let\'s find out the answer together.', topicId: 'TV-14' },
  { id: 'TV14-16', word: 'give up', partOfSpeech: 'phr.v.', phonetic: '/ɡɪv ʌp/', meaning: 'từ bỏ', example: "Don't give up; keep trying!", topicId: 'TV-14' },
  { id: 'TV14-17', word: 'grow up', partOfSpeech: 'phr.v.', phonetic: '/ɡroʊ ʌp/', meaning: 'lớn lên', example: 'What do you want to be when you grow up?', topicId: 'TV-14' },
  { id: 'TV14-18', word: 'run out of', partOfSpeech: 'phr.v.', phonetic: '/rʌn aʊt əv/', meaning: 'hết (cái gì)', example: 'We ran out of milk this morning.', topicId: 'TV-14' },
  { id: 'TV14-19', word: 'keep an eye on', partOfSpeech: 'idiom', phonetic: '/kiːp ən aɪ ɑːn/', meaning: 'trông chừng', example: 'Please keep an eye on my bag.', topicId: 'TV-14' },
  { id: 'TV14-20', word: 'as easy as pie', partOfSpeech: 'idiom', phonetic: '/æz ˈiː.zi æz paɪ/', meaning: 'dễ như trở bàn tay', example: 'Riding a bike is as easy as pie for him.', topicId: 'TV-14' },
]
