import type { VocabCard } from '../../types/domain'

// Flashcard từ vựng theo chủ đề TV-xx — Mục 4.2 URD.
// Giai đoạn 3: TV-07 (Thể thao & sở thích), xác thực mô hình flashcard +
// spaced repetition. Giai đoạn 6: mở rộng thêm 5 chủ đề tần suất cao trong
// đề thi thật (gia đình, trường học, thức ăn, động vật, giao thông).
export const vocabCards: VocabCard[] = [
  { id: 'TV07-01', word: 'football', meaning: 'bóng đá', example: 'He plays football every weekend.', topicId: 'TV-07' },
  { id: 'TV07-02', word: 'basketball', meaning: 'bóng rổ', example: 'She is good at basketball.', topicId: 'TV-07' },
  { id: 'TV07-03', word: 'swim', meaning: 'bơi', example: 'We swim in the lake in summer.', topicId: 'TV-07' },
  { id: 'TV07-04', word: 'team', meaning: 'đội, nhóm', example: 'Our team won the match.', topicId: 'TV-07' },
  { id: 'TV07-05', word: 'match', meaning: 'trận đấu', example: 'The football match starts at 3 pm.', topicId: 'TV-07' },
  { id: 'TV07-06', word: 'goal', meaning: 'bàn thắng', example: 'Minh scored the winning goal.', topicId: 'TV-07' },
  { id: 'TV07-07', word: 'player', meaning: 'cầu thủ, người chơi', example: 'He is the best player on the team.', topicId: 'TV-07' },
  { id: 'TV07-08', word: 'practice', meaning: 'luyện tập', example: 'I practice badminton every Tuesday.', topicId: 'TV-07' },
  { id: 'TV07-09', word: 'hobby', meaning: 'sở thích', example: 'Reading comic books is my hobby.', topicId: 'TV-07' },
  { id: 'TV07-10', word: 'race', meaning: 'cuộc đua', example: 'They ran a race around the park.', topicId: 'TV-07' },
  { id: 'TV07-11', word: 'champion', meaning: 'nhà vô địch', example: 'She became the champion of the chess club.', topicId: 'TV-07' },
  { id: 'TV07-12', word: 'exercise', meaning: 'sự luyện tập, bài tập thể dục', example: 'Exercise is good for your health.', topicId: 'TV-07' },
  { id: 'TV07-13', word: 'score', meaning: 'ghi điểm', example: 'He scored three goals in one match.', topicId: 'TV-07' },
  { id: 'TV07-14', word: 'coach', meaning: 'huấn luyện viên', example: 'Our coach teaches us new skills every day.', topicId: 'TV-07' },

  // TV-01: Gia đình & bản thân
  { id: 'TV01-01', word: 'father', meaning: 'bố', example: 'My father works in a hospital.', topicId: 'TV-01' },
  { id: 'TV01-02', word: 'mother', meaning: 'mẹ', example: 'My mother cooks dinner every evening.', topicId: 'TV-01' },
  { id: 'TV01-03', word: 'brother', meaning: 'anh/em trai', example: 'I have an older brother.', topicId: 'TV-01' },
  { id: 'TV01-04', word: 'sister', meaning: 'chị/em gái', example: 'My sister is younger than me.', topicId: 'TV-01' },
  { id: 'TV01-05', word: 'grandparents', meaning: 'ông bà', example: 'We visit our grandparents every weekend.', topicId: 'TV-01' },
  { id: 'TV01-06', word: 'cousin', meaning: 'anh/chị/em họ', example: 'My cousin lives in Da Nang.', topicId: 'TV-01' },
  { id: 'TV01-07', word: 'parents', meaning: 'cha mẹ', example: 'My parents love me very much.', topicId: 'TV-01' },
  { id: 'TV01-08', word: 'baby', meaning: 'em bé', example: 'The baby is sleeping in the room.', topicId: 'TV-01' },
  { id: 'TV01-09', word: 'family', meaning: 'gia đình', example: 'I love spending time with my family.', topicId: 'TV-01' },
  { id: 'TV01-10', word: 'name', meaning: 'tên', example: 'What is your name?', topicId: 'TV-01' },
  { id: 'TV01-11', word: 'age', meaning: 'tuổi', example: 'What is your age?', topicId: 'TV-01' },
  { id: 'TV01-12', word: 'birthday', meaning: 'sinh nhật', example: 'My birthday is in June.', topicId: 'TV-01' },
  { id: 'TV01-13', word: 'kind', meaning: 'tốt bụng', example: 'My grandmother is very kind.', topicId: 'TV-01' },
  { id: 'TV01-14', word: 'friendly', meaning: 'thân thiện', example: 'My new classmate is friendly.', topicId: 'TV-01' },

  // TV-02: Trường học & môn học
  { id: 'TV02-01', word: 'classroom', meaning: 'lớp học', example: 'Our classroom is on the second floor.', topicId: 'TV-02' },
  { id: 'TV02-02', word: 'teacher', meaning: 'giáo viên', example: 'Our teacher explains lessons clearly.', topicId: 'TV-02' },
  { id: 'TV02-03', word: 'student', meaning: 'học sinh', example: 'There are thirty students in my class.', topicId: 'TV-02' },
  { id: 'TV02-04', word: 'subject', meaning: 'môn học', example: 'Math is my favorite subject.', topicId: 'TV-02' },
  { id: 'TV02-05', word: 'homework', meaning: 'bài tập về nhà', example: 'I do my homework after dinner.', topicId: 'TV-02' },
  { id: 'TV02-06', word: 'timetable', meaning: 'thời khóa biểu', example: "Check the timetable for tomorrow's classes.", topicId: 'TV-02' },
  { id: 'TV02-07', word: 'exam', meaning: 'kỳ thi', example: 'The English exam is next Monday.', topicId: 'TV-02' },
  { id: 'TV02-08', word: 'library', meaning: 'thư viện', example: 'I borrow books from the library.', topicId: 'TV-02' },
  { id: 'TV02-09', word: 'playground', meaning: 'sân chơi', example: 'We play football in the playground.', topicId: 'TV-02' },
  { id: 'TV02-10', word: 'break time', meaning: 'giờ ra chơi', example: 'We eat snacks during break time.', topicId: 'TV-02' },
  { id: 'TV02-11', word: 'uniform', meaning: 'đồng phục', example: 'Students wear a uniform on Mondays.', topicId: 'TV-02' },
  { id: 'TV02-12', word: 'blackboard', meaning: 'bảng đen', example: 'The teacher writes on the blackboard.', topicId: 'TV-02' },
  { id: 'TV02-13', word: 'principal', meaning: 'hiệu trưởng', example: 'The principal gave a speech today.', topicId: 'TV-02' },
  { id: 'TV02-14', word: 'score', meaning: 'điểm số', example: 'She got a high score on the test.', topicId: 'TV-02' },

  // TV-04: Thức ăn & đồ uống
  { id: 'TV04-01', word: 'rice', meaning: 'cơm, gạo', example: 'We eat rice every day.', topicId: 'TV-04' },
  { id: 'TV04-02', word: 'bread', meaning: 'bánh mì', example: 'I have bread and milk for breakfast.', topicId: 'TV-04' },
  { id: 'TV04-03', word: 'vegetable', meaning: 'rau', example: 'Vegetables are good for your health.', topicId: 'TV-04' },
  { id: 'TV04-04', word: 'fruit', meaning: 'trái cây', example: 'I eat fruit after lunch.', topicId: 'TV-04' },
  { id: 'TV04-05', word: 'meat', meaning: 'thịt', example: "He doesn't eat much meat.", topicId: 'TV-04' },
  { id: 'TV04-06', word: 'fish', meaning: 'cá', example: 'My mother cooks fish for dinner.', topicId: 'TV-04' },
  { id: 'TV04-07', word: 'egg', meaning: 'trứng', example: 'I had a boiled egg this morning.', topicId: 'TV-04' },
  { id: 'TV04-08', word: 'milk', meaning: 'sữa', example: 'Children should drink milk every day.', topicId: 'TV-04' },
  { id: 'TV04-09', word: 'juice', meaning: 'nước ép', example: 'I like orange juice very much.', topicId: 'TV-04' },
  { id: 'TV04-10', word: 'noodles', meaning: 'mì', example: 'We had noodles for lunch.', topicId: 'TV-04' },
  { id: 'TV04-11', word: 'snack', meaning: 'đồ ăn vặt', example: 'She bought some snacks for the trip.', topicId: 'TV-04' },
  { id: 'TV04-12', word: 'sweet', meaning: 'ngọt', example: 'This cake is too sweet for me.', topicId: 'TV-04' },
  { id: 'TV04-13', word: 'delicious', meaning: 'ngon', example: 'The soup smells delicious.', topicId: 'TV-04' },
  { id: 'TV04-14', word: 'hungry', meaning: 'đói', example: 'I am hungry after football practice.', topicId: 'TV-04' },

  // TV-05: Động vật & thiên nhiên
  { id: 'TV05-01', word: 'dog', meaning: 'chó', example: 'My dog likes playing in the yard.', topicId: 'TV-05' },
  { id: 'TV05-02', word: 'cat', meaning: 'mèo', example: 'The cat is sleeping on the chair.', topicId: 'TV-05' },
  { id: 'TV05-03', word: 'bird', meaning: 'chim', example: 'Birds sing early in the morning.', topicId: 'TV-05' },
  { id: 'TV05-04', word: 'elephant', meaning: 'voi', example: 'An elephant is a very big animal.', topicId: 'TV-05' },
  { id: 'TV05-05', word: 'tiger', meaning: 'hổ', example: 'The tiger is the king of the forest.', topicId: 'TV-05' },
  { id: 'TV05-06', word: 'monkey', meaning: 'khỉ', example: 'Monkeys can climb trees quickly.', topicId: 'TV-05' },
  { id: 'TV05-07', word: 'forest', meaning: 'rừng', example: 'Many animals live in the forest.', topicId: 'TV-05' },
  { id: 'TV05-08', word: 'mountain', meaning: 'núi', example: 'We climbed a high mountain last summer.', topicId: 'TV-05' },
  { id: 'TV05-09', word: 'river', meaning: 'dòng sông', example: 'The river flows through the village.', topicId: 'TV-05' },
  { id: 'TV05-10', word: 'tree', meaning: 'cây', example: 'We planted a tree in the garden.', topicId: 'TV-05' },
  { id: 'TV05-11', word: 'flower', meaning: 'hoa', example: 'These flowers smell very nice.', topicId: 'TV-05' },
  { id: 'TV05-12', word: 'sky', meaning: 'bầu trời', example: 'The sky is blue and clear today.', topicId: 'TV-05' },
  { id: 'TV05-13', word: 'wild', meaning: 'hoang dã', example: 'Wild animals live in the jungle.', topicId: 'TV-05' },
  { id: 'TV05-14', word: 'protect', meaning: 'bảo vệ', example: 'We should protect wild animals.', topicId: 'TV-05' },

  // TV-09: Thành phố, phương hướng & phương tiện giao thông
  { id: 'TV09-01', word: 'city', meaning: 'thành phố', example: 'Ha Noi is a big city.', topicId: 'TV-09' },
  { id: 'TV09-02', word: 'street', meaning: 'con phố', example: 'There are many shops on this street.', topicId: 'TV-09' },
  { id: 'TV09-03', word: 'bus', meaning: 'xe buýt', example: 'I go to school by bus.', topicId: 'TV-09' },
  { id: 'TV09-04', word: 'bicycle', meaning: 'xe đạp', example: 'She rides her bicycle to school.', topicId: 'TV-09' },
  { id: 'TV09-05', word: 'car', meaning: 'ô tô', example: 'My father drives a car to work.', topicId: 'TV-09' },
  { id: 'TV09-06', word: 'train', meaning: 'tàu hỏa', example: 'We traveled by train to Hue.', topicId: 'TV-09' },
  { id: 'TV09-07', word: 'airport', meaning: 'sân bay', example: 'The airport is far from the city center.', topicId: 'TV-09' },
  { id: 'TV09-08', word: 'traffic light', meaning: 'đèn giao thông', example: 'Stop when the traffic light is red.', topicId: 'TV-09' },
  { id: 'TV09-09', word: 'left', meaning: 'bên trái', example: 'Turn left at the corner.', topicId: 'TV-09' },
  { id: 'TV09-10', word: 'right', meaning: 'bên phải', example: 'The post office is on your right.', topicId: 'TV-09' },
  { id: 'TV09-11', word: 'straight', meaning: 'thẳng', example: 'Go straight and you will see the school.', topicId: 'TV-09' },
  { id: 'TV09-12', word: 'map', meaning: 'bản đồ', example: 'Look at the map to find the way.', topicId: 'TV-09' },
  { id: 'TV09-13', word: 'crowded', meaning: 'đông đúc', example: 'The street is crowded in the morning.', topicId: 'TV-09' },
  { id: 'TV09-14', word: 'direction', meaning: 'phương hướng', example: 'Can you tell me the direction to the park?', topicId: 'TV-09' },

  // TV-03: Nhà cửa & đồ vật trong nhà
  { id: 'TV03-01', word: 'house', meaning: 'ngôi nhà', example: 'We live in a small house.', topicId: 'TV-03' },
  { id: 'TV03-02', word: 'room', meaning: 'phòng', example: 'My room is very tidy.', topicId: 'TV-03' },
  { id: 'TV03-03', word: 'kitchen', meaning: 'nhà bếp', example: 'My mother is cooking in the kitchen.', topicId: 'TV-03' },
  { id: 'TV03-04', word: 'bedroom', meaning: 'phòng ngủ', example: 'I sleep in my bedroom every night.', topicId: 'TV-03' },
  { id: 'TV03-05', word: 'bathroom', meaning: 'phòng tắm', example: 'The bathroom is next to my bedroom.', topicId: 'TV-03' },
  { id: 'TV03-06', word: 'table', meaning: 'cái bàn', example: 'We eat dinner at the table.', topicId: 'TV-03' },
  { id: 'TV03-07', word: 'chair', meaning: 'cái ghế', example: 'Please sit on this chair.', topicId: 'TV-03' },
  { id: 'TV03-08', word: 'bed', meaning: 'cái giường', example: 'My bed is very comfortable.', topicId: 'TV-03' },
  { id: 'TV03-09', word: 'window', meaning: 'cửa sổ', example: 'Open the window, please.', topicId: 'TV-03' },
  { id: 'TV03-10', word: 'door', meaning: 'cửa ra vào', example: 'Please close the door.', topicId: 'TV-03' },
  { id: 'TV03-11', word: 'lamp', meaning: 'đèn', example: "Turn on the lamp; it's dark.", topicId: 'TV-03' },
  { id: 'TV03-12', word: 'mirror', meaning: 'gương', example: 'She looks in the mirror every morning.', topicId: 'TV-03' },
  { id: 'TV03-13', word: 'wardrobe', meaning: 'tủ quần áo', example: 'I keep my clothes in the wardrobe.', topicId: 'TV-03' },
  { id: 'TV03-14', word: 'garden', meaning: 'khu vườn', example: 'My grandmother grows flowers in the garden.', topicId: 'TV-03' },

  // TV-06: Thời tiết & các mùa
  { id: 'TV06-01', word: 'sunny', meaning: 'nắng', example: 'It is sunny today.', topicId: 'TV-06' },
  { id: 'TV06-02', word: 'rainy', meaning: 'mưa', example: "I don't like rainy days.", topicId: 'TV-06' },
  { id: 'TV06-03', word: 'cloudy', meaning: 'nhiều mây', example: 'The sky is cloudy this afternoon.', topicId: 'TV-06' },
  { id: 'TV06-04', word: 'windy', meaning: 'có gió', example: "It's windy near the sea.", topicId: 'TV-06' },
  { id: 'TV06-05', word: 'hot', meaning: 'nóng', example: 'Summer in Ha Noi is very hot.', topicId: 'TV-06' },
  { id: 'TV06-06', word: 'cold', meaning: 'lạnh', example: "It's cold in winter.", topicId: 'TV-06' },
  { id: 'TV06-07', word: 'warm', meaning: 'ấm', example: 'I like warm weather in spring.', topicId: 'TV-06' },
  { id: 'TV06-08', word: 'cool', meaning: 'mát mẻ', example: 'The weather is cool in autumn.', topicId: 'TV-06' },
  { id: 'TV06-09', word: 'storm', meaning: 'cơn bão', example: 'A storm is coming this weekend.', topicId: 'TV-06' },
  { id: 'TV06-10', word: 'spring', meaning: 'mùa xuân', example: 'Flowers bloom in spring.', topicId: 'TV-06' },
  { id: 'TV06-11', word: 'summer', meaning: 'mùa hè', example: 'We go swimming in summer.', topicId: 'TV-06' },
  { id: 'TV06-12', word: 'autumn', meaning: 'mùa thu', example: 'The leaves turn yellow in autumn.', topicId: 'TV-06' },
  { id: 'TV06-13', word: 'winter', meaning: 'mùa đông', example: 'It sometimes snows in winter in the mountains.', topicId: 'TV-06' },
  { id: 'TV06-14', word: 'temperature', meaning: 'nhiệt độ', example: 'The temperature today is thirty degrees.', topicId: 'TV-06' },

  // TV-08: Nghề nghiệp
  { id: 'TV08-01', word: 'doctor', meaning: 'bác sĩ', example: 'The doctor works at the hospital.', topicId: 'TV-08' },
  { id: 'TV08-02', word: 'teacher', meaning: 'giáo viên', example: 'My teacher explains lessons clearly.', topicId: 'TV-08' },
  { id: 'TV08-03', word: 'farmer', meaning: 'nông dân', example: 'The farmer grows rice in the field.', topicId: 'TV-08' },
  { id: 'TV08-04', word: 'engineer', meaning: 'kỹ sư', example: 'My father is an engineer.', topicId: 'TV-08' },
  { id: 'TV08-05', word: 'nurse', meaning: 'y tá', example: 'The nurse takes care of patients.', topicId: 'TV-08' },
  { id: 'TV08-06', word: 'pilot', meaning: 'phi công', example: 'A pilot flies an airplane.', topicId: 'TV-08' },
  { id: 'TV08-07', word: 'driver', meaning: 'tài xế', example: 'The bus driver is very careful.', topicId: 'TV-08' },
  { id: 'TV08-08', word: 'singer', meaning: 'ca sĩ', example: 'My sister wants to be a singer.', topicId: 'TV-08' },
  { id: 'TV08-09', word: 'writer', meaning: 'nhà văn', example: 'The writer wrote an interesting book.', topicId: 'TV-08' },
  { id: 'TV08-10', word: 'police officer', meaning: 'cảnh sát', example: 'The police officer helps keep the street safe.', topicId: 'TV-08' },
  { id: 'TV08-11', word: 'firefighter', meaning: 'lính cứu hỏa', example: 'Firefighters put out the fire quickly.', topicId: 'TV-08' },
  { id: 'TV08-12', word: 'chef', meaning: 'đầu bếp', example: 'The chef cooks delicious food.', topicId: 'TV-08' },
  { id: 'TV08-13', word: 'dentist', meaning: 'nha sĩ', example: 'I visited the dentist yesterday.', topicId: 'TV-08' },
  { id: 'TV08-14', word: 'scientist', meaning: 'nhà khoa học', example: 'The scientist works in a laboratory.', topicId: 'TV-08' },

  // TV-10: Sức khỏe & cơ thể người
  { id: 'TV10-01', word: 'head', meaning: 'đầu', example: 'My head hurts a little.', topicId: 'TV-10' },
  { id: 'TV10-02', word: 'eye', meaning: 'mắt', example: 'She has beautiful eyes.', topicId: 'TV-10' },
  { id: 'TV10-03', word: 'ear', meaning: 'tai', example: 'My ear hurts when I have a cold.', topicId: 'TV-10' },
  { id: 'TV10-04', word: 'hand', meaning: 'bàn tay', example: 'Wash your hands before eating.', topicId: 'TV-10' },
  { id: 'TV10-05', word: 'leg', meaning: 'chân', example: 'He hurt his leg while playing football.', topicId: 'TV-10' },
  { id: 'TV10-06', word: 'stomach', meaning: 'bụng', example: 'I have a stomachache.', topicId: 'TV-10' },
  { id: 'TV10-07', word: 'healthy', meaning: 'khỏe mạnh', example: 'Eating vegetables makes you healthy.', topicId: 'TV-10' },
  { id: 'TV10-08', word: 'sick', meaning: 'ốm', example: 'She is sick today and stays at home.', topicId: 'TV-10' },
  { id: 'TV10-09', word: 'fever', meaning: 'sốt', example: 'He has a high fever.', topicId: 'TV-10' },
  { id: 'TV10-10', word: 'cough', meaning: 'ho', example: 'I have a bad cough.', topicId: 'TV-10' },
  { id: 'TV10-11', word: 'medicine', meaning: 'thuốc', example: 'Take this medicine after meals.', topicId: 'TV-10' },
  { id: 'TV10-12', word: 'exercise', meaning: 'tập thể dục', example: 'Exercise every day to stay healthy.', topicId: 'TV-10' },
  { id: 'TV10-13', word: 'rest', meaning: 'nghỉ ngơi', example: 'You should rest when you are tired.', topicId: 'TV-10' },
  { id: 'TV10-14', word: 'hospital', meaning: 'bệnh viện', example: 'My mother works at a hospital.', topicId: 'TV-10' },

  // TV-11: Ngày lễ, văn hóa Việt Nam & thế giới
  { id: 'TV11-01', word: 'Tet holiday', meaning: 'Tết Nguyên Đán', example: 'Tet holiday is the most important festival in Vietnam.', topicId: 'TV-11' },
  { id: 'TV11-02', word: 'Christmas', meaning: 'Giáng sinh', example: 'Many families decorate a tree at Christmas.', topicId: 'TV-11' },
  { id: 'TV11-03', word: 'festival', meaning: 'lễ hội', example: 'The Mid-Autumn Festival is popular with children.', topicId: 'TV-11' },
  { id: 'TV11-04', word: 'lantern', meaning: 'đèn lồng', example: 'Children carry colorful lanterns at the Mid-Autumn Festival.', topicId: 'TV-11' },
  { id: 'TV11-05', word: 'fireworks', meaning: 'pháo hoa', example: "We watched fireworks on New Year's Eve.", topicId: 'TV-11' },
  { id: 'TV11-06', word: 'tradition', meaning: 'truyền thống', example: 'Giving lucky money is a Tet tradition.', topicId: 'TV-11' },
  { id: 'TV11-07', word: 'celebrate', meaning: 'kỷ niệm, ăn mừng', example: "We celebrate Teachers' Day every November.", topicId: 'TV-11' },
  { id: 'TV11-08', word: 'custom', meaning: 'phong tục', example: 'Vietnam has many interesting customs.', topicId: 'TV-11' },
  { id: 'TV11-09', word: 'gift', meaning: 'món quà', example: 'I gave my mother a gift on her birthday.', topicId: 'TV-11' },
  { id: 'TV11-10', word: 'costume', meaning: 'trang phục', example: 'She wore a traditional costume at the festival.', topicId: 'TV-11' },
  { id: 'TV11-11', word: 'parade', meaning: 'cuộc diễu hành', example: 'There was a parade in the city center.', topicId: 'TV-11' },
  { id: 'TV11-12', word: 'New Year', meaning: 'năm mới', example: 'Happy New Year!', topicId: 'TV-11' },
  { id: 'TV11-13', word: 'ancestor', meaning: 'tổ tiên', example: "We visit our ancestors' graves before Tet.", topicId: 'TV-11' },
  { id: 'TV11-14', word: 'reunion', meaning: 'đoàn tụ', example: 'Tet is a time for family reunion.', topicId: 'TV-11' },

  // TV-12: Công nghệ & truyền thông
  { id: 'TV12-01', word: 'computer', meaning: 'máy tính', example: 'I use a computer to do my homework.', topicId: 'TV-12' },
  { id: 'TV12-02', word: 'smartphone', meaning: 'điện thoại thông minh', example: 'My mother has a new smartphone.', topicId: 'TV-12' },
  { id: 'TV12-03', word: 'internet', meaning: 'mạng internet', example: 'We use the internet to find information.', topicId: 'TV-12' },
  { id: 'TV12-04', word: 'website', meaning: 'trang web', example: 'This website has many useful lessons.', topicId: 'TV-12' },
  { id: 'TV12-05', word: 'email', meaning: 'thư điện tử', example: 'Please send me an email.', topicId: 'TV-12' },
  { id: 'TV12-06', word: 'message', meaning: 'tin nhắn', example: 'I sent her a message this morning.', topicId: 'TV-12' },
  { id: 'TV12-07', word: 'video call', meaning: 'cuộc gọi video', example: 'We had a video call with my grandparents.', topicId: 'TV-12' },
  { id: 'TV12-08', word: 'robot', meaning: 'rô bốt', example: 'The robot can answer simple questions.', topicId: 'TV-12' },
  { id: 'TV12-09', word: 'camera', meaning: 'máy ảnh', example: 'He took photos with his new camera.', topicId: 'TV-12' },
  { id: 'TV12-10', word: 'television', meaning: 'tivi', example: 'We watch the news on television.', topicId: 'TV-12' },
  { id: 'TV12-11', word: 'password', meaning: 'mật khẩu', example: "Don't share your password with strangers.", topicId: 'TV-12' },
  { id: 'TV12-12', word: 'download', meaning: 'tải xuống', example: 'I downloaded a new game yesterday.', topicId: 'TV-12' },
  { id: 'TV12-13', word: 'screen', meaning: 'màn hình', example: "Don't sit too close to the screen.", topicId: 'TV-12' },
  { id: 'TV12-14', word: 'technology', meaning: 'công nghệ', example: 'Technology helps students learn more easily.', topicId: 'TV-12' },

  // TV-13: Môi trường & bảo vệ thiên nhiên
  { id: 'TV13-01', word: 'environment', meaning: 'môi trường', example: 'We should protect the environment.', topicId: 'TV-13' },
  { id: 'TV13-02', word: 'pollution', meaning: 'ô nhiễm', example: 'Air pollution is a serious problem in big cities.', topicId: 'TV-13' },
  { id: 'TV13-03', word: 'rubbish', meaning: 'rác', example: 'Please put rubbish in the bin.', topicId: 'TV-13' },
  { id: 'TV13-04', word: 'recycle', meaning: 'tái chế', example: 'We should recycle paper and plastic bottles.', topicId: 'TV-13' },
  { id: 'TV13-05', word: 'plastic bag', meaning: 'túi ni lông', example: 'Try not to use too many plastic bags.', topicId: 'TV-13' },
  { id: 'TV13-06', word: 'clean', meaning: 'sạch sẽ', example: 'Keep the beach clean.', topicId: 'TV-13' },
  { id: 'TV13-07', word: 'dirty', meaning: 'bẩn', example: 'The river looks dirty because of rubbish.', topicId: 'TV-13' },
  { id: 'TV13-08', word: 'plant a tree', meaning: 'trồng cây', example: 'We planted a tree at school last week.', topicId: 'TV-13' },
  { id: 'TV13-09', word: 'save water', meaning: 'tiết kiệm nước', example: 'We should save water every day.', topicId: 'TV-13' },
  { id: 'TV13-10', word: 'save energy', meaning: 'tiết kiệm năng lượng', example: 'Turn off the lights to save energy.', topicId: 'TV-13' },
  { id: 'TV13-11', word: 'climate', meaning: 'khí hậu', example: 'Climate change affects the whole world.', topicId: 'TV-13' },
  { id: 'TV13-12', word: 'earth', meaning: 'trái đất', example: 'We only have one Earth.', topicId: 'TV-13' },
  { id: 'TV13-13', word: 'natural resources', meaning: 'tài nguyên thiên nhiên', example: 'We must not waste natural resources.', topicId: 'TV-13' },
  { id: 'TV13-14', word: 'wildlife', meaning: 'động vật hoang dã', example: 'The forest protects a lot of wildlife.', topicId: 'TV-13' },

  // TV-14: Cụm động từ & thành ngữ thông dụng ở tiểu học
  { id: 'TV14-01', word: 'get up', meaning: 'thức dậy', example: 'I get up at six every morning.', topicId: 'TV-14' },
  { id: 'TV14-02', word: 'turn on', meaning: 'bật (thiết bị)', example: 'Please turn on the light.', topicId: 'TV-14' },
  { id: 'TV14-03', word: 'turn off', meaning: 'tắt (thiết bị)', example: 'Turn off the TV before you sleep.', topicId: 'TV-14' },
  { id: 'TV14-04', word: 'look after', meaning: 'chăm sóc', example: 'She looks after her little brother.', topicId: 'TV-14' },
  { id: 'TV14-05', word: 'look for', meaning: 'tìm kiếm', example: 'I am looking for my pencil case.', topicId: 'TV-14' },
  { id: 'TV14-06', word: 'put on', meaning: 'mặc vào', example: "Put on your coat; it's cold outside.", topicId: 'TV-14' },
  { id: 'TV14-07', word: 'take off', meaning: 'cởi ra', example: 'Take off your shoes before entering the house.', topicId: 'TV-14' },
  { id: 'TV14-08', word: 'come in', meaning: 'đi vào', example: 'Please come in and sit down.', topicId: 'TV-14' },
  { id: 'TV14-09', word: 'go out', meaning: 'đi ra ngoài', example: 'We usually go out on Sundays.', topicId: 'TV-14' },
  { id: 'TV14-10', word: 'write down', meaning: 'viết xuống', example: 'Write down the new words in your notebook.', topicId: 'TV-14' },
  { id: 'TV14-11', word: 'pick up', meaning: 'nhặt lên, đón ai', example: 'My father picks me up from school.', topicId: 'TV-14' },
  { id: 'TV14-12', word: 'hand in', meaning: 'nộp (bài)', example: 'Please hand in your homework tomorrow.', topicId: 'TV-14' },
  { id: 'TV14-13', word: 'once in a while', meaning: 'thỉnh thoảng', example: 'We eat out once in a while.', topicId: 'TV-14' },
  { id: 'TV14-14', word: 'piece of cake', meaning: 'việc dễ như ăn kẹo', example: 'This test is a piece of cake for her.', topicId: 'TV-14' },
]
