import type { Question } from '../../types/domain'

/** ND-02 · Bổ sung ngân hàng câu hỏi ngữ pháp — đợt 3: NP-25 → NP-36. */
export const grammarExtra3: Question[] = [
  // ==================== NP-25 · Cấu trúc với V-ing/to-V khác ====================
  {
    id: 'GX-NP25-01',
    prompt: 'It takes me an hour ______ to school every day.',
    options: ['go', 'to go', 'going', 'went'],
    answerIndex: 1,
    explain: 'Cấu trúc "It takes + sb + thời gian + TO V".',
    topicIds: ['NP-25'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP25-02',
    prompt: 'My father spends two hours ______ in the garden every weekend.',
    options: ['to work', 'working', 'work', 'worked'],
    answerIndex: 1,
    explain: 'Cấu trúc "spend + thời gian + V-ING" (khác với "It takes ... to V").',
    topicIds: ['NP-25'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP25-03',
    prompt: 'I look forward to ______ from you soon.',
    options: ['hear', 'hearing', 'heard', 'be heard'],
    answerIndex: 1,
    explain:
      '"look forward TO" — "to" ở đây là GIỚI TỪ nên sau nó là V-ing, không phải động từ nguyên thể.',
    topicIds: ['NP-25'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP25-04',
    prompt: 'She is good at ______ English songs.',
    options: ['sing', 'to sing', 'singing', 'sings'],
    answerIndex: 2,
    explain: 'Sau giới từ (at, in, of, about...) luôn là V-ing.',
    topicIds: ['NP-25'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP25-05',
    prompt: 'It is difficult ______ this exercise without a dictionary.',
    options: ['do', 'to do', 'doing', 'did'],
    answerIndex: 1,
    explain: 'Cấu trúc "It is + adj + to V".',
    topicIds: ['NP-25'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP25-06',
    prompt: 'My mother made me ______ my room before going out.',
    options: ['to clean', 'clean', 'cleaning', 'cleaned'],
    answerIndex: 1,
    explain: 'Sau "make/let + O" là động từ NGUYÊN THỂ KHÔNG "to".',
    topicIds: ['NP-25', 'NP-36'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP25-07',
    prompt: 'The teacher advised us ______ more English books.',
    options: ['read', 'to read', 'reading', 'reads'],
    answerIndex: 1,
    explain: '"advise + O + to V".',
    topicIds: ['NP-25'],
    skillId: 'KN-03',
  },

  // ==================== NP-26 · so...that / such...that ====================
  {
    id: 'GX-NP26-01',
    prompt: 'The weather was ______ hot that we stayed indoors all day.',
    options: ['such', 'so', 'very', 'too'],
    answerIndex: 1,
    explain: '"so + tính từ + that". "such" phải đi với cụm danh từ.',
    topicIds: ['NP-26', 'TV-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP26-02',
    prompt: 'It was ______ an exciting match that nobody wanted to leave.',
    options: ['so', 'such', 'very', 'too'],
    answerIndex: 1,
    explain: '"such + a/an + adj + danh từ + that".',
    topicIds: ['NP-26', 'TV-07'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP26-03',
    prompt: 'She spoke ______ quickly that I could not understand her.',
    options: ['such', 'so', 'too', 'very'],
    answerIndex: 1,
    explain: '"so" còn dùng với TRẠNG TỪ: so quickly that...',
    topicIds: ['NP-26'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP26-04',
    prompt: 'There were ______ many people that we could not find a seat.',
    options: ['such', 'so', 'very', 'too'],
    answerIndex: 1,
    explain:
      'Ngoại lệ cần nhớ: "so many / so much / so few / so little" — dùng "so" chứ không phải "such".',
    topicIds: ['NP-26', 'NP-10'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP26-05',
    prompt: 'They were ______ interesting books that I read them all in a week.',
    options: ['so', 'such', 'very', 'too'],
    answerIndex: 1,
    explain: 'Danh từ số nhiều không có mạo từ: "such + adj + Ns + that".',
    topicIds: ['NP-26'],
    skillId: 'KN-03',
  },

  // ==================== NP-27 · Đồng tình: so, too, either, neither ====================
  {
    id: 'GX-NP27-01',
    prompt: 'I like ice cream. — ______.',
    options: ['So do I', 'So I do', 'Neither do I', 'I do so'],
    answerIndex: 0,
    explain: 'Đồng tình câu khẳng định: "So + trợ động từ + S" (đảo trật tự).',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP27-02',
    prompt: "I don't like durian. — ______.",
    options: ['So do I', 'Neither do I', 'Neither I do', 'I do too'],
    answerIndex: 1,
    explain: 'Đồng tình câu PHỦ ĐỊNH: "Neither + trợ động từ + S" (bản thân đã mang nghĩa phủ định).',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP27-03',
    prompt: 'Lan can swim, and ______.',
    options: ['so can Nam', 'so Nam can', 'so does Nam', 'Nam can so'],
    answerIndex: 0,
    explain: 'Trợ động từ phải khớp câu đầu (can) và đảo lên trước chủ ngữ.',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP27-04',
    prompt: 'She has never been to Hue, and I haven\'t ______.',
    options: ['too', 'either', 'neither', 'so'],
    answerIndex: 1,
    explain: '"either" đứng CUỐI câu phủ định; "too" chỉ dùng cho câu khẳng định.',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP27-05',
    prompt: 'My brother went to the party and my sister did ______.',
    options: ['either', 'neither', 'too', 'so'],
    answerIndex: 2,
    explain: '"too" đứng cuối câu khẳng định để đồng tình.',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
  },

  // ==================== NP-28 · Would like, would rather ====================
  {
    id: 'GX-NP28-01',
    prompt: 'I would like ______ a glass of orange juice, please.',
    options: ['have', 'to have', 'having', 'had'],
    answerIndex: 1,
    explain: '"would like + to V".',
    topicIds: ['NP-28', 'TV-04'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP28-02',
    prompt: 'I would rather ______ at home than go out tonight.',
    options: ['to stay', 'stay', 'staying', 'stayed'],
    answerIndex: 1,
    explain: '"would rather + V nguyên thể KHÔNG to + than + V nguyên thể".',
    topicIds: ['NP-28'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP28-03',
    prompt: 'Would you like ______ tea or coffee?',
    options: ['any', 'some', 'many', 'a few'],
    answerIndex: 1,
    explain: 'Lời mời dùng "some" dù ở dạng câu hỏi.',
    topicIds: ['NP-28', 'NP-10'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP28-04',
    prompt: 'What would you like ______ this weekend?',
    options: ['do', 'to do', 'doing', 'did'],
    answerIndex: 1,
    explain: '"would like to + V" trong câu hỏi Wh-.',
    topicIds: ['NP-28'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP28-05',
    prompt: '"Would you like to join our club?" — "______"',
    options: ['Yes, I would love to.', 'Yes, I like.', 'Yes, I would like.', 'Yes, I do.'],
    answerIndex: 0,
    explain:
      'Trả lời lời mời: "Yes, I\'d love to." — không lược "to" và không dùng "Yes, I do".',
    topicIds: ['NP-28'],
    skillId: 'KN-04',
    challenging: true,
  },

  // ==================== NP-29 · Câu ước: wish, if only ====================
  {
    id: 'GX-NP29-01',
    prompt: 'I wish I ______ how to play the guitar.',
    options: ['know', 'knew', 'will know', 'have known'],
    answerIndex: 1,
    explain: 'Ước trái với hiện tại: lùi một thì ⇒ quá khứ đơn.',
    topicIds: ['NP-29'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP29-02',
    prompt: 'She wishes she ______ taller.',
    options: ['is', 'was', 'were', 'will be'],
    answerIndex: 2,
    explain: 'Câu ước dùng "were" cho MỌI ngôi (dạng giả định) — đáp án chuẩn trong đề thi.',
    topicIds: ['NP-29'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP29-03',
    prompt: 'I wish it ______ raining so that we could go out.',
    options: ["isn't", "wasn't", "won't be", "hasn't been"],
    answerIndex: 1,
    explain: 'Ước điều trái ngược ở hiện tại ⇒ lùi thì: is not → wasn\'t.',
    topicIds: ['NP-29', 'TV-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP29-04',
    prompt: 'If only I ______ more time to finish this exercise!',
    options: ['have', 'had', 'will have', 'have had'],
    answerIndex: 1,
    explain: '"If only" dùng như "wish" — ước ở hiện tại thì lùi về quá khứ đơn.',
    topicIds: ['NP-29'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP29-05',
    prompt: 'My little sister wishes she ______ go to school with me next year.',
    options: ['can', 'could', 'will', 'may'],
    answerIndex: 1,
    explain: 'can → could trong câu ước.',
    topicIds: ['NP-29'],
    skillId: 'KN-03',
  },

  // ==================== NP-30 · Hòa hợp chủ ngữ – động từ ====================
  {
    id: 'GX-NP30-01',
    prompt: 'Every student in the two classes ______ a new textbook.',
    options: ['have', 'has', 'are having', 'were'],
    answerIndex: 1,
    explain: '"Every + N số ít" luôn chia động từ SỐ ÍT, dù phía sau có cụm số nhiều.',
    topicIds: ['NP-30'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP30-02',
    prompt: 'The number of students in my school ______ increasing.',
    options: ['are', 'is', 'have', 'were'],
    answerIndex: 1,
    explain:
      '"The number of + Ns" chia SỐ ÍT; ngược lại "A number of + Ns" chia số nhiều. Bẫy rất hay ra.',
    topicIds: ['NP-30'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP30-03',
    prompt: 'Both my brother and my sister ______ good at maths.',
    options: ['is', 'are', 'was', 'has'],
    answerIndex: 1,
    explain: '"Both A and B" luôn chia số nhiều.',
    topicIds: ['NP-30'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP30-04',
    prompt: 'Neither Nam nor his friends ______ the answer.',
    options: ['knows', 'know', 'is knowing', 'has known'],
    answerIndex: 1,
    explain:
      'Với "either/neither ... or/nor", động từ chia theo chủ ngữ GẦN NHẤT — ở đây là "his friends" (số nhiều).',
    topicIds: ['NP-30'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP30-05',
    prompt: 'Mathematics ______ my favourite subject.',
    options: ['are', 'is', 'were', 'have been'],
    answerIndex: 1,
    explain: 'Tên môn học tận cùng -ics (mathematics, physics) chia SỐ ÍT.',
    topicIds: ['NP-30', 'TV-02'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-31 · Cặp từ dễ nhầm ====================
  {
    id: 'GX-NP31-01',
    prompt: 'Please ______ me the salt.',
    options: ['bring', 'take', 'pass', 'carry'],
    answerIndex: 2,
    explain: '"pass somebody something" = đưa/chuyển đồ cho ai đó ở gần.',
    topicIds: ['NP-31'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP31-02',
    prompt: 'My parents don\'t ______ me to go out after 9 p.m.',
    options: ['let', 'allow', 'make', 'have'],
    answerIndex: 1,
    explain: '"allow somebody TO V"; "let somebody V" (không có "to").',
    topicIds: ['NP-31', 'NP-36'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP31-03',
    prompt: 'Can you ______ me how to get to the post office?',
    options: ['say', 'speak', 'tell', 'talk'],
    answerIndex: 2,
    explain: '"tell somebody something"; "say something TO somebody"; "speak/talk TO somebody".',
    topicIds: ['NP-31'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP31-04',
    prompt: 'She ______ a lot of money on books last month.',
    options: ['paid', 'spent', 'cost', 'took'],
    answerIndex: 1,
    explain: '"spend money ON something"; "pay FOR something"; "something costs + giá".',
    topicIds: ['NP-31'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP31-05',
    prompt: 'I ______ my homework every evening.',
    options: ['make', 'do', 'take', 'have'],
    answerIndex: 1,
    explain: '"do homework/housework/exercise" ≠ "make a cake/a noise/a mistake".',
    topicIds: ['NP-31'],
    skillId: 'KN-03',
  },

  // ==================== NP-32 · There is / There are ====================
  {
    id: 'GX-NP32-01',
    prompt: 'There ______ a lot of milk in the bottle.',
    options: ['is', 'are', 'have', 'were'],
    answerIndex: 0,
    explain: '"milk" không đếm được ⇒ "There is", dù có "a lot of".',
    topicIds: ['NP-32', 'NP-10'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP32-02',
    prompt: 'There ______ thirty students in my class.',
    options: ['is', 'are', 'has', 'have'],
    answerIndex: 1,
    explain: 'Danh từ đếm được số nhiều ⇒ "There are".',
    topicIds: ['NP-32'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP32-03',
    prompt: '______ any bananas left in the kitchen?',
    options: ['Is there', 'Are there', 'There are', 'Have there'],
    answerIndex: 1,
    explain: 'Câu hỏi đảo "Are there + danh từ số nhiều".',
    topicIds: ['NP-32'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP32-04',
    prompt: 'There ______ a big park near my house ten years ago.',
    options: ['is', 'was', 'were', 'has been'],
    answerIndex: 1,
    explain: '"ten years ago" ⇒ quá khứ, chủ ngữ số ít ⇒ "There was".',
    topicIds: ['NP-32', 'NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP32-05',
    prompt: 'There ______ a pen and two notebooks on the desk.',
    options: ['is', 'are', 'have', 'has'],
    answerIndex: 0,
    explain:
      'Khi liệt kê, động từ chia theo danh từ ĐẦU TIÊN — "a pen" số ít ⇒ "There is".',
    topicIds: ['NP-32'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-33 · too...to / enough ====================
  {
    id: 'GX-NP33-01',
    prompt: 'This coffee is too hot ______.',
    options: ['to drink', 'to drink it', 'drinking', 'for drink'],
    answerIndex: 0,
    explain:
      'Sau "too + adj + to V" KHÔNG lặp lại tân ngữ, vì chủ ngữ đầu câu (coffee) đã là tân ngữ của "drink".',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP33-02',
    prompt: 'He is old ______ to drive a car.',
    options: ['enough', 'too', 'so', 'very'],
    answerIndex: 0,
    explain: '"enough" đứng SAU tính từ: old enough.',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP33-03',
    prompt: 'We don\'t have ______ chairs for everyone.',
    options: ['chairs enough', 'enough', 'too', 'enough of'],
    answerIndex: 1,
    explain: '"enough" đứng TRƯỚC danh từ: enough chairs.',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP33-04',
    prompt: 'The box is too heavy for me ______.',
    options: ['carry', 'to carry', 'carrying', 'carried'],
    answerIndex: 1,
    explain: 'Cấu trúc "too + adj + for somebody + TO V".',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP33-05',
    prompt: 'She speaks English well ______ to work in that company.',
    options: ['too', 'enough', 'so', 'such'],
    answerIndex: 1,
    explain: '"enough" cũng đứng sau TRẠNG TỪ: well enough.',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP33-06',
    prompt: 'It was ______ dark for us to see anything.',
    options: ['enough', 'too', 'so', 'very'],
    answerIndex: 1,
    explain: 'Nghĩa "quá tối để có thể nhìn thấy" ⇒ "too + adj + for sb + to V".',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP33-07',
    prompt: 'I don\'t have ______ money to buy that bicycle.',
    options: ['enough', 'too', 'many', 'much enough'],
    answerIndex: 0,
    explain: '"enough + danh từ không đếm được" (enough money).',
    topicIds: ['NP-33', 'NP-10'],
    skillId: 'KN-03',
  },

  // ==================== NP-34 · Biến đổi từ loại ====================
  {
    id: 'GX-NP34-01',
    prompt: 'My sister sings very ______. (beauty)',
    options: ['beauty', 'beautiful', 'beautifully', 'beautify'],
    answerIndex: 2,
    explain: 'Bổ nghĩa cho động từ "sings" ⇒ TRẠNG TỪ: beautifully.',
    topicIds: ['NP-34'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP34-02',
    prompt: 'Air ______ is a serious problem in big cities. (pollute)',
    options: ['pollute', 'polluted', 'pollution', 'polluting'],
    answerIndex: 2,
    explain: 'Sau "Air" và trước động từ "is" cần một DANH TỪ: pollution.',
    topicIds: ['NP-34', 'TV-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP34-03',
    prompt: 'He is a very ______ student. (care)',
    options: ['care', 'careful', 'carefully', 'careless'],
    answerIndex: 1,
    explain: 'Trước danh từ "student" cần TÍNH TỪ mang nghĩa tích cực: careful.',
    topicIds: ['NP-34'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP34-04',
    prompt: 'The teacher was ______ with our behaviour. (please)',
    options: ['pleasant', 'pleased', 'pleasing', 'pleasure'],
    answerIndex: 1,
    explain: 'Người nhận cảm xúc ⇒ tính từ đuôi -ed: "be pleased with".',
    topicIds: ['NP-34', 'NP-05'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP34-05',
    prompt: 'We must find a ______ to this problem. (solve)',
    options: ['solve', 'solved', 'solution', 'solving'],
    answerIndex: 2,
    explain: 'Sau mạo từ "a" cần DANH TỪ: solution.',
    topicIds: ['NP-34'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-35 · Đại từ thay thế one/ones, another/other ====================
  {
    id: 'GX-NP35-01',
    prompt: 'I don\'t like this shirt. Can you show me another ______?',
    options: ['one', 'ones', 'it', 'them'],
    answerIndex: 0,
    explain: '"one" thay cho một danh từ đếm được SỐ ÍT đã nhắc tới.',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP35-02',
    prompt: 'These apples are bad. Give me the red ______, please.',
    options: ['one', 'ones', 'it', 'other'],
    answerIndex: 1,
    explain: '"ones" thay cho danh từ đếm được SỐ NHIỀU.',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP35-03',
    prompt: 'I have two pens. One is blue and ______ is black.',
    options: ['another', 'other', 'the other', 'others'],
    answerIndex: 2,
    explain: 'Chỉ còn ĐÚNG MỘT cái còn lại ⇒ "the other".',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP35-04',
    prompt: 'Some students like maths; ______ prefer literature.',
    options: ['another', 'the other', 'others', 'other'],
    answerIndex: 2,
    explain: '"others" = một số người khác (đứng một mình, không có danh từ theo sau).',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP35-05',
    prompt: 'Would you like ______ cup of tea?',
    options: ['other', 'others', 'another', 'the other'],
    answerIndex: 2,
    explain: '"another + danh từ số ít" = thêm một cái nữa.',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
  },

  // ==================== NP-36 · make/let/have + O + V ====================
  {
    id: 'GX-NP36-01',
    prompt: 'My parents don\'t let me ______ out late at night.',
    options: ['to go', 'go', 'going', 'gone'],
    answerIndex: 1,
    explain: '"let + O + V nguyên thể KHÔNG to".',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP36-02',
    prompt: 'The film made me ______.',
    options: ['to cry', 'cry', 'crying', 'cried'],
    answerIndex: 1,
    explain: '"make + O + V nguyên thể KHÔNG to".',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP36-03',
    prompt: 'I had the mechanic ______ my bicycle yesterday.',
    options: ['repair', 'to repair', 'repaired', 'repairing'],
    answerIndex: 0,
    explain: '"have + NGƯỜI + V nguyên thể" = nhờ ai đó làm việc gì.',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP36-04',
    prompt: 'She had her hair ______ last weekend.',
    options: ['cut', 'to cut', 'cutting', 'cuts'],
    answerIndex: 0,
    explain:
      '"have + VẬT + V3/V-ed" = nhờ người khác làm gì cho vật đó. "cut" có V3 giữ nguyên là "cut".',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP36-05',
    prompt: 'The teacher made the students ______ the exercise again.',
    options: ['to do', 'do', 'doing', 'did'],
    answerIndex: 1,
    explain: '"make + O + V nguyên thể" ở thể chủ động (bị động thì lại có "to": be made TO do).',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
    challenging: true,
  },
]
