import type { Question } from '../../types/domain'

/** ND-02 · Bổ sung ngân hàng câu hỏi ngữ pháp — đợt 2: NP-13 → NP-24. */
export const grammarExtra2: Question[] = [
  // ==================== NP-13 · Quá khứ đơn ====================
  {
    id: 'GX-NP13-01',
    prompt: 'We ______ to Ha Long Bay last summer.',
    options: ['go', 'went', 'have gone', 'are going'],
    answerIndex: 1,
    explain: '"last summer" là mốc quá khứ rõ ràng ⇒ quá khứ đơn: went.',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP13-02',
    prompt: 'She ______ finish her homework yesterday evening.',
    options: ["didn't", "doesn't", "wasn't", "hasn't"],
    answerIndex: 0,
    explain: 'Phủ định quá khứ đơn: didn\'t + V nguyên thể.',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP13-03',
    prompt: 'What time ______ you get up this morning?',
    options: ['do', 'did', 'are', 'have'],
    answerIndex: 1,
    explain: '"this morning" đã trôi qua ⇒ dùng "did" + V nguyên thể.',
    topicIds: ['NP-13', 'NP-17'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP13-04',
    prompt: 'My grandfather ______ a teacher for thirty years before he retired.',
    options: ['is', 'was', 'has been', 'will be'],
    answerIndex: 1,
    explain:
      'Việc đã kết thúc hoàn toàn trong quá khứ (đã nghỉ hưu) ⇒ quá khứ đơn, không dùng hiện tại hoàn thành.',
    topicIds: ['NP-13', 'NP-15'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP13-05',
    prompt: 'They ______ the new bridge two years ago.',
    options: ['build', 'built', 'have built', 'are building'],
    answerIndex: 1,
    explain: '"ago" luôn đi với quá khứ đơn.',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },

  // ==================== NP-14 · Quá khứ tiếp diễn ====================
  {
    id: 'GX-NP14-01',
    prompt: 'While I ______ dinner, the phone rang.',
    options: ['cook', 'cooked', 'was cooking', 'have cooked'],
    answerIndex: 2,
    explain:
      'Hành động DÀI làm nền dùng quá khứ tiếp diễn; hành động NGẮN cắt ngang (rang) dùng quá khứ đơn.',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP14-02',
    prompt: 'At 8 p.m. last night, we ______ television.',
    options: ['watch', 'watched', 'were watching', 'have watched'],
    answerIndex: 2,
    explain: 'Một thời điểm cụ thể trong quá khứ ⇒ quá khứ tiếp diễn.',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP14-03',
    prompt: 'When the teacher came in, the students ______ noisily.',
    options: ['talk', 'talked', 'were talking', 'have talked'],
    answerIndex: 2,
    explain: 'Việc đang diễn ra khi một việc khác xảy đến ⇒ quá khứ tiếp diễn.',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP14-04',
    prompt: 'While my mother ______ the floor, my father ______ the dishes.',
    options: [
      'cleaned / washed',
      'was cleaning / was washing',
      'cleaned / was washing',
      'is cleaning / washes',
    ],
    answerIndex: 1,
    explain:
      'Hai hành động DÀI diễn ra song song trong quá khứ ⇒ cả hai đều ở quá khứ tiếp diễn.',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP14-05',
    prompt: 'I ______ my keys while I was walking to school.',
    options: ['was losing', 'lost', 'lose', 'have lost'],
    answerIndex: 1,
    explain: 'Hành động NGẮN xảy ra trong lúc hành động dài đang diễn ra ⇒ quá khứ đơn.',
    topicIds: ['NP-14', 'NP-13'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP14-06',
    prompt: 'She fell down when she ______ down the stairs.',
    options: ['runs', 'ran', 'was running', 'has run'],
    answerIndex: 2,
    explain: 'Việc đang chạy làm nền cho việc ngã ⇒ was running.',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP14-07',
    prompt: 'It ______ heavily when we arrived at the airport.',
    options: ['rains', 'rained', 'was raining', 'has rained'],
    answerIndex: 2,
    explain: 'Trời đang mưa (bối cảnh kéo dài) lúc một việc xảy ra ⇒ quá khứ tiếp diễn.',
    topicIds: ['NP-14', 'TV-06'],
    skillId: 'KN-03',
  },

  // ==================== NP-15 · Hiện tại hoàn thành ====================
  {
    id: 'GX-NP15-01',
    prompt: 'I ______ this film three times.',
    options: ['see', 'saw', 'have seen', 'was seeing'],
    answerIndex: 2,
    explain: 'Số lần đã trải nghiệm tính tới hiện tại ⇒ hiện tại hoàn thành.',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP15-02',
    prompt: 'She has studied English ______ five years.',
    options: ['since', 'for', 'in', 'from'],
    answerIndex: 1,
    explain: '"for" + KHOẢNG thời gian (five years); "since" + MỐC thời gian (2020).',
    topicIds: ['NP-15', 'NP-08'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP15-03',
    prompt: '______ you ever ______ to Japan?',
    options: ['Did / go', 'Have / been', 'Are / going', 'Do / go'],
    answerIndex: 1,
    explain: '"ever" hỏi trải nghiệm ⇒ Have you ever been to...? (been = đã đến và đã về).',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP15-04',
    prompt: 'My brother ______ his homework yet.',
    options: ["hasn't finished", "didn't finish", "doesn't finish", "wasn't finishing"],
    answerIndex: 0,
    explain: '"yet" trong câu phủ định là dấu hiệu của hiện tại hoàn thành.',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP15-05',
    prompt: 'They ______ already ______ the classroom.',
    options: ['did / clean', 'have / cleaned', 'are / cleaning', 'were / cleaning'],
    answerIndex: 1,
    explain: '"already" đứng giữa have và V3 trong câu khẳng định.',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP15-06',
    prompt: 'Lan ______ to Hue last year, and she ______ there twice since then.',
    options: [
      'went / has been',
      'has gone / went',
      'goes / has been',
      'has been / went',
    ],
    answerIndex: 0,
    explain:
      'Mốc "last year" ⇒ quá khứ đơn; "since then" ⇒ hiện tại hoàn thành. Đề CLC rất hay ghép hai thì này trong một câu.',
    topicIds: ['NP-15', 'NP-13'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP15-07',
    prompt: 'This is the first time I ______ Vietnamese food.',
    options: ['try', 'tried', 'have tried', 'am trying'],
    answerIndex: 2,
    explain:
      'Cấu trúc cố định "This is the first time + S + have/has + V3" — hay ra trong dạng viết lại câu.',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-16 · Tương lai đơn & used to ====================
  {
    id: 'GX-NP16-01',
    prompt: 'I think it ______ rain tomorrow.',
    options: ['will', 'is', 'was', 'has'],
    answerIndex: 0,
    explain: 'Dự đoán không có căn cứ chắc chắn ⇒ "will".',
    topicIds: ['NP-16', 'TV-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP16-02',
    prompt: 'Look at those dark clouds! It ______ rain.',
    options: ['will', 'is going to', 'used to', 'would'],
    answerIndex: 1,
    explain:
      'Có DẤU HIỆU hiện tại nhìn thấy được (mây đen) ⇒ "be going to", không dùng "will".',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP16-03',
    prompt: 'My father ______ smoke, but he gave it up last year.',
    options: ['uses to', 'used to', 'is used to', 'was used to'],
    answerIndex: 1,
    explain: '"used to + V" = thói quen cũ nay không còn.',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP16-04',
    prompt: 'The phone is ringing. — I ______ answer it.',
    options: ['am going to', 'will', 'used to', 'am'],
    answerIndex: 1,
    explain: 'Quyết định ngay tại thời điểm nói ⇒ "will".',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP16-05',
    prompt: 'There ______ a school festival next Saturday.',
    options: ['will be', 'will have', 'is going', 'will is'],
    answerIndex: 0,
    explain: 'Cấu trúc "There will be + N" cho tương lai của "There is/are".',
    topicIds: ['NP-16', 'NP-32'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP16-06',
    prompt: 'She ______ have long hair when she was a little girl.',
    options: ['used to', 'uses to', 'is used to', 'would like to'],
    answerIndex: 0,
    explain: '"used to" còn dùng cho TRẠNG THÁI trong quá khứ nay đã khác.',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP16-07',
    prompt: 'If you study hard, you ______ pass the entrance exam.',
    options: ['would', 'will', 'used to', 'are'],
    answerIndex: 1,
    explain: 'Câu điều kiện loại 1: If + hiện tại đơn, S + will + V.',
    topicIds: ['NP-16', 'NP-20'],
    skillId: 'KN-03',
  },

  // ==================== NP-17 · Câu hỏi Wh-/How, câu hỏi đuôi ====================
  {
    id: 'GX-NP17-01',
    prompt: '______ is your new English teacher? — She is very friendly.',
    options: ['Who', 'What', 'How', 'Which'],
    answerIndex: 1,
    explain:
      '"What is somebody like?" hỏi TÍNH CÁCH. "How is she?" là hỏi sức khỏe — bẫy rất hay gặp.',
    topicIds: ['NP-17'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP17-02',
    prompt: '______ far is it from your house to school?',
    options: ['What', 'How', 'Which', 'Where'],
    answerIndex: 1,
    explain: 'Hỏi khoảng cách dùng "How far".',
    topicIds: ['NP-17', 'TV-09'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP17-03',
    prompt: 'You are Nam\'s sister, ______?',
    options: ["aren't you", "are you", "don't you", "isn't it"],
    answerIndex: 0,
    explain: 'Câu hỏi đuôi: mệnh đề khẳng định ⇒ đuôi phủ định, giữ nguyên chủ ngữ và trợ động từ.',
    topicIds: ['NP-17'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP17-04',
    prompt: "Lan doesn't like coffee, ______?",
    options: ["does she", "doesn't she", "is she", "do she"],
    answerIndex: 0,
    explain: 'Mệnh đề phủ định ⇒ đuôi khẳng định "does she".',
    topicIds: ['NP-17'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP17-05',
    prompt: "Let's go to the cinema tonight, ______?",
    options: ["will we", "shall we", "don't we", "do we"],
    answerIndex: 1,
    explain: 'Câu bắt đầu bằng "Let\'s" luôn có câu hỏi đuôi là "shall we?" — ngoại lệ cần thuộc.',
    topicIds: ['NP-17'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-18 · Mệnh đề quan hệ (ưu tiên 1 — 12 câu) ====================
  {
    id: 'GX-NP18-01',
    prompt: 'The girl ______ is sitting next to me is my best friend.',
    options: ['which', 'who', 'whose', 'where'],
    answerIndex: 1,
    explain: 'Đại từ quan hệ thay cho NGƯỜI làm chủ ngữ ⇒ "who".',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP18-02',
    prompt: 'This is the book ______ I borrowed from the library.',
    options: ['who', 'which', 'whose', 'when'],
    answerIndex: 1,
    explain: 'Thay cho VẬT ⇒ "which" (hoặc "that").',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP18-03',
    prompt: 'I know a boy ______ father is a famous doctor.',
    options: ['who', 'which', 'whose', 'whom'],
    answerIndex: 2,
    explain: 'Chỉ SỞ HỮU (bố của cậu bé) ⇒ "whose" + danh từ, không có mạo từ đứng sau.',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP18-04',
    prompt: 'That is the school ______ my mother used to study.',
    options: ['which', 'where', 'who', 'that'],
    answerIndex: 1,
    explain:
      'Sau nơi chốn mà mệnh đề phía sau ĐỦ thành phần (my mother used to study) ⇒ dùng "where".',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP18-05',
    prompt: 'Ha Noi, ______ is the capital of Viet Nam, is over 1,000 years old.',
    options: ['that', 'which', 'where', 'who'],
    answerIndex: 1,
    explain:
      'Mệnh đề KHÔNG xác định (có dấu phẩy) KHÔNG bao giờ dùng "that" — phải dùng which/who.',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP18-06',
    prompt: 'The man ______ we met yesterday is my uncle.',
    options: ['who', 'which', 'whose', 'where'],
    answerIndex: 0,
    explain: 'Thay cho người làm TÂN NGỮ — dùng who/whom/that, hoặc lược bỏ được.',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP18-07',
    prompt: 'I still remember the day ______ we first met.',
    options: ['which', 'where', 'when', 'that'],
    answerIndex: 2,
    explain: 'Trạng từ quan hệ chỉ THỜI GIAN ⇒ "when".',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP18-08',
    prompt: 'The cake ______ my mother made was delicious.',
    options: ['who', 'which', 'whose', 'when'],
    answerIndex: 1,
    explain: 'Thay cho vật làm tân ngữ ⇒ "which/that" (có thể lược bỏ).',
    topicIds: ['NP-18', 'TV-04'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP18-09',
    prompt: 'The reason ______ he was late is that his bike broke down.',
    options: ['which', 'why', 'where', 'when'],
    answerIndex: 1,
    explain: 'Sau "the reason" dùng trạng từ quan hệ "why".',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-19 · Mệnh đề trạng ngữ ====================
  {
    id: 'GX-NP19-01',
    prompt: '______ I finish my homework, I will watch TV.',
    options: ['Before', 'After', 'While', 'Because'],
    answerIndex: 1,
    explain: 'Làm bài xong rồi mới xem TV ⇒ "After".',
    topicIds: ['NP-19'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP19-02',
    prompt: 'Please turn off the lights ______ you leave the room.',
    options: ['when', 'because', 'although', 'so'],
    answerIndex: 0,
    explain: 'Mệnh đề chỉ thời điểm ⇒ "when".',
    topicIds: ['NP-19', 'TV-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP19-03',
    prompt: 'I will call you as soon as I ______ home.',
    options: ['will get', 'get', 'got', 'am getting'],
    answerIndex: 1,
    explain:
      'Mệnh đề thời gian (as soon as, when, before, after, until) KHÔNG dùng "will" — dùng hiện tại đơn thay cho tương lai.',
    topicIds: ['NP-19', 'NP-16'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP19-04',
    prompt: 'We waited ______ the rain stopped.',
    options: ['until', 'while', 'since', 'although'],
    answerIndex: 0,
    explain: '"until" = cho tới khi, diễn tả điểm kết thúc của việc chờ.',
    topicIds: ['NP-19'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP19-05',
    prompt: '______ she was ill, she still came to school.',
    options: ['Because', 'Although', 'So', 'When'],
    answerIndex: 1,
    explain: 'Hai vế trái ngược ⇒ "Although".',
    topicIds: ['NP-19'],
    skillId: 'KN-03',
  },

  // ==================== NP-20 · Câu điều kiện 0 và 1 ====================
  {
    id: 'GX-NP20-01',
    prompt: 'If you heat ice, it ______.',
    options: ['will melt', 'melts', 'melted', 'would melt'],
    answerIndex: 1,
    explain: 'Sự thật hiển nhiên ⇒ điều kiện loại 0: cả hai vế đều hiện tại đơn.',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP20-02',
    prompt: 'If it ______ tomorrow, we will stay at home.',
    options: ['will rain', 'rains', 'rained', 'is raining'],
    answerIndex: 1,
    explain: 'Vế "If" của loại 1 dùng hiện tại đơn, KHÔNG dùng "will".',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP20-03',
    prompt: 'If you don\'t hurry, you ______ the bus.',
    options: ['miss', 'will miss', 'missed', 'would miss'],
    answerIndex: 1,
    explain: 'Vế chính của loại 1 dùng "will + V".',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP20-04',
    prompt: 'Unless you water the plants, they ______.',
    options: ['will die', "won't die", 'die', 'died'],
    answerIndex: 0,
    explain:
      '"Unless" = "If ... not", bản thân nó đã mang nghĩa phủ định nên vế sau giữ khẳng định.',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP20-05',
    prompt: 'If you ______ this button, the machine will start.',
    options: ['will press', 'press', 'pressed', 'are pressing'],
    answerIndex: 1,
    explain: 'Loại 1: If + S + V(hiện tại đơn), S + will + V.',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP20-06',
    prompt: 'Water boils if you ______ it to 100°C.',
    options: ['will heat', 'heat', 'heated', 'would heat'],
    answerIndex: 1,
    explain: 'Điều kiện loại 0 cho quy luật tự nhiên — hai vế đều hiện tại đơn.',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP20-07',
    prompt: 'If I have enough money, I ______ a new bicycle next month.',
    options: ['buy', 'will buy', 'bought', 'would buy'],
    answerIndex: 1,
    explain: 'Điều kiện có thật ở tương lai ⇒ loại 1: will + V.',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
  },

  // ==================== NP-21 · Câu bị động (ưu tiên 1) ====================
  {
    id: 'GX-NP21-01',
    prompt: 'English ______ in many countries around the world.',
    options: ['speaks', 'is spoken', 'spoke', 'is speaking'],
    answerIndex: 1,
    explain: 'Bị động hiện tại đơn: am/is/are + V3.',
    topicIds: ['NP-21'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP21-02',
    prompt: 'This bridge ______ in 1990.',
    options: ['builds', 'built', 'was built', 'is built'],
    answerIndex: 2,
    explain: 'Mốc quá khứ ⇒ bị động quá khứ đơn: was/were + V3.',
    topicIds: ['NP-21', 'NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP21-03',
    prompt: 'The classrooms ______ every afternoon.',
    options: ['is cleaned', 'are cleaned', 'clean', 'were cleaned'],
    answerIndex: 1,
    explain: 'Chủ ngữ số nhiều "classrooms" + hiện tại đơn ⇒ "are cleaned".',
    topicIds: ['NP-21'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP21-04',
    prompt: 'A lot of trees ______ in our schoolyard last year.',
    options: ['planted', 'were planted', 'are planted', 'have planted'],
    answerIndex: 1,
    explain: 'Cây không tự trồng được ⇒ bị động; "last year" ⇒ were planted.',
    topicIds: ['NP-21', 'TV-13'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP21-05',
    prompt: 'These photos ______ by my brother.',
    options: ['took', 'were taken', 'are taking', 'have taken'],
    answerIndex: 1,
    explain: 'Có "by + tác nhân" là dấu hiệu bị động; take → taken.',
    topicIds: ['NP-21'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP21-06',
    prompt: 'The homework must ______ before Friday.',
    options: ['finish', 'be finished', 'is finished', 'finished'],
    answerIndex: 1,
    explain: 'Bị động với động từ khuyết thiếu: modal + BE + V3.',
    topicIds: ['NP-21', 'NP-23'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP21-07',
    prompt: 'I ______ a beautiful present on my birthday last week.',
    options: ['was given', 'was gave', 'gave', 'am given'],
    answerIndex: 0,
    explain:
      'Động từ 2 tân ngữ (give sb sth) có thể đưa NGƯỜI lên làm chủ ngữ bị động: I was given a present.',
    topicIds: ['NP-21'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-22 · Câu tường thuật (ưu tiên 1) ====================
  {
    id: 'GX-NP22-01',
    prompt: 'He said, "I am tired." → He said that he ______ tired.',
    options: ['is', 'was', 'has been', 'will be'],
    answerIndex: 1,
    explain: 'Lùi thì: hiện tại đơn → quá khứ đơn.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP22-02',
    prompt: 'She said, "I will help you." → She said she ______ help me.',
    options: ['will', 'would', 'can', 'shall'],
    answerIndex: 1,
    explain: 'will → would khi tường thuật.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP22-03',
    prompt: 'Mai asked me, "Where do you live?" → Mai asked me where ______.',
    options: ['do I live', 'I lived', 'did I live', 'I live'],
    answerIndex: 1,
    explain:
      'Câu hỏi tường thuật phải đưa về trật tự KHẲNG ĐỊNH (S + V), bỏ trợ động từ do/did, và lùi thì.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP22-04',
    prompt: 'The teacher told us ______ quiet.',
    options: ['be', 'to be', 'being', 'that be'],
    answerIndex: 1,
    explain: 'Tường thuật câu mệnh lệnh: told + O + to V.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP22-05',
    prompt: 'He said, "I saw her yesterday." → He said he ______ her the day before.',
    options: ['saw', 'had seen', 'has seen', 'sees'],
    answerIndex: 1,
    explain: 'Quá khứ đơn → quá khứ hoàn thành; yesterday → the day before.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP22-06',
    prompt: 'Nam asked Lan ______ she liked pop music.',
    options: ['that', 'if', 'what', 'which'],
    answerIndex: 1,
    explain: 'Tường thuật câu hỏi Yes/No dùng "if" hoặc "whether".',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP22-07',
    prompt: 'She said, "I am living here now." → She said she was living there ______.',
    options: ['now', 'then', 'today', 'tomorrow'],
    answerIndex: 1,
    explain: 'Trạng ngữ đổi: now → then, here → there.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP22-08',
    prompt: 'My mother told me ______ too much time playing games.',
    options: ['not spend', 'not to spend', "don't spend", 'to not spend'],
    answerIndex: 1,
    explain: 'Mệnh lệnh phủ định: told + O + NOT + to V (not đứng trước "to").',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-23 · Động từ khuyết thiếu ====================
  {
    id: 'GX-NP23-01',
    prompt: 'You ______ wear a helmet when riding a motorbike. It is the law.',
    options: ['can', 'must', 'may', 'might'],
    answerIndex: 1,
    explain: '"must" chỉ nghĩa vụ bắt buộc theo quy định.',
    topicIds: ['NP-23', 'TV-09'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP23-02',
    prompt: 'You ______ be tired after such a long trip.',
    options: ['must', 'can', 'should', 'need'],
    answerIndex: 0,
    explain: '"must" còn dùng để SUY ĐOÁN chắc chắn: hẳn là, chắc chắn là.',
    topicIds: ['NP-23'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP23-03',
    prompt: 'You ______ eat so much candy — it is bad for your teeth.',
    options: ["shouldn't", "couldn't", "mustn't be", "don't should"],
    answerIndex: 0,
    explain: '"shouldn\'t" đưa lời khuyên không nên làm gì.',
    topicIds: ['NP-23', 'TV-10'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP23-04',
    prompt: 'It is Sunday, so you ______ get up early.',
    options: ["mustn't", "don't have to", 'must not', "shouldn't have"],
    answerIndex: 1,
    explain:
      'Bẫy kinh điển: "mustn\'t" = CẤM; "don\'t have to" = không cần thiết. Ngữ cảnh này là không cần.',
    topicIds: ['NP-23'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP23-05',
    prompt: '______ you speak French? — Yes, a little.',
    options: ['Must', 'Can', 'Should', 'Need'],
    answerIndex: 1,
    explain: '"can" diễn tả khả năng làm được việc gì.',
    topicIds: ['NP-23'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP23-06',
    prompt: 'Students ______ not use mobile phones during the exam.',
    options: ['may', 'must', 'can be', 'have'],
    answerIndex: 1,
    explain: '"must not" = cấm tuyệt đối.',
    topicIds: ['NP-23'],
    skillId: 'KN-03',
  },

  // ==================== NP-24 · Danh động từ & động từ nguyên thể ====================
  {
    id: 'GX-NP24-01',
    prompt: 'I enjoy ______ books in my free time.',
    options: ['read', 'to read', 'reading', 'reads'],
    answerIndex: 2,
    explain: 'Sau "enjoy" luôn là V-ing.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP24-02',
    prompt: 'She decided ______ abroad next year.',
    options: ['study', 'to study', 'studying', 'studies'],
    answerIndex: 1,
    explain: 'Sau "decide" là to + V.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP24-03',
    prompt: 'Would you mind ______ the window?',
    options: ['open', 'to open', 'opening', 'opened'],
    answerIndex: 2,
    explain: 'Sau "mind" luôn là V-ing.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP24-04',
    prompt: 'He promised ______ me with my homework.',
    options: ['help', 'to help', 'helping', 'helped'],
    answerIndex: 1,
    explain: 'Sau "promise" là to + V.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP24-05',
    prompt: 'I remember ______ this film when I was a child.',
    options: ['to watch', 'watching', 'watch', 'watched'],
    answerIndex: 1,
    explain:
      '"remember + V-ing" = nhớ việc ĐÃ làm; "remember + to V" = nhớ PHẢI làm. Ngữ cảnh nói về quá khứ ⇒ V-ing.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP24-06',
    prompt: 'Don\'t forget ______ the door before you leave.',
    options: ['locking', 'to lock', 'lock', 'locked'],
    answerIndex: 1,
    explain: '"forget + to V" = quên PHẢI làm việc gì (việc chưa làm).',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP24-07',
    prompt: 'She stopped ______ because her throat hurt.',
    options: ['to sing', 'singing', 'sing', 'sang'],
    answerIndex: 1,
    explain:
      '"stop + V-ing" = dừng hẳn việc đang làm; "stop + to V" = dừng lại ĐỂ làm việc khác.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
    challenging: true,
  },
]
