import type { Question } from '../../types/domain'

/**
 * ND-02 · Bổ sung ngân hàng câu hỏi ngữ pháp — đợt 1: NP-01 → NP-12.
 *
 * Trước bản này, 28/36 chủ điểm chỉ có đúng 3 câu, khiến học sinh thuộc lòng
 * đáp án sau 2 lượt luyện và điểm mastery đo trí nhớ thay vì năng lực. Mục
 * tiêu: tối thiểu 8 câu/chủ điểm, 10 câu cho các chủ điểm hay ra, 12 câu cho
 * nhóm ra nhiều nhất (các thì, so sánh, bị động, tường thuật, mệnh đề quan hệ).
 *
 * Mỗi chủ điểm có ít nhất 2 câu gắn `challenging: true` — bẫy quen thuộc
 * trong đề CLC, không chỉ câu nhận biết công thức.
 */
export const grammarExtra1: Question[] = [
  // ==================== NP-01 · Danh từ số ít/nhiều, đếm được ====================
  {
    id: 'GX-NP01-01',
    prompt: 'There are three ______ on the table.',
    options: ['knifes', 'knives', 'knife', 'knive'],
    answerIndex: 1,
    explain: 'Danh từ tận cùng -f/-fe đổi thành -ves ở số nhiều: knife → knives.',
    topicIds: ['NP-01'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP01-02',
    prompt: 'My mother bought two ______ of bread this morning.',
    options: ['loafs', 'loaves', 'loaf', 'breads'],
    answerIndex: 1,
    explain:
      '"bread" không đếm được nên phải dùng đơn vị đo: a loaf of bread → two loaves of bread.',
    topicIds: ['NP-01'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP01-03',
    prompt: 'How many ______ are there in your class?',
    options: ['child', 'childs', 'children', 'childrens'],
    answerIndex: 2,
    explain: 'child → children là số nhiều bất quy tắc, KHÔNG thêm -s nữa.',
    topicIds: ['NP-01'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP01-04',
    prompt: 'The news about the storm ______ very worrying.',
    options: ['are', 'is', 'were', 'have'],
    answerIndex: 1,
    explain:
      '"news" trông như số nhiều nhưng là danh từ KHÔNG đếm được, luôn chia động từ số ít.',
    topicIds: ['NP-01', 'NP-30'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP01-05',
    prompt: 'I need to buy some ______ for the new school year.',
    options: ['stationeries', 'stationery', 'a stationery', 'stationerys'],
    answerIndex: 1,
    explain: '"stationery" (văn phòng phẩm) là danh từ không đếm được, không thêm -s.',
    topicIds: ['NP-01', 'TV-02'],
    skillId: 'KN-03',
  },

  // ==================== NP-02 · Mạo từ a/an/the ====================
  {
    id: 'GX-NP02-01',
    prompt: 'My brother wants to be ______ engineer when he grows up.',
    options: ['a', 'an', 'the', '(no article)'],
    answerIndex: 1,
    explain: '"engineer" bắt đầu bằng ÂM nguyên âm /e/ nên dùng "an".',
    topicIds: ['NP-02', 'TV-08'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP02-02',
    prompt: 'She has been learning English for ______ hour.',
    options: ['a', 'an', 'the', '(no article)'],
    answerIndex: 1,
    explain:
      '"hour" viết bằng phụ âm h nhưng h CÂM, đọc là /aʊə/ ⇒ dùng "an". Mạo từ theo ÂM, không theo chữ.',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP02-03',
    prompt: 'He is ______ university student in Ha Noi.',
    options: ['an', 'a', 'the', '(no article)'],
    answerIndex: 1,
    explain:
      '"university" bắt đầu bằng âm /juː/ — âm phụ âm ⇒ dùng "a", dù chữ cái đầu là nguyên âm u.',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP02-04',
    prompt: '______ sun rises in the east.',
    options: ['A', 'An', 'The', '(no article)'],
    answerIndex: 2,
    explain: 'Vật duy nhất trên đời (the sun, the moon, the earth) luôn dùng "the".',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP02-05',
    prompt: 'My sister goes to ______ school by bicycle every day.',
    options: ['a', 'the', '(no article)', 'an'],
    answerIndex: 2,
    explain:
      'go to school/bed/work với nghĩa MỤC ĐÍCH (đi học) thì không dùng mạo từ. "go to the school" là đi tới tòa nhà trường.',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP02-06',
    prompt: 'I saw a cat in the garden. ______ cat was black and white.',
    options: ['A', 'An', 'The', '(no article)'],
    answerIndex: 2,
    explain: 'Nhắc lại danh từ đã được nói tới ở câu trước ⇒ dùng "the".',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP02-07',
    prompt: 'Ha Long Bay is one of ______ most beautiful places in Viet Nam.',
    options: ['a', 'an', 'the', '(no article)'],
    answerIndex: 2,
    explain: 'Trước so sánh nhất luôn có "the": the most beautiful.',
    topicIds: ['NP-02', 'NP-06'],
    skillId: 'KN-03',
  },

  // ==================== NP-04 · Đại từ bất định, quan hệ cơ bản ====================
  {
    id: 'GX-NP04-01',
    prompt: '______ in my class likes the new English teacher.',
    options: ['Everyone', 'Every', 'All', 'Someone'],
    answerIndex: 0,
    explain: '"Everyone" đứng một mình làm chủ ngữ; "Every" luôn phải đi kèm danh từ.',
    topicIds: ['NP-04'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP04-02',
    prompt: 'I looked everywhere but I could not find ______.',
    options: ['something', 'anything', 'nothing', 'everything'],
    answerIndex: 1,
    explain:
      'Câu đã có "not" phủ định ⇒ dùng "anything". Dùng "nothing" sẽ thành phủ định hai lần.',
    topicIds: ['NP-04'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP04-03',
    prompt: 'Would you like ______ to drink?',
    options: ['anything', 'something', 'nothing', 'everything'],
    answerIndex: 1,
    explain:
      'Câu hỏi MỜI hoặc ĐỀ NGHỊ vẫn dùng "something" dù ở dạng nghi vấn — ngoại lệ cần nhớ.',
    topicIds: ['NP-04'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP04-04',
    prompt: '______ was at home when the postman came.',
    options: ['Anyone', 'Nobody', 'Not anybody', 'Someone not'],
    answerIndex: 1,
    explain:
      '"Nobody" mang nghĩa phủ định và làm chủ ngữ được; động từ vẫn chia khẳng định (was).',
    topicIds: ['NP-04'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP04-05',
    prompt: 'Everything in the shop ______ very expensive.',
    options: ['are', 'is', 'were', 'have been'],
    answerIndex: 1,
    explain: 'Everything/everyone/nobody/something luôn chia động từ SỐ ÍT.',
    topicIds: ['NP-04', 'NP-30'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-05 · Tính từ: thứ tự, -ed/-ing ====================
  {
    id: 'GX-NP05-01',
    prompt: 'The film was so ______ that I fell asleep.',
    options: ['bored', 'boring', 'bore', 'boredom'],
    answerIndex: 1,
    explain:
      'Đuôi -ing tả TÍNH CHẤT của sự vật (bộ phim gây chán), đuôi -ed tả CẢM XÚC của người.',
    topicIds: ['NP-05'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP05-02',
    prompt: 'I was very ______ when I heard the good news.',
    options: ['exciting', 'excited', 'excite', 'excitement'],
    answerIndex: 1,
    explain: 'Chủ ngữ là NGƯỜI cảm thấy ⇒ tính từ đuôi -ed: excited.',
    topicIds: ['NP-05'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP05-03',
    prompt: 'She bought a ______ dress yesterday.',
    options: ['silk long beautiful', 'beautiful long silk', 'long beautiful silk', 'silk beautiful long'],
    answerIndex: 1,
    explain:
      'Thứ tự tính từ: Ý kiến (beautiful) → Kích thước (long) → Chất liệu (silk) + danh từ.',
    topicIds: ['NP-05'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP05-04',
    prompt: 'My grandmother lives in a ______ house near the river.',
    options: ['small old wooden', 'wooden old small', 'old wooden small', 'small wooden old'],
    answerIndex: 0,
    explain: 'Thứ tự: Kích thước (small) → Tuổi (old) → Chất liệu (wooden).',
    topicIds: ['NP-05', 'TV-03'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP05-05',
    prompt: 'The students were ______ about the results of the competition.',
    options: ['surprising', 'surprised', 'surprise', 'surprisingly'],
    answerIndex: 1,
    explain: 'Người nhận cảm xúc ⇒ đuôi -ed. "be surprised about/at something".',
    topicIds: ['NP-05'],
    skillId: 'KN-03',
  },

  // ==================== NP-06 · So sánh (ưu tiên 1 — 12 câu) ====================
  {
    id: 'GX-NP06-01',
    prompt: 'This exercise is ______ than the one we did yesterday.',
    options: ['more easy', 'easier', 'easiest', 'as easy'],
    answerIndex: 1,
    explain: 'Tính từ 2 âm tiết tận cùng -y đổi y → i + er: easy → easier.',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-02',
    prompt: 'Nam runs ______ than any other boy in his class.',
    options: ['fastly', 'more fast', 'faster', 'fastest'],
    answerIndex: 2,
    explain: '"fast" vừa là tính từ vừa là trạng từ, so sánh hơn là "faster" (không có "fastly").',
    topicIds: ['NP-06', 'NP-07'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-03',
    prompt: 'Of the three sisters, Lan is ______.',
    options: ['the youngest', 'younger', 'the younger', 'youngest'],
    answerIndex: 0,
    explain: 'So sánh từ 3 đối tượng trở lên ⇒ so sánh nhất, có "the": the youngest.',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-04',
    prompt: 'My new phone is ______ expensive as my old one.',
    options: ['so', 'as', 'more', 'the same'],
    answerIndex: 1,
    explain: 'So sánh bằng: as + adj + as.',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-05',
    prompt: 'This is ______ book I have ever read.',
    options: ['the good', 'better', 'the best', 'the goodest'],
    answerIndex: 2,
    explain:
      'good → better → the best (bất quy tắc). Cấu trúc "the + so sánh nhất + I have ever + V3" rất hay ra trong đề.',
    topicIds: ['NP-06', 'NP-15'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP06-06',
    prompt: 'The more you practise, ______ you will become.',
    options: ['the better', 'better', 'the best', 'the more good'],
    answerIndex: 0,
    explain:
      'Cấu trúc so sánh kép "The + comparative..., the + comparative...": càng... càng... Cả hai vế đều phải có "the".',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP06-07',
    prompt: 'Hoa sings ______ beautifully than her sister.',
    options: ['more', 'much', 'most', 'very'],
    answerIndex: 0,
    explain: 'Trạng từ dài (beautifully) tạo so sánh hơn bằng "more + adv + than".',
    topicIds: ['NP-06', 'NP-07'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-08',
    prompt: 'Today is ______ hotter than yesterday.',
    options: ['very', 'much', 'more', 'so'],
    answerIndex: 1,
    explain:
      'Nhấn mạnh so sánh hơn dùng much/far/a lot, KHÔNG dùng "very": much hotter ✅ · very hotter ❌',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP06-09',
    prompt: 'This road is not as ______ as that one.',
    options: ['narrower', 'narrowest', 'narrow', 'more narrow',],
    answerIndex: 2,
    explain: 'Giữa "as ... as" luôn là tính từ NGUYÊN GỐC, không phải dạng so sánh.',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP06-10',
    prompt: 'Mount Fansipan is the ______ mountain in Viet Nam.',
    options: ['higher', 'highest', 'high', 'more high'],
    answerIndex: 1,
    explain: 'So sánh nhất trong một phạm vi (in Viet Nam) ⇒ the highest.',
    topicIds: ['NP-06', 'TV-05'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-11',
    prompt: 'Her handwriting is ______ than mine.',
    options: ['badder', 'worse', 'worst', 'more bad'],
    answerIndex: 1,
    explain: 'bad → worse → the worst (bất quy tắc).',
    topicIds: ['NP-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP06-12',
    prompt: 'The weather this week is getting ______.',
    options: ['colder and colder', 'more and more cold', 'coldest and coldest', 'cold and cold'],
    answerIndex: 0,
    explain:
      'Diễn tả mức độ tăng dần: "adj-er and adj-er" với tính từ ngắn, "more and more + adj" với tính từ dài.',
    topicIds: ['NP-06', 'TV-06'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-07 · Trạng từ tần suất, cách thức ====================
  {
    id: 'GX-NP07-01',
    prompt: 'My father ______ goes to work by car.',
    options: ['usual', 'usually', 'is usually', 'usualy'],
    answerIndex: 1,
    explain: 'Trạng từ tần suất đứng TRƯỚC động từ thường: usually goes.',
    topicIds: ['NP-07'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP07-02',
    prompt: 'Lan is ______ late for school.',
    options: ['never', 'never is', 'not never', 'nevers'],
    answerIndex: 0,
    explain: 'Trạng từ tần suất đứng SAU động từ "to be": is never late.',
    topicIds: ['NP-07'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP07-03',
    prompt: 'The children played ______ in the garden.',
    options: ['happy', 'happily', 'happyly', 'more happy'],
    answerIndex: 1,
    explain: 'Bổ nghĩa cho ĐỘNG TỪ (played) ⇒ trạng từ: happy → happily (y → i + ly).',
    topicIds: ['NP-07'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP07-04',
    prompt: 'She works very ______, so her boss likes her.',
    options: ['hardly', 'hard', 'hardy', 'harder'],
    answerIndex: 1,
    explain:
      'Bẫy kinh điển: "hard" = chăm chỉ; "hardly" = hầu như không. Nghĩa câu là chăm chỉ ⇒ "hard".',
    topicIds: ['NP-07'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP07-05',
    prompt: 'How ______ do you visit your grandparents? — Twice a month.',
    options: ['much', 'many', 'often', 'long'],
    answerIndex: 2,
    explain: 'Hỏi tần suất dùng "How often"; câu trả lời "twice a month" là dấu hiệu rõ.',
    topicIds: ['NP-07', 'NP-17'],
    skillId: 'KN-03',
  },

  // ==================== NP-08 · Giới từ thời gian, nơi chốn ====================
  {
    id: 'GX-NP08-01',
    prompt: 'My birthday is ______ the 15th of May.',
    options: ['in', 'at', 'on', 'to'],
    answerIndex: 2,
    explain: 'Giới từ chỉ NGÀY cụ thể dùng "on".',
    topicIds: ['NP-08'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP08-02',
    prompt: 'We usually have dinner ______ 7 p.m.',
    options: ['in', 'on', 'at', 'from'],
    answerIndex: 2,
    explain: 'Giờ cụ thể dùng "at": at 7 p.m.',
    topicIds: ['NP-08'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP08-03',
    prompt: 'It often rains a lot ______ August in Ha Noi.',
    options: ['on', 'at', 'in', 'to'],
    answerIndex: 2,
    explain: 'Tháng, năm, mùa dùng "in": in August.',
    topicIds: ['NP-08', 'TV-06'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP08-04',
    prompt: 'The picture is hanging ______ the wall.',
    options: ['in', 'on', 'at', 'above'],
    answerIndex: 1,
    explain: 'Tiếp xúc bề mặt dùng "on": on the wall, on the floor.',
    topicIds: ['NP-08', 'TV-03'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP08-05',
    prompt: 'I will wait for you ______ the bus stop.',
    options: ['in', 'on', 'at', 'into'],
    answerIndex: 2,
    explain: 'Một ĐIỂM trong không gian (bus stop, school gate) dùng "at".',
    topicIds: ['NP-08', 'TV-09'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP08-06',
    prompt: 'She has lived in this town ______ 2019.',
    options: ['for', 'since', 'from', 'in'],
    answerIndex: 1,
    explain: '"since" + MỐC thời gian (2019); "for" + KHOẢNG thời gian (three years).',
    topicIds: ['NP-08', 'NP-15'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP08-07',
    prompt: 'The library is ______ the post office and the bank.',
    options: ['among', 'between', 'in', 'next'],
    answerIndex: 1,
    explain: '"between" dùng cho HAI đối tượng; "among" dùng cho từ ba trở lên.',
    topicIds: ['NP-08', 'TV-09'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-09 · Liên từ ====================
  {
    id: 'GX-NP09-01',
    prompt: 'I wanted to go swimming, ______ the pool was closed.',
    options: ['and', 'but', 'so', 'because'],
    answerIndex: 1,
    explain: 'Hai vế TƯƠNG PHẢN (muốn đi bơi ↔ bể đóng cửa) ⇒ "but".',
    topicIds: ['NP-09'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP09-02',
    prompt: 'It was raining heavily, ______ we stayed at home.',
    options: ['because', 'although', 'so', 'but'],
    answerIndex: 2,
    explain: 'Vế sau là KẾT QUẢ ⇒ "so". Nếu là "because" thì phải đảo trật tự hai vế.',
    topicIds: ['NP-09'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP09-03',
    prompt: '______ he was very tired, he still helped his mother cook dinner.',
    options: ['Because', 'Although', 'So', 'Therefore'],
    answerIndex: 1,
    explain: 'Hai vế trái ngược ⇒ "Although + S + V".',
    topicIds: ['NP-09', 'NP-19'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP09-04',
    prompt: 'We turn off the lights ______ save electricity.',
    options: ['so that', 'in order to', 'because of', 'so'],
    answerIndex: 1,
    explain:
      'Chỉ mục đích + ĐỘNG TỪ nguyên thể dùng "in order to / so as to". "so that" phải đi với cả mệnh đề S + V.',
    topicIds: ['NP-09', 'TV-13'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP09-05',
    prompt: 'The match was cancelled ______ the bad weather.',
    options: ['because', 'although', 'because of', 'so'],
    answerIndex: 2,
    explain: '"because of" + CỤM DANH TỪ (the bad weather); "because" + mệnh đề S + V.',
    topicIds: ['NP-09'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-10 · Từ định lượng ====================
  {
    id: 'GX-NP10-01',
    prompt: 'There isn\'t ______ milk left in the fridge.',
    options: ['many', 'much', 'a few', 'few'],
    answerIndex: 1,
    explain: '"milk" không đếm được ⇒ dùng "much" trong câu phủ định.',
    topicIds: ['NP-10', 'TV-04'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP10-02',
    prompt: 'How ______ students are there in your school?',
    options: ['much', 'many', 'a lot of', 'little'],
    answerIndex: 1,
    explain: '"students" đếm được số nhiều ⇒ "How many".',
    topicIds: ['NP-10', 'TV-02'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP10-03',
    prompt: 'Would you like ______ more tea?',
    options: ['some', 'any', 'many', 'a few'],
    answerIndex: 0,
    explain: 'Câu hỏi mời/đề nghị dùng "some" thay vì "any".',
    topicIds: ['NP-10'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP10-04',
    prompt: 'She has ______ friends, so she often feels lonely.',
    options: ['a few', 'few', 'a little', 'little'],
    answerIndex: 1,
    explain:
      '"few" (không có mạo từ) mang nghĩa tiêu cực: rất ít, gần như không có. "a few" là "một vài" — nghĩa tích cực.',
    topicIds: ['NP-10'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP10-05',
    prompt: 'Don\'t worry, we still have ______ time before the train leaves.',
    options: ['a few', 'few', 'a little', 'little'],
    answerIndex: 2,
    explain: '"time" không đếm được + nghĩa tích cực (vẫn còn chút ít) ⇒ "a little".',
    topicIds: ['NP-10'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP10-06',
    prompt: 'There are ______ of interesting books in the school library.',
    options: ['much', 'many', 'lots', 'a lot'],
    answerIndex: 2,
    explain: 'Cấu trúc "lots of / a lot of + danh từ". "a lot" đứng một mình thì thiếu "of".',
    topicIds: ['NP-10', 'TV-02'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP10-07',
    prompt: 'I don\'t have ______ money to buy that game.',
    options: ['some', 'any', 'many', 'a few'],
    answerIndex: 1,
    explain: 'Câu phủ định dùng "any"; "money" không đếm được nên loại "many/a few".',
    topicIds: ['NP-10'],
    skillId: 'KN-03',
  },

  // ==================== NP-11 · Hiện tại đơn (ưu tiên 1 — 12 câu) ====================
  {
    id: 'GX-NP11-01',
    prompt: 'My sister ______ her homework every evening.',
    options: ['do', 'does', 'is doing', 'did'],
    answerIndex: 1,
    explain: '"every evening" ⇒ hiện tại đơn; chủ ngữ ngôi thứ ba số ít ⇒ does.',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP11-02',
    prompt: 'Water ______ at 100 degrees Celsius.',
    options: ['boil', 'boils', 'is boiling', 'boiled'],
    answerIndex: 1,
    explain: 'Sự thật hiển nhiên luôn dùng hiện tại đơn.',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP11-03',
    prompt: '______ your father work in a hospital?',
    options: ['Do', 'Does', 'Is', 'Did'],
    answerIndex: 1,
    explain: 'Chủ ngữ "your father" (ngôi 3 số ít) ⇒ trợ động từ "Does" + động từ nguyên thể.',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP11-04',
    prompt: 'Nam ______ like durian at all.',
    options: ["don't", "doesn't", "isn't", "didn't"],
    answerIndex: 1,
    explain: 'Phủ định hiện tại đơn với ngôi 3 số ít: doesn\'t + V nguyên thể.',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP11-05',
    prompt: 'She ______ English very well.',
    options: ['teachs', 'teaches', 'teach', 'teached'],
    answerIndex: 1,
    explain: 'Động từ tận cùng -ch thêm "-es": teach → teaches.',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP11-06',
    prompt: 'My brother ______ to school by bus, but today he is walking.',
    options: ['go', 'goes', 'is going', 'went'],
    answerIndex: 1,
    explain:
      'Vế đầu nói thói quen ⇒ hiện tại đơn "goes"; vế sau "today ... is walking" là ngoại lệ hôm nay.',
    topicIds: ['NP-11', 'NP-12'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP11-07',
    prompt: 'The train ______ at 6:30 every morning.',
    options: ['leave', 'leaves', 'is leaving', 'has left'],
    answerIndex: 1,
    explain: 'Lịch trình tàu xe cố định dùng hiện tại đơn, dù nói về tương lai.',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
    challenging: true,
  },

  // ==================== NP-12 · Hiện tại tiếp diễn ====================
  {
    id: 'GX-NP12-01',
    prompt: 'Look! The children ______ in the yard.',
    options: ['play', 'plays', 'are playing', 'played'],
    answerIndex: 2,
    explain: '"Look!" là dấu hiệu của hiện tại tiếp diễn — việc đang xảy ra ngay lúc nói.',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP12-02',
    prompt: 'Be quiet! The baby ______.',
    options: ['sleeps', 'is sleeping', 'slept', 'sleep'],
    answerIndex: 1,
    explain: 'Việc đang diễn ra tại thời điểm nói ⇒ hiện tại tiếp diễn.',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP12-03',
    prompt: 'She ______ a new dress at the moment.',
    options: ['wears', 'is wearing', 'wear', 'wore'],
    answerIndex: 1,
    explain: '"at the moment" là dấu hiệu hiện tại tiếp diễn.',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP12-04',
    prompt: 'I ______ the answer to this question.',
    options: ['am knowing', 'know', 'knows', 'am know'],
    answerIndex: 1,
    explain:
      'Động từ chỉ TRẠNG THÁI (know, like, want, need, understand) KHÔNG dùng ở tiếp diễn.',
    topicIds: ['NP-12', 'NP-11'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP12-05',
    prompt: 'They ______ to Da Nang next Sunday. The tickets are already booked.',
    options: ['fly', 'are flying', 'flew', 'have flown'],
    answerIndex: 1,
    explain:
      'Hiện tại tiếp diễn còn dùng cho KẾ HOẠCH tương lai gần đã sắp xếp chắc chắn (vé đã đặt).',
    topicIds: ['NP-12', 'NP-16'],
    skillId: 'KN-03',
    challenging: true,
  },
  {
    id: 'GX-NP12-06',
    prompt: 'My mother ______ dinner in the kitchen now.',
    options: ['cooks', 'cooking', 'is cooking', 'cook'],
    answerIndex: 2,
    explain: '"now" ⇒ hiện tại tiếp diễn: am/is/are + V-ing.',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  {
    id: 'GX-NP12-07',
    prompt: 'What ______ you ______ tonight?',
    options: ['do / do', 'are / doing', 'did / do', 'have / done'],
    answerIndex: 1,
    explain: 'Hỏi kế hoạch tối nay ⇒ "What are you doing tonight?"',
    topicIds: ['NP-12', 'NP-17'],
    skillId: 'KN-03',
  },
]
