import type { Question } from '../../types/domain'

// Ngân hàng câu hỏi, chia theo dạng bài KN-xx — Mục 4.3, 4.4 URD.
// Giai đoạn 1: 55 câu khởi động, biên soạn mới (không sao chép đề thi thật),
// phủ 6/7 dạng bài trắc nghiệm (KN-07 là WritingPrompt, không phải Question).
// KN-08 (Ngữ âm) ngoài phạm vi v1.0 — xem Mục 13.

// ---- KN-01: Đọc hiểu thông báo/tin nhắn/biển hiệu ngắn (7 câu) ----
const kn01: Question[] = [
  {
    id: 'KN01-01',
    prompt:
      'FOOTBALL CLUB\nNew members welcome!\nTime: Every Tuesday and Thursday, 4:30 pm – 5:30 pm\nPlace: School yard\nPlease bring water and sports shoes.\nContact Mr. Nam for more information.\n\nWhat should new members bring to the football club?',
    options: [
      'A football and a raincoat',
      'Water and sports shoes',
      'A pencil and a notebook',
      'Money and a ticket',
    ],
    answerIndex: 1,
    explain: 'Thông báo ghi rõ "Please bring water and sports shoes."',
    topicIds: ['TV-07', 'TV-02'],
    skillId: 'KN-01',
  },
  {
    id: 'KN01-02',
    prompt:
      'SCHOOL LIBRARY\nOpening hours: Monday – Friday, 7:30 am – 4:00 pm\nClosed on Saturday and Sunday\nPlease keep quiet and return books on time.\n\nWhen is the school library closed?',
    options: [
      'Monday and Tuesday',
      'Every afternoon',
      'Saturday and Sunday',
      'During lunch time',
    ],
    answerIndex: 2,
    explain: 'Biển thông báo ghi "Closed on Saturday and Sunday."',
    topicIds: ['TV-02'],
    skillId: 'KN-01',
  },
  {
    id: 'KN01-03',
    prompt:
      'Hi Nam, our English test is tomorrow, not today! Mr. Long changed the date. See you at school. — Duc\n\nWhat does Duc want to tell Nam?',
    options: [
      'The test date has changed',
      'The test is cancelled',
      'Mr. Long is absent',
      'School starts late tomorrow',
    ],
    answerIndex: 0,
    explain: 'Tin nhắn báo bài kiểm tra chuyển sang ngày mai, không phải hủy.',
    topicIds: ['TV-02', 'NP-13'],
    skillId: 'KN-01',
  },
  {
    id: 'KN01-04',
    prompt:
      'CITY PARK\nPlease do not ride bicycles on the grass.\nPlease put litter in the bin.\nDogs must be on a lead.\n\nAccording to the sign, what must dog owners do?',
    options: [
      'Keep their dogs at home',
      'Keep their dogs on a lead',
      'Give their dogs some food',
      'Let their dogs run freely',
    ],
    answerIndex: 1,
    explain: 'Biển báo ghi "Dogs must be on a lead."',
    topicIds: ['TV-13', 'NP-23'],
    skillId: 'KN-01',
  },
  {
    id: 'KN01-05',
    prompt:
      'CODING CLUB\nLearn to make your own computer game!\nEvery Friday, 3:00 pm, Computer Room\nBring your own laptop if you have one. Beginners are welcome.\n\nWhat will students do at the Coding Club?',
    options: [
      'Watch movies',
      'Learn to make computer games',
      'Play football',
      'Read story books',
    ],
    answerIndex: 1,
    explain: 'Thông báo ghi "Learn to make your own computer game!"',
    topicIds: ['TV-12', 'TV-02'],
    skillId: 'KN-01',
  },
  {
    id: 'KN01-06',
    prompt:
      'SCHOOL BUS TIMETABLE\nBus A: Leaves at 6:45 am\nBus B: Leaves at 7:00 am\nBus B is for students living near the lake.\n\nWhich bus should a student living near the lake take?',
    options: ['Bus A', 'Bus B', 'Both buses', 'Neither bus'],
    answerIndex: 1,
    explain: 'Bảng giờ ghi "Bus B is for students living near the lake."',
    topicIds: ['TV-09'],
    skillId: 'KN-01',
  },
  {
    id: 'KN01-07',
    prompt:
      'SCHOOL TRIP TO THE ZOO\nDate: Next Friday\nPlease bring the permission slip signed by your parents before Wednesday.\nCost: 50,000 VND (includes lunch).\n\nWhat do students need to do before Wednesday?',
    options: [
      'Pay for lunch at the zoo',
      'Bring a signed permission slip',
      'Buy a ticket at the zoo',
      "Ask their teacher for a map",
    ],
    answerIndex: 1,
    explain:
      'Thông báo yêu cầu nộp "permission slip signed by your parents before Wednesday."',
    topicIds: ['TV-05'],
    skillId: 'KN-01',
  },
]

// ---- KN-02: Đọc hiểu văn bản dài phi hư cấu (10 câu, gắn với 2 bài đọc RP-01, RP-02) ----
const kn02: Question[] = [
  {
    id: 'KN02-01',
    prompt: 'What is the passage "The Football Match" mainly about?',
    options: [
      'A football match between two classes',
      'A football lesson at school',
      'A birthday party at school',
      'A trip to a stadium',
    ],
    answerIndex: 0,
    explain: 'Cả bài kể về trận đấu bóng đá giữa lớp 5A và 5B.',
    topicIds: ['TV-07'],
    skillId: 'KN-02',
    passageId: 'RP-01',
  },
  {
    id: 'KN02-02',
    prompt: 'How many goals did Minh score in total?',
    options: ['1', '2', '3', '4'],
    answerIndex: 2,
    explain: 'Minh ghi 1 bàn rồi "two more goals" — tổng cộng 3 bàn.',
    topicIds: ['TV-07', 'NP-13'],
    skillId: 'KN-02',
    passageId: 'RP-01',
  },
  {
    id: 'KN02-03',
    prompt:
      'Why did the players of Class 5A feel worried in the first half?',
    options: [
      'Because it started to rain',
      'Because Class 5B scored two goals first',
      'Because their teacher was late',
      'Because Minh was injured',
    ],
    answerIndex: 1,
    explain: 'Bài đọc nêu "Class 5B scored two goals, so the players of Class 5A felt worried."',
    topicIds: ['TV-07'],
    skillId: 'KN-02',
    passageId: 'RP-01',
  },
  {
    id: 'KN02-04',
    prompt: 'In the passage, the word "cheered" is closest in meaning to ___.',
    options: ['cried sadly', 'shouted happily', 'ran away', 'fell asleep'],
    answerIndex: 1,
    explain: '"Cheered" nghĩa là hò reo, cổ vũ vui mừng.',
    topicIds: ['TV-07'],
    skillId: 'KN-02',
    passageId: 'RP-01',
  },
  {
    id: 'KN02-05',
    prompt:
      'In the sentence "his teammates cheered loudly and ran to hug him", who does "him" refer to?',
    options: [
      'Mr. Hung',
      'The goalkeeper of Class 5B',
      'Minh',
      'A player from Class 5B',
    ],
    answerIndex: 2,
    explain: '"Him" thay cho Minh, người vừa ghi bàn.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-01',
  },
  {
    id: 'KN02-06',
    prompt: 'What is the passage "Robots at School" mainly about?',
    options: [
      'How robots are made',
      'The use of robots to help students learn',
      'A robot that can drive a car',
      'A competition between robots and teachers',
    ],
    answerIndex: 1,
    explain: 'Bài đọc nói về việc robot hỗ trợ học sinh học tập.',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-02',
  },
  {
    id: 'KN02-07',
    prompt: 'What can Robi do during English lessons?',
    options: [
      'Cook food for students',
      'Ask questions and play word games',
      'Drive students to school',
      'Write reports for teachers',
    ],
    answerIndex: 1,
    explain: 'Bài đọc ghi "Robi can ask questions, play word games..."',
    topicIds: ['TV-12', 'NP-23'],
    skillId: 'KN-02',
    passageId: 'RP-02',
  },
  {
    id: 'KN02-08',
    prompt: 'Why do students love Robi?',
    options: [
      'Because it gives them presents',
      'Because it never gets angry and waits patiently',
      'Because it lets them skip homework',
      'Because it can fly',
    ],
    answerIndex: 1,
    explain:
      'Bài đọc nêu "Students love Robi because it never gets angry and it always waits patiently."',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-02',
  },
  {
    id: 'KN02-09',
    prompt: 'The word "patiently" in the passage is closest in meaning to ___.',
    options: [
      'quickly and angrily',
      'calmly, without complaining',
      'loudly and rudely',
      'secretly',
    ],
    answerIndex: 1,
    explain: '"Patiently" nghĩa là kiên nhẫn, bình tĩnh.',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-02',
  },
  {
    id: 'KN02-10',
    prompt:
      "According to the teachers, why can't robots replace humans completely?",
    options: [
      'Because robots are too expensive',
      "Because robots cannot understand students' feelings",
      'Because robots often break down',
      'Because robots do not like children',
    ],
    answerIndex: 1,
    explain:
      'Bài đọc nêu robot "cannot understand a student\'s feelings the way a real teacher can."',
    topicIds: ['TV-12', 'NP-11'],
    skillId: 'KN-02',
    passageId: 'RP-02',
  },
  // RP-03: A Weekend with Grandparents
  {
    id: 'KN02-11',
    prompt: 'What is the passage "A Weekend with Grandparents" mainly about?',
    options: [
      'A trip to the countryside to visit grandparents',
      'A fishing competition',
      'A cooking lesson',
      'A trip to a farm',
    ],
    answerIndex: 0,
    explain: 'Cả bài kể về chuyến thăm ông bà ở quê của Minh và em gái.',
    topicIds: ['TV-01'],
    skillId: 'KN-02',
    passageId: 'RP-03',
  },
  {
    id: 'KN02-12',
    prompt: 'What did Minh do by the river?',
    options: ['He swam', 'He caught fish', 'He read a book', 'He planted rice'],
    answerIndex: 1,
    explain: 'Bài đọc ghi "Minh caught two small fish."',
    topicIds: ['TV-01'],
    skillId: 'KN-02',
    passageId: 'RP-03',
  },
  {
    id: 'KN02-13',
    prompt: "Why did Minh's sister want to visit more often?",
    options: [
      'Because the food was free',
      'Because she loved spending time with her grandparents',
      'Because she wanted to fish',
      'Because she was bored at home',
    ],
    answerIndex: 1,
    explain: 'Bài đọc nêu cô bé muốn thăm ông bà thường xuyên hơn vì yêu quý thời gian bên ông bà.',
    topicIds: ['TV-01'],
    skillId: 'KN-02',
    passageId: 'RP-03',
  },
  {
    id: 'KN02-14',
    prompt: 'The word "proud" is closest in meaning to ___.',
    options: ['sad and tired', 'pleased with an achievement', 'angry and upset', 'confused'],
    answerIndex: 1,
    explain: '"Proud" nghĩa là tự hào, hài lòng về thành quả của mình.',
    topicIds: ['TV-01'],
    skillId: 'KN-02',
    passageId: 'RP-03',
  },
  {
    id: 'KN02-15',
    prompt: 'In "their grandmother gave them a bag of fresh vegetables", who does "them" refer to?',
    options: ['The neighbors', 'Minh and his sister', 'The grandparents', 'The fish'],
    answerIndex: 1,
    explain: '"Them" thay cho Minh và em gái, hai người vừa được nhắc tới.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-03',
  },
  // RP-04: Our School Sports Day
  {
    id: 'KN02-16',
    prompt: 'What is the passage "Our School Sports Day" mainly about?',
    options: ['A school sports event', 'A football match', 'A school exam', 'A class trip'],
    answerIndex: 0,
    explain: 'Cả bài mô tả ngày hội thể thao của trường.',
    topicIds: ['TV-02', 'TV-07'],
    skillId: 'KN-02',
    passageId: 'RP-04',
  },
  {
    id: 'KN02-17',
    prompt: 'What did Class 5B win?',
    options: ['A jumping competition', 'The relay race', 'A running race alone', 'A prize for best costume'],
    answerIndex: 1,
    explain: 'Bài đọc ghi lớp 5B đã thắng cuộc thi chạy tiếp sức.',
    topicIds: ['TV-02', 'TV-07'],
    skillId: 'KN-02',
    passageId: 'RP-04',
  },
  {
    id: 'KN02-18',
    prompt: 'Why did Nam feel very happy?',
    options: [
      "Because he didn't have to study",
      'Because it was the first time his class won a medal',
      'Because school ended early',
      'Because he received money',
    ],
    answerIndex: 1,
    explain: 'Bài đọc nêu đây là lần đầu tiên lớp của Nam giành huy chương.',
    topicIds: ['TV-02'],
    skillId: 'KN-02',
    passageId: 'RP-04',
  },
  {
    id: 'KN02-19',
    prompt: 'The word "cheered" is closest in meaning to ___.',
    options: ['shouted happily to support someone', 'cried loudly', 'ran quickly', 'fell asleep'],
    answerIndex: 0,
    explain: '"Cheered" nghĩa là hò reo cổ vũ.',
    topicIds: ['TV-07'],
    skillId: 'KN-02',
    passageId: 'RP-04',
  },
  {
    id: 'KN02-20',
    prompt: 'In "he ran extremely fast and helped his team finish first", who does "he" refer to?',
    options: ['The principal', 'Nam', 'A student from another class', 'The teacher'],
    answerIndex: 1,
    explain: '"He" thay cho Nam, người vừa được nhắc tới trước đó.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-04',
  },
  // RP-05: Vietnamese Street Food
  {
    id: 'KN02-21',
    prompt: 'What is the passage "Vietnamese Street Food" mainly about?',
    options: ['Vietnamese street food', 'A recipe for pho', 'How to open a restaurant', 'Tourist attractions in Vietnam'],
    answerIndex: 0,
    explain: 'Cả bài giới thiệu về các món ăn đường phố nổi tiếng của Việt Nam.',
    topicIds: ['TV-04'],
    skillId: 'KN-02',
    passageId: 'RP-05',
  },
  {
    id: 'KN02-22',
    prompt: 'Why do many people eat pho for breakfast?',
    options: ['Because it is cheap and fast', 'Because it is tasty and filling', 'Because it is sweet', 'Because it is served cold'],
    answerIndex: 1,
    explain: 'Bài đọc ghi phở "tasty and filling" (ngon và no bụng).',
    topicIds: ['TV-04'],
    skillId: 'KN-02',
    passageId: 'RP-05',
  },
  {
    id: 'KN02-23',
    prompt: 'What can we infer about Vietnamese food sellers?',
    options: [
      'They only work at night',
      'They work hard to prepare fresh food every day',
      "They don't use fresh ingredients",
      'They only sell one type of food',
    ],
    answerIndex: 1,
    explain: 'Bài đọc nêu người bán "start working early... and prepare fresh ingredients every day."',
    topicIds: ['TV-04'],
    skillId: 'KN-02',
    passageId: 'RP-05',
  },
  {
    id: 'KN02-24',
    prompt: 'The word "filling" in the passage is closest in meaning to ___.',
    options: ['making you feel hungry', 'making you feel full', 'tasting sour', 'looking colorful'],
    answerIndex: 1,
    explain: '"Filling" nghĩa là no bụng, đủ chất.',
    topicIds: ['TV-04'],
    skillId: 'KN-02',
    passageId: 'RP-05',
  },
  {
    id: 'KN02-25',
    prompt: 'In "Many families have their own recipes that have been passed down for generations", what does "their" refer to?',
    options: ['Tourists', 'Families', 'Food sellers only', 'Restaurants'],
    answerIndex: 1,
    explain: '"Their" thay cho "many families" đứng ngay trước.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-05',
  },
  // RP-06: A Day at the Zoo
  {
    id: 'KN02-26',
    prompt: 'What is the passage "A Day at the Zoo" mainly about?',
    options: ['A school trip to the zoo', 'A trip to the countryside', 'A biology lesson at school', 'A visit to a farm'],
    answerIndex: 0,
    explain: 'Cả bài kể về chuyến tham quan sở thú của lớp Lan.',
    topicIds: ['TV-05'],
    skillId: 'KN-02',
    passageId: 'RP-06',
  },
  {
    id: 'KN02-27',
    prompt: 'What were the tigers doing when the students visited?',
    options: ['Eating', 'Sleeping', 'Playing', 'Swimming'],
    answerIndex: 1,
    explain: 'Bài đọc ghi "the tigers were sleeping under a tree."',
    topicIds: ['TV-05'],
    skillId: 'KN-02',
    passageId: 'RP-06',
  },
  {
    id: 'KN02-28',
    prompt: 'Why did the teacher remind students not to feed the animals?',
    options: [
      'Because the animals were not hungry',
      'To help keep the animals healthy and safe',
      'Because it was against the rules of the school',
      'Because food was expensive',
    ],
    answerIndex: 1,
    explain: 'Việc không cho ăn giúp bảo vệ sức khỏe và sự an toàn cho động vật.',
    topicIds: ['TV-05'],
    skillId: 'KN-02',
    passageId: 'RP-06',
  },
  {
    id: 'KN02-29',
    prompt: 'The word "protects" in the passage is closest in meaning to ___.',
    options: ['sells', 'keeps safe', 'hunts', 'feeds'],
    answerIndex: 1,
    explain: '"Protects" nghĩa là bảo vệ, giữ an toàn.',
    topicIds: ['TV-05'],
    skillId: 'KN-02',
    passageId: 'RP-06',
  },
  {
    id: 'KN02-30',
    prompt: 'In "they were jumping and playing happily in their cage", who does "they" refer to?',
    options: ['The elephants', 'The tigers', 'The monkeys', 'The students'],
    answerIndex: 2,
    explain: '"They" thay cho "the monkeys", chủ đề của câu ngay trước đó.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-06',
  },
  // RP-07: Getting Around Ha Noi
  {
    id: 'KN02-31',
    prompt: 'What is the passage "Getting Around Ha Noi" mainly about?',
    options: ['Transportation in Ha Noi', 'The history of Ha Noi', 'Famous foods in Ha Noi', 'Schools in Ha Noi'],
    answerIndex: 0,
    explain: 'Cả bài mô tả các phương tiện di chuyển ở Hà Nội.',
    topicIds: ['TV-09'],
    skillId: 'KN-02',
    passageId: 'RP-07',
  },
  {
    id: 'KN02-32',
    prompt: 'Why do many people in Ha Noi use motorbikes?',
    options: [
      'Because they are cheap to buy',
      'Because they are fast and easy to park',
      'Because cars are not allowed',
      'Because buses are too slow',
    ],
    answerIndex: 1,
    explain: 'Bài đọc ghi xe máy "fast and easy to park."',
    topicIds: ['TV-09'],
    skillId: 'KN-02',
    passageId: 'RP-07',
  },
  {
    id: 'KN02-33',
    prompt: 'Why is the city building new train lines?',
    options: [
      'To reduce traffic and make travel easier',
      'Because motorbikes are dangerous',
      'Because buses will stop running',
      'To attract more tourists',
    ],
    answerIndex: 0,
    explain: 'Bài đọc nêu tàu điện giúp việc di chuyển "faster and more convenient".',
    topicIds: ['TV-09'],
    skillId: 'KN-02',
    passageId: 'RP-07',
  },
  {
    id: 'KN02-34',
    prompt: 'The word "crowded" in the passage is closest in meaning to ___.',
    options: ['empty and quiet', 'full of people', 'clean and new', 'far away'],
    answerIndex: 1,
    explain: '"Crowded" nghĩa là đông đúc, nhiều người/xe cộ.',
    topicIds: ['TV-09'],
    skillId: 'KN-02',
    passageId: 'RP-07',
  },
  {
    id: 'KN02-35',
    prompt: 'In "people usually walk slowly and let the traffic flow around them", what does "them" refer to?',
    options: ['The motorbikes', 'The people crossing the street', 'The buses', 'The tourists'],
    answerIndex: 1,
    explain: '"Them" thay cho "people" (người đi bộ qua đường) vừa nhắc tới.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-07',
  },
  // RP-08: The Robot Football Team
  {
    id: 'KN02-36',
    prompt: 'What is the passage "The Robot Football Team" mainly about?',
    options: [
      'A group of students who built football-playing robots',
      'A real football match',
      'A robot factory',
      'A computer game competition',
    ],
    answerIndex: 0,
    explain: 'Cả bài kể về nhóm học sinh chế tạo robot chơi bóng đá.',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-08',
  },
  {
    id: 'KN02-37',
    prompt: 'How long did the students spend building the robots?',
    options: ['Two months', 'Six months', 'One year', 'One week'],
    answerIndex: 1,
    explain: 'Bài đọc ghi các bạn học sinh "spent six months building and programming the robots."',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-08',
  },
  {
    id: 'KN02-38',
    prompt: 'What was the hardest part of the project, according to one student?',
    options: [
      "Building the robot's body",
      'Teaching the robots to find the ball by themselves',
      'Painting the robots',
      'Charging the batteries',
    ],
    answerIndex: 1,
    explain: 'Bài đọc ghi phần khó nhất là dạy robot tự tìm bóng.',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-08',
  },
  {
    id: 'KN02-39',
    prompt: 'The word "impressed" in the passage is closest in meaning to ___.',
    options: ['confused and worried', 'bored and tired', 'amazed and admiring', 'angry and upset'],
    answerIndex: 2,
    explain: '"Impressed" nghĩa là ấn tượng, thán phục.',
    topicIds: ['TV-12'],
    skillId: 'KN-02',
    passageId: 'RP-08',
  },
  {
    id: 'KN02-40',
    prompt: 'In "The team hopes to build an even smarter robot next year", who does "The team" refer to?',
    options: ['The visitors', 'The students who built the robots', "Another school's robots", 'The engineers'],
    answerIndex: 1,
    explain: '"The team" thay cho nhóm học sinh chế tạo robot được nhắc tới xuyên suốt bài.',
    topicIds: ['NP-03'],
    skillId: 'KN-02',
    passageId: 'RP-08',
  },
]

// ---- KN-03: Đọc và điền từ / hoàn thành đoạn tóm tắt (8 câu, cùng 1 đoạn văn) ----
// Mỗi câu hỏi hiện TOÀN BỘ đoạn văn (chỉ để trống đúng 1 từ đang kiểm tra),
// để tự đủ ngữ cảnh khi hiện riêng lẻ trong Luyện tập/Quiz nhanh/Thi thử —
// không phụ thuộc học sinh đã thấy các câu trước đó trong cùng bộ hay chưa.
// Đoạn gốc hoàn chỉnh: "Last Sunday, Tom and his father went to the Space
// Museum. They learned many interesting things about planets and rockets.
// Tom took a photo next to a real spacesuit. After that, they watched a
// short movie about astronauts. Tom's father bought him a toy rocket at the
// gift shop. On the way home, Tom said he wanted to be an astronaut when he
// grew up. He was very happy and could not stop talking about his trip."
const kn03: Question[] = [
  {
    id: 'KN03-01',
    prompt:
      "Last Sunday, Tom and his father _____ to the Space Museum. They learned many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he wanted to be an astronaut when he grew up. He was very happy and could not stop talking about his trip.",
    options: ['go', 'went', 'goes', 'going'],
    answerIndex: 1,
    explain: 'Chuyện xảy ra "last Sunday" (quá khứ) nên dùng quá khứ đơn "went".',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-02',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They _____ many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he wanted to be an astronaut when he grew up. He was very happy and could not stop talking about his trip.",
    options: ['learn', 'learned', 'learning', 'learns'],
    answerIndex: 1,
    explain: 'Cùng mốc thời gian quá khứ "last Sunday" với câu trước nên dùng "learned".',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-03',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They learned many interesting things about planets and rockets. Tom _____ a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he wanted to be an astronaut when he grew up. He was very happy and could not stop talking about his trip.",
    options: ['take', 'took', 'taken', 'takes'],
    answerIndex: 1,
    explain: 'Cả đoạn kể chuyện đã xảy ra "last Sunday"; "take" là động từ bất quy tắc, quá khứ đơn là "took".',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-04',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They learned many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they _____ a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he wanted to be an astronaut when he grew up. He was very happy and could not stop talking about his trip.",
    options: ['watch', 'watched', 'watching', 'watches'],
    answerIndex: 1,
    explain: 'Tiếp tục mạch quá khứ đơn của cả đoạn văn (chuyện xảy ra "last Sunday").',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-05',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They learned many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket _____ the gift shop. On the way home, Tom said he wanted to be an astronaut when he grew up. He was very happy and could not stop talking about his trip.",
    options: ['in', 'at', 'on', 'to'],
    answerIndex: 1,
    explain: 'Dùng giới từ "at" với địa điểm cụ thể như cửa hàng.',
    topicIds: ['NP-08'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-06',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They learned many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he _____ to be an astronaut when he grew up. He was very happy and could not stop talking about his trip.",
    options: ['want', 'wanted', 'wants', 'wanting'],
    answerIndex: 1,
    explain: 'Câu tường thuật lùi thì: "wants" trong câu gốc lùi thành "wanted" vì "said" ở quá khứ.',
    topicIds: ['NP-22'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-07',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They learned many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he wanted to be an astronaut when he _____ up. He was very happy and could not stop talking about his trip.",
    options: ['grow', 'grew', 'grows', 'growing'],
    answerIndex: 1,
    explain: 'Mệnh đề thời gian trong câu tường thuật quá khứ dùng "grew" (quá khứ đơn).',
    topicIds: ['NP-13'],
    skillId: 'KN-03',
  },
  {
    id: 'KN03-08',
    prompt:
      "Last Sunday, Tom and his father went to the Space Museum. They learned many interesting things about planets and rockets. Tom took a photo next to a real spacesuit. After that, they watched a short movie about astronauts. Tom's father bought him a toy rocket at the gift shop. On the way home, Tom said he wanted to be an astronaut when he grew up. He was very happy and could not stop talking _____ his trip.",
    options: ['about', 'of', 'for', 'with'],
    answerIndex: 0,
    explain: 'Cụm động từ đúng là "talk about something".',
    topicIds: ['NP-08'],
    skillId: 'KN-03',
  },
]

// ---- KN-04: Hoàn thành hội thoại & chức năng giao tiếp (10 câu) ----
const kn04: Question[] = [
  {
    id: 'KN04-01',
    prompt: "A: \"Would you like to come to my birthday party on Sunday?\"\nB: \"_____\"",
    options: [
      "Sure, I'd love to!",
      "No, I don't like parties.",
      "It's five o'clock.",
      "I'm sorry, that's expensive.",
    ],
    answerIndex: 0,
    explain: 'Lời mời cần được nhận lời hoặc từ chối phù hợp; "Sure, I\'d love to!" là phản hồi tự nhiên.',
    topicIds: ['NP-28', 'TV-01'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-02',
    prompt: 'A: "I\'m sorry I broke your pencil."\nB: "_____"',
    options: [
      "That's all right, don't worry.",
      "You're welcome.",
      'Nice to meet you.',
      'See you later.',
    ],
    answerIndex: 0,
    explain: 'Đáp lại lời xin lỗi bằng cách trấn an, bỏ qua.',
    topicIds: ['TV-02'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-03',
    prompt: 'A: "Excuse me, how can I get to the post office?"\nB: "_____"',
    options: [
      'Go straight and turn left.',
      "I'm from Vietnam.",
      "It's my favorite color.",
      'Yes, please.',
    ],
    answerIndex: 0,
    explain: 'Câu hỏi đường cần được trả lời bằng chỉ dẫn.',
    topicIds: ['TV-09'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-04',
    prompt: 'A: "Shall we play football after school?"\nB: "_____"',
    options: [
      'That sounds great!',
      "It's raining outside now.",
      "I don't have a pencil.",
      'He is my brother.',
    ],
    answerIndex: 0,
    explain: 'Lời rủ rê "Shall we...?" thường được đáp lại bằng sự đồng ý.',
    topicIds: ['TV-07'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-05',
    prompt: 'A: "Can I borrow your eraser, please?"\nB: "_____"',
    options: [
      'Sure, here you are.',
      "I'm sorry to hear that.",
      'Happy birthday!',
      "It's Monday today.",
    ],
    answerIndex: 0,
    explain: 'Lời đề nghị mượn đồ được đáp lại bằng sự đồng ý và đưa vật.',
    topicIds: ['TV-02'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-06',
    prompt: 'A: "What\'s the weather like today?"\nB: "_____"',
    options: [
      "It's sunny and warm.",
      "I'm nine years old.",
      "It's my pencil case.",
      'I like swimming.',
    ],
    answerIndex: 0,
    explain: 'Câu hỏi về thời tiết cần trả lời bằng mô tả thời tiết.',
    topicIds: ['TV-06'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-07',
    prompt: 'A: "Do you want some orange juice?"\nB: "_____"',
    options: [
      'Yes, please. Thank you.',
      "No, it's Tuesday.",
      "I'm from Ha Noi.",
      'He is tall.',
    ],
    answerIndex: 0,
    explain: 'Lời mời đồ uống được đáp lại bằng nhận hoặc từ chối lịch sự.',
    topicIds: ['TV-04'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-08',
    prompt: 'A: "I\'m going to the dentist tomorrow."\nB: "_____"',
    options: [
      'I hope everything goes well!',
      "That's a beautiful song.",
      "Let's play chess.",
      "It's under the table.",
    ],
    answerIndex: 0,
    explain: 'Đáp lại thông tin về việc khám răng bằng lời động viên.',
    topicIds: ['TV-10'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-09',
    prompt: 'A: "Congratulations on winning the match!"\nB: "_____"',
    options: [
      'Thank you very much!',
      "I'm sorry about that.",
      'Never mind.',
      "That's too bad.",
    ],
    answerIndex: 0,
    explain: 'Lời chúc mừng được đáp lại bằng lời cảm ơn.',
    topicIds: ['TV-07'],
    skillId: 'KN-04',
  },
  {
    id: 'KN04-10',
    prompt: 'A: "Could you help me carry these books, please?"\nB: "_____"',
    options: [
      'Of course, no problem.',
      "I don't like reading.",
      "It's very cold today.",
      'She is my teacher.',
    ],
    answerIndex: 0,
    explain: 'Lời nhờ giúp đỡ lịch sự được đáp lại bằng sự đồng ý giúp đỡ.',
    topicIds: ['TV-02'],
    skillId: 'KN-04',
  },
]

// ---- KN-05: Viết lại câu giữ nguyên nghĩa (10 câu, dạng chọn câu đồng nghĩa) ----
const kn05: Question[] = [
  {
    id: 'KN05-01',
    prompt:
      'Which sentence has the same meaning as "Nam is taller than Tuan"?',
    options: [
      'Tuan is taller than Nam.',
      'Tuan is shorter than Nam.',
      'Nam and Tuan are the same height.',
      'Tuan is as tall as Nam.',
    ],
    answerIndex: 1,
    explain: 'Nam cao hơn Tuấn tương đương với Tuấn thấp hơn Nam.',
    topicIds: ['NP-06'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-02',
    prompt:
      'Which sentence has the same meaning as "The cake is so delicious that everyone wants more"?',
    options: [
      'The cake is such delicious that everyone wants more.',
      'It is such a delicious cake that everyone wants more.',
      'The cake is too delicious for everyone to want more.',
      "The cake is delicious so everyone doesn't want more.",
    ],
    answerIndex: 1,
    explain: 'Cấu trúc "such a/an + adj + noun + that" tương đương "so + adj + that".',
    topicIds: ['NP-26'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-03',
    prompt:
      'Which sentence has the same meaning as "People grow rice in this field"?',
    options: [
      'Rice is grown in this field.',
      'Rice grows in this field by people.',
      'This field grows rice by people.',
      'Rice was grown in this field.',
    ],
    answerIndex: 0,
    explain: 'Chuyển sang câu bị động hiện tại đơn: "Rice is grown in this field."',
    topicIds: ['NP-21'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-04',
    prompt:
      'Which sentence has the same meaning as \'"I am reading a book," said Lan\'?',
    options: [
      'Lan said that she is reading a book.',
      'Lan said that she was reading a book.',
      'Lan says she read a book.',
      'Lan said I was reading a book.',
    ],
    answerIndex: 1,
    explain: 'Câu tường thuật lùi thì: hiện tại tiếp diễn → quá khứ tiếp diễn.',
    topicIds: ['NP-22'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-05',
    prompt:
      'Which sentence has the same meaning as "Minh has never been to Da Lat"?',
    options: [
      'It is the first time Minh has been to Da Lat.',
      'Minh went to Da Lat many times.',
      'Minh has been to Da Lat before.',
      "This is not Minh's first time in Da Lat.",
    ],
    answerIndex: 0,
    explain: '"Never been to" nghĩa là chưa từng đến — tương đương "lần đầu tiên".',
    topicIds: ['NP-15'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-06',
    prompt: 'Which sentence has the same meaning as "My mother is a good cook"?',
    options: [
      'My mother cooks good.',
      'My mother cooks well.',
      'My mother cooking is good.',
      'My mother good cooks.',
    ],
    answerIndex: 1,
    explain: 'Trạng từ cách thức đúng của "good" là "well".',
    topicIds: ['NP-07'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-07',
    prompt:
      'Which sentence has the same meaning as "This box is too heavy for me to lift"?',
    options: [
      "This box is so heavy that I can't lift it.",
      'This box is heavy enough for me to lift.',
      'This box is not heavy, so I can lift it.',
      'I can lift this box easily.',
    ],
    answerIndex: 0,
    explain: '"too...to" tương đương "so...that...can\'t".',
    topicIds: ['NP-26'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-08',
    prompt:
      'Which sentence has the same meaning as "If it rains, we will stay at home"?',
    options: [
      'We will stay at home only if it rains.',
      'We stayed at home because it rained.',
      "We will go out if it doesn't rain.",
      'It rained, so we stayed at home.',
    ],
    answerIndex: 0,
    explain: 'Giữ nguyên câu điều kiện loại 1, chỉ diễn đạt lại bằng "only if".',
    topicIds: ['NP-20'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-09',
    prompt:
      'Which sentence has the same meaning as "Lan can speak English very well"?',
    options: [
      'Lan is good at speaking English.',
      'Lan speaks English badly.',
      "Lan can't speak English.",
      'Lan wants to speak English.',
    ],
    answerIndex: 0,
    explain: '"Can speak very well" tương đương "is good at speaking".',
    topicIds: ['NP-23'],
    skillId: 'KN-05',
  },
  {
    id: 'KN05-10',
    prompt:
      'Which sentence has the same meaning as "It took Nam two hours to finish his homework"?',
    options: [
      'Nam finished his homework in two hours.',
      'Nam took two hours from his homework.',
      "Nam's homework took two hours away.",
      'Nam needed two hours to start his homework.',
    ],
    answerIndex: 0,
    explain: '"It takes sb time to do sth" tương đương "sb do sth in + time".',
    topicIds: ['NP-25'],
    skillId: 'KN-05',
  },
]

// ---- KN-06: Tìm và sửa lỗi sai trong câu (10 câu, dạng chọn câu đúng) ----
const kn06: Question[] = [
  {
    id: 'KN06-01',
    prompt: 'Which sentence is correct?',
    options: [
      "She don't like ice cream.",
      "She doesn't likes ice cream.",
      "She doesn't like ice cream.",
      'She not like ice cream.',
    ],
    answerIndex: 2,
    explain: 'Hiện tại đơn phủ định với chủ ngữ số ít: "doesn\'t + V-inf".',
    topicIds: ['NP-11'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-02',
    prompt: 'Which sentence is correct?',
    options: [
      'They was playing football yesterday.',
      'They were playing football yesterday.',
      'They is playing football yesterday.',
      'They playing football yesterday.',
    ],
    answerIndex: 1,
    explain: 'Chủ ngữ số nhiều "they" dùng "were" trong quá khứ tiếp diễn.',
    topicIds: ['NP-14'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-03',
    prompt: 'Which sentence is correct?',
    options: [
      'I have live here since 2018.',
      'I have lived here since 2018.',
      'I lived here since 2018.',
      'I am living here since 2018.',
    ],
    answerIndex: 1,
    explain: 'Hiện tại hoàn thành với "since" cần "have/has + V3/-ed".',
    topicIds: ['NP-15'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-04',
    prompt: 'Which sentence is correct?',
    options: [
      'There is many books on the table.',
      'There are many book on the table.',
      'There are many books on the table.',
      'There is many book on the table.',
    ],
    answerIndex: 2,
    explain: '"Many" đi với danh từ đếm được số nhiều và "there are".',
    topicIds: ['NP-01'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-05',
    prompt: 'Which sentence is correct?',
    options: [
      'My father go to work by bus every day.',
      'My father goes to work by bus every day.',
      'My father going to work by bus every day.',
      'My father is go to work by bus every day.',
    ],
    answerIndex: 1,
    explain: 'Chủ ngữ số ít "my father" cần thêm "-es": "goes".',
    topicIds: ['NP-11'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-06',
    prompt: 'Which sentence is correct?',
    options: [
      'This book is more interesting than that one.',
      'This book is more interesting as that one.',
      'This book is interesting more than that one.',
      'This book is most interesting than that one.',
    ],
    answerIndex: 0,
    explain: 'So sánh hơn dùng "more + adj + than".',
    topicIds: ['NP-06'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-07',
    prompt: 'Which sentence is correct?',
    options: [
      'You should to finish your homework first.',
      'You should finishing your homework first.',
      'You should finish your homework first.',
      'You should finishes your homework first.',
    ],
    answerIndex: 2,
    explain: 'Động từ khuyết thiếu "should" theo sau bởi động từ nguyên mẫu không "to".',
    topicIds: ['NP-23'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-08',
    prompt: 'Which sentence is correct?',
    options: [
      'The letter was write by my sister.',
      'The letter was written by my sister.',
      'The letter was wrote by my sister.',
      'The letter is written by my sister yesterday.',
    ],
    answerIndex: 1,
    explain: 'Câu bị động quá khứ đơn: "was/were + V3 (past participle)".',
    topicIds: ['NP-21'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-09',
    prompt: 'Which sentence is correct?',
    options: [
      'He asked me where I lived.',
      'He asked me where did I live.',
      'He asked me where I live.',
      'He asked me where do I live.',
    ],
    answerIndex: 0,
    explain: 'Câu hỏi gián tiếp giữ trật tự từ như câu kể, không đảo động từ, và lùi thì.',
    topicIds: ['NP-22'],
    skillId: 'KN-06',
  },
  {
    id: 'KN06-10',
    prompt: 'Which sentence is correct?',
    options: [
      'I look forward to seeing you soon.',
      'I look forward to see you soon.',
      'I look forward seeing you soon.',
      'I look forward to seen you soon.',
    ],
    answerIndex: 0,
    explain: 'Cụm "look forward to" theo sau là V-ing.',
    topicIds: ['NP-25'],
    skillId: 'KN-06',
  },
]

// ---- Quiz nhanh cuối bài học lý thuyết (FR-L03), Nhóm B — Thì động từ ----
// Ngân hàng KN-01..06 ở trên chưa đủ 3–5 câu/thì cho tất cả NP-11..16 (một số
// thì chỉ xuất hiện lồng ghép trong bài đọc/hội thoại). Bổ sung câu hỏi luyện
// tập trực tiếp từng thì để FR-L03 có đủ dữ liệu cho cả 6 chủ điểm Nhóm B.
const lessonQuiz: Question[] = [
  // NP-11: Hiện tại đơn (bổ sung 2 câu, đã có 3 câu trong KN-06/KN-02)
  {
    id: 'LQ-NP11-01',
    prompt: 'Which sentence is correct?',
    options: [
      'The sun rise in the east.',
      'The sun rises in the east.',
      'The sun rising in the east.',
      'The sun rised in the east.',
    ],
    answerIndex: 1,
    explain: 'Chủ ngữ số ít "the sun" cần động từ thêm "-s": "rises".',
    topicIds: ['NP-11'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP11-02',
    prompt:
      'Every morning, my sister _____ (brush) her teeth before breakfast.',
    options: ['brush', 'brushes', 'brushing', 'brushed'],
    answerIndex: 1,
    explain: 'Chủ ngữ số ít "my sister" cần động từ thêm "-es": "brushes".',
    topicIds: ['NP-11'],
    skillId: 'KN-03',
  },
  // NP-12: Hiện tại tiếp diễn (5 câu mới)
  {
    id: 'LQ-NP12-01',
    prompt: 'Look! The children _____ in the yard now.',
    options: ['play', 'plays', 'are playing', 'played'],
    answerIndex: 2,
    explain: '"Look!" + "now" báo hiệu hành động đang diễn ra: "are playing".',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP12-02',
    prompt: 'Which sentence is correct?',
    options: [
      'She is cook dinner now.',
      'She cooking dinner now.',
      'She is cooking dinner now.',
      'She cooks dinner now, right now.',
    ],
    answerIndex: 2,
    explain: 'Hiện tại tiếp diễn: am/is/are + V-ing.',
    topicIds: ['NP-12'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP12-03',
    prompt:
      'Right now, my father _____ (read) the newspaper in the living room.',
    options: ['read', 'reads', 'is reading', 'was reading'],
    answerIndex: 2,
    explain: '"Right now" báo hiệu hành động đang diễn ra ở hiện tại: "is reading".',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP12-04',
    prompt: 'Which sentence is correct?',
    options: [
      'Listen! Someone is knocking at the door.',
      'Listen! Someone knock at the door.',
      'Listen! Someone knocking at the door.',
      'Listen! Someone knocks at the door now.',
    ],
    answerIndex: 0,
    explain: '"Listen!" báo hiệu hành động đang xảy ra: "is knocking".',
    topicIds: ['NP-12'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP12-05',
    prompt: "We can't go out because it _____ heavily outside.",
    options: ['rain', 'rains', 'is raining', 'rained'],
    answerIndex: 2,
    explain: 'Mưa đang diễn ra ngay lúc nói: "is raining".',
    topicIds: ['NP-12'],
    skillId: 'KN-03',
  },
  // NP-14: Quá khứ tiếp diễn (4 câu mới, đã có 1 câu trong KN-06)
  {
    id: 'LQ-NP14-01',
    prompt: 'This time yesterday, I _____ (do) my homework.',
    options: ['do', 'did', 'was doing', 'am doing'],
    answerIndex: 2,
    explain: '"This time yesterday" diễn tả hành động đang xảy ra tại một thời điểm quá khứ: "was doing".',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP14-02',
    prompt: 'Which sentence is correct?',
    options: [
      'While I was cooking, the phone rang.',
      'While I cooked, the phone was ringing.',
      'While I was cooking, the phone was ring.',
      'While I cook, the phone rang.',
    ],
    answerIndex: 0,
    explain: 'Hành động nền dài dùng quá khứ tiếp diễn, hành động ngắn xen vào dùng quá khứ đơn.',
    topicIds: ['NP-14'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP14-03',
    prompt: 'What _____ you doing at 8 pm last night?',
    options: ['were', 'was', 'are', 'did'],
    answerIndex: 0,
    explain: 'Chủ ngữ "you" trong câu hỏi quá khứ tiếp diễn dùng "were".',
    topicIds: ['NP-14'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP14-04',
    prompt: 'Which sentence is correct?',
    options: [
      'They were watching TV when I arrived.',
      'They was watching TV when I arrived.',
      'They were watch TV when I arrived.',
      'They watching TV when I arrived.',
    ],
    answerIndex: 0,
    explain: 'Chủ ngữ số nhiều "they" dùng "were" + V-ing.',
    topicIds: ['NP-14'],
    skillId: 'KN-06',
  },
  // NP-15: Hiện tại hoàn thành (3 câu mới, đã có 2 câu trong KN-05/KN-06)
  {
    id: 'LQ-NP15-01',
    prompt: 'I _____ (see) that movie three times.',
    options: ['see', 'saw', 'have seen', 'seeing'],
    answerIndex: 2,
    explain: 'Không nói rõ thời điểm cụ thể, chỉ nói số lần: hiện tại hoàn thành "have seen".',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP15-02',
    prompt: 'Which sentence is correct?',
    options: [
      'She has lived here for ten years.',
      'She has lived here since ten years.',
      'She have lived here for ten years.',
      'She lived here for ten years now.',
    ],
    answerIndex: 0,
    explain: '"For" đi với khoảng thời gian ("for ten years"); chủ ngữ số ít dùng "has".',
    topicIds: ['NP-15'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP15-03',
    prompt: '_____ you ever been to Japan?',
    options: ['Have', 'Has', 'Did', 'Do'],
    answerIndex: 0,
    explain: 'Chủ ngữ "you" dùng "Have" trong câu hỏi hiện tại hoàn thành.',
    topicIds: ['NP-15'],
    skillId: 'KN-03',
  },
  // NP-16: Tương lai đơn (will) & used to (5 câu mới)
  {
    id: 'LQ-NP16-01',
    prompt: 'I think it _____ (rain) tomorrow.',
    options: ['rain', 'rains', 'will rain', 'rained'],
    answerIndex: 2,
    explain: 'Dự đoán về tương lai dùng "will + V nguyên thể".',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP16-02',
    prompt: 'Which sentence is correct?',
    options: [
      'She will helps you tomorrow.',
      'She will help you tomorrow.',
      'She wills help you tomorrow.',
      'She will helping you tomorrow.',
    ],
    answerIndex: 1,
    explain: 'Sau "will" luôn là động từ nguyên thể, không chia.',
    topicIds: ['NP-16'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP16-03',
    prompt: 'When I was young, I _____ to play in the park every day.',
    options: ['use', 'used', 'using', 'uses'],
    answerIndex: 1,
    explain: '"Used to + V" diễn tả thói quen trong quá khứ.',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ-NP16-04',
    prompt: 'Which sentence is correct?',
    options: [
      "He used to smoking, but he doesn't anymore.",
      "He used to smoke, but he doesn't anymore.",
      "He use to smoke, but he doesn't anymore.",
      "He was used to smoke, but he doesn't anymore.",
    ],
    answerIndex: 1,
    explain: '"Used to" theo sau bởi động từ nguyên thể: "used to smoke".',
    topicIds: ['NP-16'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ-NP16-05',
    prompt: 'I promise I _____ (help) you with your homework later.',
    options: ['help', 'helps', 'will help', 'helped'],
    answerIndex: 2,
    explain: 'Lời hứa dùng "will + V nguyên thể".',
    topicIds: ['NP-16'],
    skillId: 'KN-03',
  },
]

// ---- KN-08: Ngữ âm — trọng âm & phát âm (12 câu) ----
// Bổ sung sau khi xác minh THCS Cầu Giấy (trường mục tiêu) có thi phần này
// (4/40 câu — xem docs/adr/0002). Trước đó KN-08 để ngoài phạm vi theo Mục 13.
const kn08: Question[] = [
  {
    id: 'KN08-01',
    prompt: "Which word has a different sound for the letter 'a' from the others?",
    options: ['cat', 'hat', 'cake', 'bag'],
    answerIndex: 2,
    explain: '"Cake" có âm /eɪ/, ba từ còn lại có âm /æ/.',
    topicIds: ['TV-04'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-02',
    prompt: "Which word has a different sound for the underlined letters 'oo' from the others?",
    options: ['book', 'look', 'food', 'foot'],
    answerIndex: 2,
    explain: '"Food" có âm /uː/ dài, ba từ còn lại có âm /ʊ/ ngắn.',
    topicIds: ['TV-04'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-03',
    prompt: "Which word has a different sound for the underlined letters from the others?",
    options: ['tea', 'sea', 'bread', 'meat'],
    answerIndex: 2,
    explain: '"Bread" có âm /e/, ba từ còn lại có âm /iː/.',
    topicIds: ['TV-04'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-04',
    prompt: "Which word has the ending '-s' pronounced differently (as /s/ instead of /z/) from the others?",
    options: ['dogs', 'pens', 'balls', 'books'],
    answerIndex: 3,
    explain: '"Books" đọc là /s/, ba từ còn lại đọc là /z/.',
    topicIds: ['TV-03'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-05',
    prompt: "Which word has a different sound for the underlined letters 'th' from the others?",
    options: ['think', 'thank', 'this', 'three'],
    answerIndex: 2,
    explain: '"This" có âm /ð/ (hữu thanh), ba từ còn lại có âm /θ/ (vô thanh).',
    topicIds: ['TV-01'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-06',
    prompt: "Which word has a different sound for the letter 'c' from the others?",
    options: ['city', 'cat', 'cup', 'cold'],
    answerIndex: 0,
    explain: '"City" có âm /s/, ba từ còn lại có âm /k/.',
    topicIds: ['TV-09'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-07',
    prompt: 'Which word has stress on a different syllable from the others?',
    options: ['happy', 'garden', 'hello', 'table'],
    answerIndex: 2,
    explain: '"Hello" trọng âm rơi vào âm tiết 2, ba từ còn lại trọng âm rơi vào âm tiết 1.',
    topicIds: ['TV-01'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-08',
    prompt: 'Which word has stress on a different syllable from the others?',
    options: ['banana', 'apple', 'orange', 'yellow'],
    answerIndex: 0,
    explain: '"Banana" trọng âm rơi vào âm tiết 2, ba từ còn lại trọng âm rơi vào âm tiết 1.',
    topicIds: ['TV-04'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-09',
    prompt: 'Which word has stress on a different syllable from the others?',
    options: ['teacher', 'begin', 'open', 'window'],
    answerIndex: 1,
    explain: '"Begin" trọng âm rơi vào âm tiết 2, ba từ còn lại trọng âm rơi vào âm tiết 1.',
    topicIds: ['TV-02'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-10',
    prompt: 'Which word has stress on a different syllable from the others?',
    options: ['football', 'decide', 'morning', 'pencil'],
    answerIndex: 1,
    explain: '"Decide" trọng âm rơi vào âm tiết 2, ba từ còn lại trọng âm rơi vào âm tiết 1.',
    topicIds: ['TV-07'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-11',
    prompt: 'Which word has stress on a different syllable from the others?',
    options: ['holiday', 'important', 'animal', 'yesterday'],
    answerIndex: 1,
    explain: '"Important" trọng âm rơi vào âm tiết 2, ba từ còn lại trọng âm rơi vào âm tiết 1.',
    topicIds: ['TV-11'],
    skillId: 'KN-08',
  },
  {
    id: 'KN08-12',
    prompt: 'Which word has stress on a different syllable from the others?',
    options: ['beautiful', 'difficult', 'tomorrow', 'yesterday'],
    answerIndex: 2,
    explain: '"Tomorrow" trọng âm rơi vào âm tiết 2, ba từ còn lại trọng âm rơi vào âm tiết 1.',
    topicIds: ['TV-06'],
    skillId: 'KN-08',
  },
]

// ---- Quiz nhanh cho 12 bài học mới bổ sung ở Giai đoạn 6 (NP-01,03,06,07,
// 08,20,21,25,26,28) — chỉ thêm đủ để mỗi chủ điểm đạt tối thiểu 3 câu cho
// FR-L03 (NP-22, NP-23 đã đủ sẵn từ trước, không cần bổ sung). ----
const lessonQuiz2: Question[] = [
  // NP-01
  {
    id: 'LQ2-NP01-01',
    prompt: 'There _____ (be) too much sugar in this drink.',
    options: ['is', 'are', 'be', 'were'],
    answerIndex: 0,
    explain: '"Sugar" là danh từ không đếm được, luôn chia động từ số ít: "is".',
    topicIds: ['NP-01'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ2-NP01-02',
    prompt: 'Which sentence is correct?',
    options: [
      'I have three childs.',
      'I have three children.',
      'I have three child.',
      'I have three childrens.',
    ],
    answerIndex: 1,
    explain: '"Child" có số nhiều bất quy tắc là "children".',
    topicIds: ['NP-01'],
    skillId: 'KN-06',
  },
  // NP-03
  {
    id: 'LQ2-NP03-01',
    prompt: "This is not my pen. It's _____.",
    options: ['her', 'hers', 'she', 'herself'],
    answerIndex: 1,
    explain: 'Đại từ sở hữu đứng một mình (không kèm danh từ) là "hers".',
    topicIds: ['NP-03'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ2-NP03-02',
    prompt: 'Which sentence is correct?',
    options: [
      'Its raining outside.',
      "It's raining outside.",
      'Their raining outside.',
      "Its's raining outside.",
    ],
    answerIndex: 1,
    explain: '"It\'s" là viết tắt của "it is", dùng đúng ở đây.',
    topicIds: ['NP-03'],
    skillId: 'KN-06',
  },
  // NP-06
  {
    id: 'LQ2-NP06-01',
    prompt: 'Which sentence is correct?',
    options: [
      'This is the goodest movie I have seen.',
      'This is the best movie I have seen.',
      'This is the more good movie I have seen.',
      'This is the most good movie I have seen.',
    ],
    answerIndex: 1,
    explain: '"Good" có dạng so sánh nhất bất quy tắc là "best".',
    topicIds: ['NP-06'],
    skillId: 'KN-06',
  },
  // NP-07
  {
    id: 'LQ2-NP07-01',
    prompt: 'Which sentence is correct?',
    options: [
      'She is always happy.',
      'She always is happy.',
      'Always she is happy.',
      'She happy is always.',
    ],
    answerIndex: 0,
    explain: 'Trạng từ tần suất đứng sau động từ "to be": "is always".',
    topicIds: ['NP-07'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ2-NP07-02',
    prompt: 'He drives _____ (careful) on rainy days.',
    options: ['careful', 'carefully', 'care', 'carefulness'],
    answerIndex: 1,
    explain: 'Trạng từ cách thức bổ nghĩa cho động từ "drives": "carefully".',
    topicIds: ['NP-07'],
    skillId: 'KN-03',
  },
  // NP-08
  {
    id: 'LQ2-NP08-01',
    prompt: 'Which sentence is correct?',
    options: [
      'I was born in 15 May 2015.',
      'I was born on 15 May 2015.',
      'I was born at 15 May 2015.',
      'I was born by 15 May 2015.',
    ],
    answerIndex: 1,
    explain: 'Ngày cụ thể dùng giới từ "on".',
    topicIds: ['NP-08'],
    skillId: 'KN-06',
  },
  // NP-20
  {
    id: 'LQ2-NP20-01',
    prompt: 'If you mix blue and yellow, you _____ (get) green.',
    options: ['get', 'gets', 'got', 'will get'],
    answerIndex: 0,
    explain: 'Câu điều kiện loại 0 (sự thật hiển nhiên): cả hai vế dùng hiện tại đơn.',
    topicIds: ['NP-20'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ2-NP20-02',
    prompt: 'Which sentence is correct?',
    options: [
      'If she has free time, she will read books.',
      'If she will have free time, she reads books.',
      'If she have free time, she will read books.',
      'If she has free time, she reads will books.',
    ],
    answerIndex: 0,
    explain: 'Câu điều kiện loại 1: "If + hiện tại đơn, will + V nguyên thể".',
    topicIds: ['NP-20'],
    skillId: 'KN-06',
  },
  // NP-21
  {
    id: 'LQ2-NP21-01',
    prompt: 'This house _____ (build) in 1990.',
    options: ['built', 'was built', 'is build', 'builds'],
    answerIndex: 1,
    explain: 'Câu bị động quá khứ đơn: "was/were + V3".',
    topicIds: ['NP-21'],
    skillId: 'KN-03',
  },
  // NP-25
  {
    id: 'LQ2-NP25-01',
    prompt: 'Which sentence is correct?',
    options: [
      'She is good at play the piano.',
      'She is good at playing the piano.',
      'She is good to play the piano.',
      'She is good play the piano.',
    ],
    answerIndex: 1,
    explain: '"Be good at" theo sau bởi V-ing vì "at" là giới từ.',
    topicIds: ['NP-25'],
    skillId: 'KN-06',
  },
  // NP-26
  {
    id: 'LQ2-NP26-01',
    prompt: 'It was _____ difficult exam that many students failed.',
    options: ['so', 'such', 'too', 'very'],
    answerIndex: 1,
    explain: 'Trước cụm danh từ "a difficult exam" phải dùng "such".',
    topicIds: ['NP-26'],
    skillId: 'KN-03',
  },
  // NP-28
  {
    id: 'LQ2-NP28-01',
    prompt: 'I would rather _____ tea than coffee.',
    options: ['drink', 'to drink', 'drinking', 'drinks'],
    answerIndex: 0,
    explain: '"Would rather" theo sau bởi động từ nguyên thể không "to".',
    topicIds: ['NP-28'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ2-NP28-02',
    prompt: 'Which sentence is correct?',
    options: [
      'Would you like coming with us?',
      'Would you like to come with us?',
      'Would you liking to come with us?',
      'Would you to like come with us?',
    ],
    answerIndex: 1,
    explain: '"Would like" theo sau bởi "to V".',
    topicIds: ['NP-28'],
    skillId: 'KN-06',
  },
]

// ---- Quiz nhanh cho 13 bài học rà soát bổ sung (hoàn thiện đủ 31/31 chủ
// điểm ngữ pháp Mục 4.1): NP-02,04,05,09,10,17,18,19,24,27,29,30,31 ----
const lessonQuiz3: Question[] = [
  // NP-02
  {
    id: 'LQ3-NP02-01',
    prompt: 'I saw _____ elephant at the zoo.',
    options: ['a', 'an', 'the', '(không cần mạo từ)'],
    answerIndex: 1,
    explain: '"Elephant" bắt đầu bằng âm nguyên âm nên dùng "an".',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP02-02',
    prompt: 'Which sentence is correct?',
    options: [
      'I have a dog. The dog is very friendly.',
      'I have a dog. A dog is very friendly.',
      'I have the dog. The dog is very friendly.',
      'I have a dog. Dog is very friendly.',
    ],
    answerIndex: 0,
    explain: 'Nhắc lần đầu dùng "a dog", nhắc lại lần sau dùng "the dog".',
    topicIds: ['NP-02'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP02-03',
    prompt: 'We have _____ lunch at twelve o\'clock.',
    options: ['a', 'an', 'the', '(không cần mạo từ)'],
    answerIndex: 3,
    explain: 'Không dùng mạo từ trước tên bữa ăn.',
    topicIds: ['NP-02'],
    skillId: 'KN-03',
  },
  // NP-04
  {
    id: 'LQ3-NP04-01',
    prompt: "I didn't say _____ to her.",
    options: ['something', 'anything', 'nothing', 'everything'],
    answerIndex: 1,
    explain: 'Câu phủ định dùng "anything", không dùng "something".',
    topicIds: ['NP-04'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP04-02',
    prompt: 'Which sentence is correct?',
    options: [
      'The teacher who teaches us English is very kind.',
      'The teacher which teaches us English is very kind.',
      'The teacher who teach us English is very kind.',
      'The teacher whom teaches us English is very kind.',
    ],
    answerIndex: 0,
    explain: '"Who" dùng cho người, làm chủ ngữ nên động từ chia "teaches".',
    topicIds: ['NP-04'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP04-03',
    prompt: 'This is the pen _____ I bought yesterday.',
    options: ['who', 'which', 'whose', 'whom'],
    answerIndex: 1,
    explain: '"Which" dùng để thay thế cho vật ("the pen").',
    topicIds: ['NP-04'],
    skillId: 'KN-03',
  },
  // NP-05
  {
    id: 'LQ3-NP05-01',
    prompt: 'Which sentence is correct?',
    options: [
      'She has a black small cat.',
      'She has a small black cat.',
      'She has a cat small black.',
      'She has small a black cat.',
    ],
    answerIndex: 1,
    explain: 'Thứ tự tính từ: kích thước trước màu sắc — "small black cat".',
    topicIds: ['NP-05'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP05-02',
    prompt: 'The movie was really _____ (bore); many people fell asleep.',
    options: ['bore', 'bored', 'boring', 'bores'],
    answerIndex: 2,
    explain: 'Mô tả tính chất của bộ phim (gây cảm giác chán) dùng "-ing": "boring".',
    topicIds: ['NP-05'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP05-03',
    prompt: 'I was very _____ (excite) about the trip.',
    options: ['excite', 'excited', 'exciting', 'excitement'],
    answerIndex: 1,
    explain: 'Mô tả cảm xúc của người dùng "-ed": "excited".',
    topicIds: ['NP-05'],
    skillId: 'KN-03',
  },
  // NP-09
  {
    id: 'LQ3-NP09-01',
    prompt: 'Which sentence is correct?',
    options: [
      "I was tired because I didn't sleep well.",
      "I was tired because of I didn't sleep well.",
      "I was tired although I didn't sleep well.",
      "I was tired so I didn't sleep well.",
    ],
    answerIndex: 0,
    explain: '"Because" theo sau bởi một mệnh đề đầy đủ (chủ ngữ + động từ).',
    topicIds: ['NP-09'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP09-02',
    prompt: 'She stayed at home _____ it was raining heavily.',
    options: ['because', 'but', 'or', 'so'],
    answerIndex: 0,
    explain: 'Diễn tả nguyên nhân dùng "because".',
    topicIds: ['NP-09'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP09-03',
    prompt: 'He studied hard, _____ he passed the exam.',
    options: ['because', 'although', 'so', 'but'],
    answerIndex: 2,
    explain: 'Diễn tả kết quả dùng "so".',
    topicIds: ['NP-09'],
    skillId: 'KN-03',
  },
  // NP-10
  {
    id: 'LQ3-NP10-01',
    prompt: "There isn't _____ milk in the fridge.",
    options: ['some', 'any', 'many', 'a few'],
    answerIndex: 1,
    explain: 'Câu phủ định dùng "any".',
    topicIds: ['NP-10'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP10-02',
    prompt: 'Which sentence is correct?',
    options: [
      'How much books do you have?',
      'How many books do you have?',
      'How much book do you have?',
      'How many book do you have?',
    ],
    answerIndex: 1,
    explain: '"Books" là danh từ đếm được số nhiều, dùng "many".',
    topicIds: ['NP-10'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP10-03',
    prompt: 'I have _____ close friends, so I never feel lonely.',
    options: ['few', 'a few', 'little', 'much'],
    answerIndex: 1,
    explain: '"A few" mang nghĩa tích cực (có một vài, đủ để không cô đơn).',
    topicIds: ['NP-10'],
    skillId: 'KN-03',
  },
  // NP-17
  {
    id: 'LQ3-NP17-01',
    prompt: 'Which sentence is correct?',
    options: [
      'Where does he live?',
      'Where he does live?',
      'Where he lives?',
      'Where lives he?',
    ],
    answerIndex: 0,
    explain: 'Câu hỏi Wh- cần đảo trợ động từ lên trước chủ ngữ: "does he live".',
    topicIds: ['NP-17'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP17-02',
    prompt: 'You like chocolate, _____?',
    options: ["don't you", 'do you', "aren't you", "isn't it"],
    answerIndex: 0,
    explain: 'Câu kể khẳng định ("you like") có đuôi phủ định "don\'t you".',
    topicIds: ['NP-17'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP17-03',
    prompt: "He can't swim, _____?",
    options: ['can he', "can't he", 'does he', "can't you"],
    answerIndex: 0,
    explain: 'Câu kể phủ định ("can\'t swim") có đuôi khẳng định "can he".',
    topicIds: ['NP-17'],
    skillId: 'KN-03',
  },
  // NP-18
  {
    id: 'LQ3-NP18-01',
    prompt: 'Which sentence is correct?',
    options: [
      'The man who lives next door is a doctor.',
      'The man which lives next door is a doctor.',
      'The man who live next door is a doctor.',
      'The man whom lives next door is a doctor.',
    ],
    answerIndex: 0,
    explain: '"Who" dùng cho người, làm chủ ngữ số ít nên chia "lives".',
    topicIds: ['NP-18'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP18-02',
    prompt: 'Ha Noi, _____ is the capital of Vietnam, is a busy city.',
    options: ['who', 'which', 'that', 'whom'],
    answerIndex: 1,
    explain: 'Mệnh đề quan hệ không xác định (có dấu phẩy) không dùng "that".',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP18-03',
    prompt: 'This is the place _____ I first met my best friend.',
    options: ['who', 'which', 'where', 'whom'],
    answerIndex: 2,
    explain: '"Where" dùng để chỉ nơi chốn.',
    topicIds: ['NP-18'],
    skillId: 'KN-03',
  },
  // NP-19
  {
    id: 'LQ3-NP19-01',
    prompt: 'Which sentence is correct?',
    options: [
      'Although he was young, he was very brave.',
      'Although he was young, but he was very brave.',
      'Despite he was young, he was very brave.',
      'Although he was young, so he was very brave.',
    ],
    answerIndex: 0,
    explain: 'Không dùng cả "although" và "but" trong cùng một câu.',
    topicIds: ['NP-19'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP19-02',
    prompt: '_____ the bell rang, all the students stood up.',
    options: ['When', 'Because', 'Although', 'Despite'],
    answerIndex: 0,
    explain: 'Mệnh đề trạng ngữ chỉ thời gian dùng "when".',
    topicIds: ['NP-19'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP19-03',
    prompt: "She couldn't go out _____ she was sick.",
    options: ['because', 'although', 'but', 'or'],
    answerIndex: 0,
    explain: 'Mệnh đề trạng ngữ chỉ nguyên nhân dùng "because".',
    topicIds: ['NP-19'],
    skillId: 'KN-03',
  },
  // NP-24
  {
    id: 'LQ3-NP24-01',
    prompt: 'Which sentence is correct?',
    options: [
      'I enjoy reading books.',
      'I enjoy to read books.',
      'I enjoy read books.',
      'I enjoy to reading books.',
    ],
    answerIndex: 0,
    explain: '"Enjoy" theo sau bởi V-ing.',
    topicIds: ['NP-24'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP24-02',
    prompt: 'We decided _____ (go) to the beach this weekend.',
    options: ['go', 'going', 'to go', 'went'],
    answerIndex: 2,
    explain: '"Decide" theo sau bởi to-V.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP24-03',
    prompt: 'She finished _____ (write) the report yesterday.',
    options: ['write', 'to write', 'writing', 'wrote'],
    answerIndex: 2,
    explain: '"Finish" theo sau bởi V-ing.',
    topicIds: ['NP-24'],
    skillId: 'KN-03',
  },
  // NP-27
  {
    id: 'LQ3-NP27-01',
    prompt: 'A: "I love football." B: "_____"',
    options: ['So do I.', 'So I do.', 'Neither do I.', 'So am I.'],
    answerIndex: 0,
    explain: 'Đồng tình với câu khẳng định dùng "So + trợ động từ + chủ ngữ".',
    topicIds: ['NP-27'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP27-02',
    prompt: 'A: "I can\'t cook well." B: "_____"',
    options: ['Neither can I.', 'So can I.', 'Neither do I.', 'So do I.'],
    answerIndex: 0,
    explain: 'Đồng tình với câu phủ định dùng "Neither + trợ động từ + chủ ngữ".',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP27-03',
    prompt: 'A: "She doesn\'t like spicy food." B: "I don\'t, _____."',
    options: ['too', 'either', 'so', 'neither'],
    answerIndex: 1,
    explain: '"Either" đứng cuối câu phủ định để đồng tình.',
    topicIds: ['NP-27'],
    skillId: 'KN-03',
  },
  // NP-29
  {
    id: 'LQ3-NP29-01',
    prompt: 'I wish I _____ (have) a bigger house.',
    options: ['have', 'had', 'has', 'will have'],
    answerIndex: 1,
    explain: 'Ước hiện tại dùng "wish + quá khứ đơn".',
    topicIds: ['NP-29'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP29-02',
    prompt: 'Which sentence is correct?',
    options: [
      'I wish I was taller.',
      'I wish I am taller.',
      'I wish I were taller.',
      'I wish I will be taller.',
    ],
    answerIndex: 2,
    explain: 'Câu ước trang trọng dùng "were" cho mọi ngôi.',
    topicIds: ['NP-29'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP29-03',
    prompt: 'If only I _____ (study) harder last year!',
    options: ['study', 'studied', 'had studied', 'have studied'],
    answerIndex: 2,
    explain: 'Ước quá khứ (tiếc nuối) dùng "had + V3".',
    topicIds: ['NP-29'],
    skillId: 'KN-03',
  },
  // NP-30
  {
    id: 'LQ3-NP30-01',
    prompt: 'Which sentence is correct?',
    options: [
      'Everybody like the new film.',
      'Everybody likes the new film.',
      'Everybody are liking the new film.',
      'Everybody liking the new film.',
    ],
    answerIndex: 1,
    explain: '"Everybody" luôn được coi là số ít.',
    topicIds: ['NP-30'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP30-02',
    prompt: 'Each of the students _____ (have) a notebook.',
    options: ['have', 'has', 'having', 'had'],
    answerIndex: 1,
    explain: '"Each of" luôn đi với động từ số ít.',
    topicIds: ['NP-30'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP30-03',
    prompt: 'Nobody _____ (know) the secret.',
    options: ['know', 'knows', 'knowing', 'knew'],
    answerIndex: 1,
    explain: '"Nobody" luôn được coi là số ít.',
    topicIds: ['NP-30'],
    skillId: 'KN-03',
  },
  // NP-31
  {
    id: 'LQ3-NP31-01',
    prompt: 'Which sentence is correct?',
    options: [
      'Can you lend me your dictionary?',
      'Can you borrow me your dictionary?',
      'Can you lend from me your dictionary?',
      'Can you borrow from me your dictionary?',
    ],
    answerIndex: 0,
    explain: '"Lend" nghĩa là cho ai mượn, dùng đúng cấu trúc "lend me".',
    topicIds: ['NP-31'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ3-NP31-02',
    prompt: 'I need to _____ my homework before I watch TV.',
    options: ['make', 'do', 'take', 'have'],
    answerIndex: 1,
    explain: 'Cụm từ đúng là "do homework".',
    topicIds: ['NP-31'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ3-NP31-03',
    prompt: 'He _____ me an interesting story about his trip.',
    options: ['said', 'told', 'spoke', 'talked'],
    answerIndex: 1,
    explain: '"Tell" cần tân ngữ chỉ người ngay sau: "told me".',
    topicIds: ['NP-31'],
    skillId: 'KN-03',
  },
]

// ---- Quiz nhanh cho 5 chủ điểm đối chiếu giáo trình các trung tâm luyện
// thi (Casalink, MyPas, các bộ tổng hợp ngữ pháp phổ biến) — NP-32..36 ----
const lessonQuiz4: Question[] = [
  // NP-32: There is/There are
  {
    id: 'LQ4-NP32-01',
    prompt: '_____ a book on the table.',
    options: ['There is', 'There are', 'It is', 'They are'],
    answerIndex: 0,
    explain: '"Book" là danh từ số ít, dùng "There is".',
    topicIds: ['NP-32'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ4-NP32-02',
    prompt: 'Which sentence is correct?',
    options: [
      'There are much water in the bottle.',
      'There is much water in the bottle.',
      'There is many water in the bottle.',
      'There are many water in the bottle.',
    ],
    answerIndex: 1,
    explain: '"Water" là danh từ không đếm được, dùng "There is much water".',
    topicIds: ['NP-32'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ4-NP32-03',
    prompt: '_____ any pandas in Vietnam?',
    options: ['Is there', 'Are there', 'There is', 'There are'],
    answerIndex: 1,
    explain: '"Pandas" số nhiều, câu hỏi đảo động từ: "Are there".',
    topicIds: ['NP-32'],
    skillId: 'KN-03',
  },
  // NP-33: too...to / enough...to
  {
    id: 'LQ4-NP33-01',
    prompt: 'The music was _____ loud for the baby to sleep.',
    options: ['too', 'enough', 'very', 'so'],
    answerIndex: 0,
    explain: '"Too + adj + for sb + to V" diễn tả mức độ quá cao gây cản trở.',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ4-NP33-02',
    prompt: 'Which sentence is correct?',
    options: [
      'She is enough old to go to school.',
      'She is old enough to go to school.',
      'She is enough to old go to school.',
      'She old enough is to go to school.',
    ],
    answerIndex: 1,
    explain: '"Enough" đứng sau tính từ: "old enough".',
    topicIds: ['NP-33'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ4-NP33-03',
    prompt: 'This tea is _____ hot to drink right now.',
    options: ['too', 'enough', 'so', 'very'],
    answerIndex: 0,
    explain: '"Too + adj + to V" diễn tả không thể làm gì vì mức độ quá cao.',
    topicIds: ['NP-33'],
    skillId: 'KN-03',
  },
  // NP-34: Word form
  {
    id: 'LQ4-NP34-01',
    prompt: "Education is very important for children's _____ (develop).",
    options: ['develop', 'developing', 'development', 'developed'],
    answerIndex: 2,
    explain: 'Sau tính từ sở hữu cần danh từ: "development".',
    topicIds: ['NP-34'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ4-NP34-02',
    prompt: 'Which sentence is correct?',
    options: [
      'He speaks English fluent.',
      'He speaks English fluently.',
      'He speaks English fluency.',
      'He speaks English fluentness.',
    ],
    answerIndex: 1,
    explain: 'Bổ nghĩa cho động từ "speaks" cần trạng từ: "fluently".',
    topicIds: ['NP-34'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ4-NP34-03',
    prompt: 'She felt very _____ (happy) when she received the gift.',
    options: ['happy', 'happily', 'happiness', 'happier'],
    answerIndex: 0,
    explain: 'Sau động từ liên kết "felt" cần tính từ: "happy".',
    topicIds: ['NP-34'],
    skillId: 'KN-03',
  },
  // NP-35: one/ones, another/other(s)
  {
    id: 'LQ4-NP35-01',
    prompt: 'I lost my pen, so I need to buy a new _____.',
    options: ['one', 'ones', 'other', 'another'],
    answerIndex: 0,
    explain: 'Thay cho "pen" (số ít) dùng "one".',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ4-NP35-02',
    prompt: 'Which sentence is correct?',
    options: [
      'Some people like tea, other like coffee.',
      'Some people like tea, others like coffee.',
      'Some people like tea, another like coffee.',
      'Some people like tea, the other likes coffee.',
    ],
    answerIndex: 1,
    explain: '"Others" đứng một mình (không có danh từ theo sau).',
    topicIds: ['NP-35'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ4-NP35-03',
    prompt: 'This shirt is too small. Can you show me _____?',
    options: ['another one', 'other', 'others', 'the others'],
    answerIndex: 0,
    explain: '"Another one" nghĩa là "một cái khác" (số ít).',
    topicIds: ['NP-35'],
    skillId: 'KN-03',
  },
  // NP-36: make/let/have + O + V
  {
    id: 'LQ4-NP36-01',
    prompt: 'My teacher _____ (make) us practice speaking every day.',
    options: ['make', 'makes', 'making', 'made'],
    answerIndex: 1,
    explain: 'Chủ ngữ số ít "my teacher" chia động từ thêm "-s": "makes".',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
  },
  {
    id: 'LQ4-NP36-02',
    prompt: 'Which sentence is correct?',
    options: [
      'She let me to use her computer.',
      'She let me use her computer.',
      'She let me using her computer.',
      'She let I use her computer.',
    ],
    answerIndex: 1,
    explain: '"Let sb V" không có "to" trước động từ.',
    topicIds: ['NP-36'],
    skillId: 'KN-06',
  },
  {
    id: 'LQ4-NP36-03',
    prompt: 'The manager had the staff _____ (clean) the office before leaving.',
    options: ['clean', 'to clean', 'cleaning', 'cleaned'],
    answerIndex: 0,
    explain: '"Have sb V" không có "to" trước động từ.',
    topicIds: ['NP-36'],
    skillId: 'KN-03',
  },
]

export const questions: Question[] = [
  ...kn01,
  ...kn02,
  ...kn03,
  ...kn04,
  ...kn05,
  ...kn06,
  ...kn08,
  ...lessonQuiz,
  ...lessonQuiz2,
  ...lessonQuiz3,
  ...lessonQuiz4,
]
